#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

adjusted_budget_summary: null
budget_actual:
  dataset_detail_page: /datasets/budgeted-and-actual-provincial-expenditure/budgeted-and-actual-provincial-expenditure
  expenditure:
    base_financial_year: 2018-19
    nominal:
    - amount: 550964000
      financial_year: 2016-17
      phase: Main appropriation
    - amount: 591570000
      financial_year: 2017-18
      phase: Main appropriation
    - amount: null
      financial_year: 2016-17
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2016-17
      phase: Final Appropriation
    - amount: null
      financial_year: 2016-17
      phase: Audit Outcome
    - amount: null
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2017-18
      phase: Final Appropriation
    - amount: null
      financial_year: 2017-18
      phase: Audit Outcome
    - amount: null
      financial_year: 2018-19
      phase: Main appropriation
    - amount: null
      financial_year: 2018-19
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2018-19
      phase: Final Appropriation
    - amount: null
      financial_year: 2018-19
      phase: Audit Outcome
    - amount: null
      financial_year: 2019-20
      phase: Main appropriation
    - amount: null
      financial_year: 2019-20
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2019-20
      phase: Final Appropriation
    - amount: null
      financial_year: 2019-20
      phase: Audit Outcome
    real:
    - amount: 605278805
      financial_year: 2016-17
      phase: Main appropriation
    - amount: 620629054
      financial_year: 2017-18
      phase: Main appropriation
    - amount: null
      financial_year: 2016-17
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2016-17
      phase: Final Appropriation
    - amount: null
      financial_year: 2016-17
      phase: Audit Outcome
    - amount: null
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2017-18
      phase: Final Appropriation
    - amount: null
      financial_year: 2017-18
      phase: Audit Outcome
    - amount: null
      financial_year: 2018-19
      phase: Main appropriation
    - amount: null
      financial_year: 2018-19
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2018-19
      phase: Final Appropriation
    - amount: null
      financial_year: 2018-19
      phase: Audit Outcome
    - amount: null
      financial_year: 2019-20
      phase: Main appropriation
    - amount: null
      financial_year: 2019-20
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2019-20
      phase: Final Appropriation
    - amount: null
      financial_year: 2019-20
      phase: Audit Outcome
  notices:
  - Please note that the data for 2019 has not been published on vulekamali.
  - This department did not exist for some years displayed.
budget_actual_programmes:
  dataset_detail_page: /datasets/budgeted-and-actual-provincial-expenditure/budgeted-and-actual-provincial-expenditure
  notices:
  - One or more programmes did not exist for some years displayed.
  programmes:
  - items:
    - amount: 2066000
      financial_year: 2016-17
      phase: Main appropriation
    - amount: 2611000
      financial_year: 2017-18
      phase: Main appropriation
    - amount: null
      financial_year: 2016-17
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2016-17
      phase: Final Appropriation
    - amount: null
      financial_year: 2016-17
      phase: Audit Outcome
    - amount: null
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2017-18
      phase: Final Appropriation
    - amount: null
      financial_year: 2017-18
      phase: Audit Outcome
    - amount: null
      financial_year: 2018-19
      phase: Main appropriation
    - amount: null
      financial_year: 2018-19
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2018-19
      phase: Final Appropriation
    - amount: null
      financial_year: 2018-19
      phase: Audit Outcome
    - amount: null
      financial_year: 2019-20
      phase: Main appropriation
    - amount: null
      financial_year: 2019-20
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2019-20
      phase: Final Appropriation
    - amount: null
      financial_year: 2019-20
      phase: Audit Outcome
    name: Environmental Empowerment Services
  - items:
    - amount: 18181000
      financial_year: 2016-17
      phase: Main appropriation
    - amount: 21059000
      financial_year: 2017-18
      phase: Main appropriation
    - amount: null
      financial_year: 2016-17
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2016-17
      phase: Final Appropriation
    - amount: null
      financial_year: 2016-17
      phase: Audit Outcome
    - amount: null
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2017-18
      phase: Final Appropriation
    - amount: null
      financial_year: 2017-18
      phase: Audit Outcome
    - amount: null
      financial_year: 2018-19
      phase: Main appropriation
    - amount: null
      financial_year: 2018-19
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2018-19
      phase: Final Appropriation
    - amount: null
      financial_year: 2018-19
      phase: Audit Outcome
    - amount: null
      financial_year: 2019-20
      phase: Main appropriation
    - amount: null
      financial_year: 2019-20
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2019-20
      phase: Final Appropriation
    - amount: null
      financial_year: 2019-20
      phase: Audit Outcome
    name: Environmental Policy, Planning and Coordination
  - items:
    - amount: 23396000
      financial_year: 2016-17
      phase: Main appropriation
    - amount: 24827000
      financial_year: 2017-18
      phase: Main appropriation
    - amount: null
      financial_year: 2016-17
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2016-17
      phase: Final Appropriation
    - amount: null
      financial_year: 2016-17
      phase: Audit Outcome
    - amount: null
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2017-18
      phase: Final Appropriation
    - amount: null
      financial_year: 2017-18
      phase: Audit Outcome
    - amount: null
      financial_year: 2018-19
      phase: Main appropriation
    - amount: null
      financial_year: 2018-19
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2018-19
      phase: Final Appropriation
    - amount: null
      financial_year: 2018-19
      phase: Audit Outcome
    - amount: null
      financial_year: 2019-20
      phase: Main appropriation
    - amount: null
      financial_year: 2019-20
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2019-20
      phase: Final Appropriation
    - amount: null
      financial_year: 2019-20
      phase: Audit Outcome
    name: Compliance and Enforcement
  - items:
    - amount: 60138000
      financial_year: 2016-17
      phase: Main appropriation
    - amount: 65689000
      financial_year: 2017-18
      phase: Main appropriation
    - amount: null
      financial_year: 2016-17
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2016-17
      phase: Final Appropriation
    - amount: null
      financial_year: 2016-17
      phase: Audit Outcome
    - amount: null
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2017-18
      phase: Final Appropriation
    - amount: null
      financial_year: 2017-18
      phase: Audit Outcome
    - amount: null
      financial_year: 2018-19
      phase: Main appropriation
    - amount: null
      financial_year: 2018-19
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2018-19
      phase: Final Appropriation
    - amount: null
      financial_year: 2018-19
      phase: Audit Outcome
    - amount: null
      financial_year: 2019-20
      phase: Main appropriation
    - amount: null
      financial_year: 2019-20
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2019-20
      phase: Final Appropriation
    - amount: null
      financial_year: 2019-20
      phase: Audit Outcome
    name: Administration
  - items:
    - amount: 84965000
      financial_year: 2016-17
      phase: Main appropriation
    - amount: 84335000
      financial_year: 2017-18
      phase: Main appropriation
    - amount: null
      financial_year: 2016-17
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2016-17
      phase: Final Appropriation
    - amount: null
      financial_year: 2016-17
      phase: Audit Outcome
    - amount: null
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2017-18
      phase: Final Appropriation
    - amount: null
      financial_year: 2017-18
      phase: Audit Outcome
    - amount: null
      financial_year: 2018-19
      phase: Main appropriation
    - amount: null
      financial_year: 2018-19
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2018-19
      phase: Final Appropriation
    - amount: null
      financial_year: 2018-19
      phase: Audit Outcome
    - amount: null
      financial_year: 2019-20
      phase: Main appropriation
    - amount: null
      financial_year: 2019-20
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2019-20
      phase: Final Appropriation
    - amount: null
      financial_year: 2019-20
      phase: Audit Outcome
    name: Development Planning
  - items:
    - amount: 85185000
      financial_year: 2016-17
      phase: Main appropriation
    - amount: 90637000
      financial_year: 2017-18
      phase: Main appropriation
    - amount: null
      financial_year: 2016-17
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2016-17
      phase: Final Appropriation
    - amount: null
      financial_year: 2016-17
      phase: Audit Outcome
    - amount: null
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2017-18
      phase: Final Appropriation
    - amount: null
      financial_year: 2017-18
      phase: Audit Outcome
    - amount: null
      financial_year: 2018-19
      phase: Main appropriation
    - amount: null
      financial_year: 2018-19
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2018-19
      phase: Final Appropriation
    - amount: null
      financial_year: 2018-19
      phase: Audit Outcome
    - amount: null
      financial_year: 2019-20
      phase: Main appropriation
    - amount: null
      financial_year: 2019-20
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2019-20
      phase: Final Appropriation
    - amount: null
      financial_year: 2019-20
      phase: Audit Outcome
    name: Environmental Quality Management
  - items:
    - amount: 277033000
      financial_year: 2016-17
      phase: Main appropriation
    - amount: 302412000
      financial_year: 2017-18
      phase: Main appropriation
    - amount: null
      financial_year: 2016-17
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2016-17
      phase: Final Appropriation
    - amount: null
      financial_year: 2016-17
      phase: Audit Outcome
    - amount: null
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2017-18
      phase: Final Appropriation
    - amount: null
      financial_year: 2017-18
      phase: Audit Outcome
    - amount: null
      financial_year: 2018-19
      phase: Main appropriation
    - amount: null
      financial_year: 2018-19
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2018-19
      phase: Final Appropriation
    - amount: null
      financial_year: 2018-19
      phase: Audit Outcome
    - amount: null
      financial_year: 2019-20
      phase: Main appropriation
    - amount: null
      financial_year: 2019-20
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2019-20
      phase: Final Appropriation
    - amount: null
      financial_year: 2019-20
      phase: Audit Outcome
    name: Biodiversity Management
contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
department_adjusted_budget: null
department_budget: null
description: 'Western Cape department: Environmental Affairs and Development Planning
  budget data for the 2019-20 financial year from National Treasury in partnership
  with IMALI YETHU.'
economic_classification_by_programme: null
expenditure_over_time: null
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2018-19
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2019-20/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2019-20
  is_selected: true
government:
  name: Western Cape
  slug: western-cape
government_functions: []
intro: ''
is_vote_primary: true
name: Environmental Affairs and Development Planning
programme_by_economic_classification: null
programmes:
  programme_budgets: []
selected_financial_year: 2019-20
selected_tab: departments
slug: environmental-affairs-and-development-planning
sphere:
  name: provincial
  slug: provincial
subprogramme_by_programme: null
title: Environmental Affairs and Development Planning budget 2019-20  - vulekamali
vote_number: 9
vote_primary:
  name: Environmental Affairs and Development Planning
  slug: environmental-affairs-and-development-planning
  url_path: /2019-20/provincial/western-cape/departments/environmental-affairs-and-development-planning
website_url: null
