contributed_datasets: null
financial_years:
- closest_match:
    is_exact_match: true
    name: Economic Development, Environment and Tourism
    organisational_unit: department
    slug: economic-development-environment-and-tourism
    url_path: /2015-16/provincial/limpopo/departments/economic-development-environment-and-tourism
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Economic Development, Environment and Tourism
    organisational_unit: department
    slug: economic-development-environment-and-tourism
    url_path: /2016-17/provincial/limpopo/departments/economic-development-environment-and-tourism
  id: 2016-17
  is_selected: true
- closest_match:
    is_exact_match: true
    name: Economic Development, Environment and Tourism
    organisational_unit: department
    slug: economic-development-environment-and-tourism
    url_path: /2017-18/provincial/limpopo/departments/economic-development-environment-and-tourism
  id: 2017-18
  is_selected: false
government:
  name: Limpopo
  slug: limpopo
government_functions: []
intro: "## Vision\r\n\r\nA competitive economy within a sustainable environment.\r\
  \n\r\n\r\n\r\n## Mission\r\n\r\nTo create and facilitate the development of a competitive\
  \ economy, sustainable environment and\r\ntourism growth.\r\n\r\n\r\n\r\n## Main\
  \ services\r\n\r\nThe mandate of the Department is to facilitate the provincial\
  \ economy, promote and manage\r\nenvironmental and tourism activities. To carry\
  \ out this mandate, the department pursues the\r\nfollowing:\r\n\r\n\u2022 Improve\
  \ service delivery to communities and stakeholders through a skilled, accountable,\r\
  \ncorrupt free, development oriented and empowered and intergraded Public Service.\r\
  \n\r\n\u2022 Accelerate employment creation, economic growth and development.\r\n\
  \r\n\u2022 Ensure sustainable development through targeted intervention on environmental\
  \ management,\r\ndevelopment of natural resources, creation of green jobs and proactive\
  \ responses to climate\r\nchange.\r\n\r\n\u2022 To position Limpopo as a preferred\
  \ tourist and investment destination within Southern African\r\nDeveloping Countries(SADC)\
  \ and the World.\r\n\r\n\u2022 Transform Limpopo into a world class knowledge society\
  \ that uses ICT as an enabler of socioeconomic\r\ndevelopment and ICT as a production\
  \ sector."
is_vote_primary: true
name: Economic Development, Environment and Tourism
organisational_unit: department
programmes:
- name: Administration
  total_budget: 348019000.0
- name: Economic Development
  total_budget: 477147000.0
- name: Environmental Affairs
  total_budget: 371279000.0
- name: Tourism
  total_budget: 136485000.0
selected_financial_year: 2016-17
slug: economic-development-environment-and-tourism
sphere:
  name: Provincial
  slug: provincial
treasury_datasets:
  'EPRE for Vote 06 : Economic Development, Environment and Tourism':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/1cf5e0b0-ecd8-4e04-bc40-aa70691140b2/resource/aae74592-d1a4-4e71-9c4a-02ebbfa28873/download/lim-eco.-dev.-env.-and-tourism.xlsm
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2016/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/LIM/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/LIM
        - Vote 06 - Economic Dev., Environ. & Tourism.pdf
vote_number: 6
vote_primary:
  name: Economic Development, Environment and Tourism
  slug: economic-development-environment-and-tourism
  url_path: /2016-17/provincial/limpopo/departments/economic-development-environment-and-tourism
