#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
description: 'Northern Cape department: Environment and Nature Conservation budget
  data for the 2015-16 financial year from National Treasury in partnership with IMALI
  YETHU.'
economic_classification_by_programme:
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 35566000
    - economic_classification_2_name: Goods and services
      total_budget: 19256000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 150000
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Public corporations and private enterprises
      total_budget: 200000
  programme_name: Administration
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 20430000
    - economic_classification_2_name: Goods and services
      total_budget: 6791000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 150000
  programme_name: Biodiversity Management
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 10427000
    - economic_classification_2_name: Goods and services
      total_budget: 2785000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Buildings and other fixed structures
      total_budget: 90000
    - economic_classification_2_name: Machinery and equipment
      total_budget: 60000
  programme_name: Compliance And Enforcement
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 9956000
    - economic_classification_2_name: Goods and services
      total_budget: 2068000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 150000
  programme_name: Environmental Empowerment Services
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 8663000
    - economic_classification_2_name: Goods and services
      total_budget: 1091000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 200000
  programme_name: Environmental Policy,Planning And Coordination
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 9376000
    - economic_classification_2_name: Goods and services
      total_budget: 2686000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 1150000
  programme_name: Environmental Quality Management
expenditure_over_time:
  base_financial_year: 2017-18
  nominal:
  - amount: 98543000
    financial_year: 2011-12
    phase: Audited Outcome
  - amount: 102739000
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 117641000
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 127600000
    financial_year: 2014-15
    phase: Adjusted appropriation
  - amount: 131245000
    financial_year: 2015-16
    phase: Main appropriation
  - amount: 136792000
    financial_year: 2016-17
    phase: Medium Term Estimates
  - amount: 143631000
    financial_year: 2017-18
    phase: Medium Term Estimates
  real:
  - amount: 136299735
    financial_year: 2011-12
    phase: Audited Outcome
  - amount: 134641549
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 145695798
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 149612610
    financial_year: 2014-15
    phase: Adjusted appropriation
  - amount: 146325882
    financial_year: 2015-16
    phase: Main appropriation
  - amount: 143478118
    financial_year: 2016-17
    phase: Medium Term Estimates
  - amount: 143631000
    financial_year: 2017-18
    phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2015-16
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2018-19
  is_selected: false
government:
  name: Northern Cape
  slug: northern-cape
government_functions: []
intro: "## Vision\n\nA prosperous society living sustainably with the natural environment.\r\
  \n\r\n\n\n## Mission\n\nConserve and protect the natural environment for the benefit,\
  \ enjoyment and welfare of present and future generations by integrating sustainable\
  \ utilization with socio-economic development.\r\n\r\n\n\n## Core functions\n\n\
  * Environmental assets conserved, valued, sustainably used, protected and continually\
  \ enhanced;\r\n\r\n* Enhanced socio-economic benefits and employment creation for\
  \ the present and future generations from a healthy environment;\r\n\r\n* A department\
  \ that is fully capacitated to deliver its services efficiently and effectively;\r\
  \n\r\n* Environmental education provided to stimulate critical thinking and influence\
  \ decision making;\r\n\r\n* Ensure sustainable development and utilisation of natural\
  \ resources while securing representative and resilient ecosystems through scientific\
  \ research, spatial planning and cooperative governance;\r\n\r\n* To promote and\
  \ enforce compliance with environmental legislation.\r\n"
is_vote_primary: true
name: Environment and Nature Conservation
programmes:
- name: Administration
  total_budget: 55172000
- name: Environmental Policy,Planning And Coordination
  total_budget: 9954000
- name: Compliance And Enforcement
  total_budget: 13362000
- name: Environmental Quality Management
  total_budget: 13212000
- name: Biodiversity Management
  total_budget: 27371000
- name: Environmental Empowerment Services
  total_budget: 12174000
selected_financial_year: 2015-16
selected_tab: departments
slug: environment-and-nature-conservation
sphere:
  name: Provincial
  slug: provincial
title: Environment and Nature Conservation budget 2015-16  - vulekamali
treasury_datasets:
  'EPRE for Vote 13 : Environment and Nature Conservation':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSX
      url: https://data.vulekamali.gov.za/dataset/bcd06a1c-4409-45e0-912a-dee6b1ffd23f/resource/ffcac4a5-b0a6-4155-bb29-2deabc6c3b8c/download/nc-environment-and-nature-conservation.xlsx
    - format: PDF
      url: https://data.vulekamali.gov.za/dataset/bcd06a1c-4409-45e0-912a-dee6b1ffd23f/resource/4702b2d5-6d2e-40c3-ad7e-a816f4864457/download/nc-vote-13-environment-and-nature-conservation.pdf
vote_number: 13
vote_primary:
  name: Environment and Nature Conservation
  slug: environment-and-nature-conservation
  url_path: /2015-16/provincial/northern-cape/departments/environment-and-nature-conservation
