financial_years:
- closest_match:
    is_exact_match: true
    name: Environment and Nature Conservation
    organisational_unit: department
    slug: environment-and-nature-conservation
    url_path: /2015-16/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2015-16
  is_selected: true
- closest_match:
    is_exact_match: true
    name: Environment and Nature Conservation
    organisational_unit: department
    slug: environment-and-nature-conservation
    url_path: /2016-17/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Environment and Nature Conservation
    organisational_unit: department
    slug: environment-and-nature-conservation
    url_path: /2017-18/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2017-18
  is_selected: false
government:
  name: Northern Cape
  slug: northern-cape
name: Environment and Nature Conservation
narrative: {}
resources:
  'EPRE for Vote 13 : Environment and Nature Conservation':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSX
      url: https://treasurydata.openup.org.za/dataset/bcd06a1c-4409-45e0-912a-dee6b1ffd23f/resource/ffcac4a5-b0a6-4155-bb29-2deabc6c3b8c/download/nc-environment-and-nature-conservation.xlsx
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2015/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/NC/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/NC
        - Vote 13 - Environment and Nature Conservation.pdf
slug: environment-and-nature-conservation
vote_number: 13
