#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
department_adjusted_budget: null
department_budget:
  document:
    description: ''
    format: PDF
    name: 'Vote 03 : Department of Economic and Small Business Development, Tourism
      and Environmental Affairs'
    url: https://data.vulekamali.gov.za/dataset/3868892c-3259-46b8-9d4c-96a064be8bbc/resource/457a43f6-f885-4c86-aafc-595191127cb2/download/fs-vote-03-eco-and-small-bus.-dev.-tourism-and-env-affairs.pdf
  name: 'Free State Department: Economic and Small Business Development, Tourism and
    Environmental Affairs 2016-17'
  tables: null
description: 'Free State department: Economic and Small Business Development, Tourism
  and Environmental Affairs budget data for the 2016-17 financial year from National
  Treasury in partnership with IMALI YETHU.'
economic_classification_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2016-17
  programmes:
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 88284000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 51261000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 1670000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Departmental agencies and accounts
        total_budget: 4000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Administration
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 32659000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 19901000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 881000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Departmental agencies and accounts
        total_budget: 55551000
        type: economic_classification_2
      - name: Public corporations and private enterprises
        total_budget: 13508000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Economic and Small Business Development
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 93363000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 35904000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Buildings and other fixed structures
        total_budget: 39148000
        type: economic_classification_2
      - name: Machinery and equipment
        total_budget: 3148000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Departmental agencies and accounts
        total_budget: 182000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Environmental Affairs
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 8348000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 6300000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 249000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Departmental agencies and accounts
        total_budget: 43187000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Tourism
    type: programme
expenditure_over_time:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2016-17
  expenditure:
    base_financial_year: 2017-18
    nominal:
    - amount: 407139000
      financial_year: 2012-13
      phase: Audited Outcome
    - amount: 432354000
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 429772000
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 468788000
      financial_year: 2015-16
      phase: Adjusted appropriation
    - amount: 493548000
      financial_year: 2016-17
      phase: Main appropriation
    - amount: 511786000
      financial_year: 2017-18
      phase: Medium Term Estimates
    - amount: 537550000
      financial_year: 2018-19
      phase: Medium Term Estimates
    real:
    - amount: 533563941
      financial_year: 2012-13
      phase: Audited Outcome
    - amount: 535460947
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 503913094
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 522654712
      financial_year: 2015-16
      phase: Adjusted appropriation
    - amount: 517671637
      financial_year: 2016-17
      phase: Main appropriation
    - amount: 511786000
      financial_year: 2017-18
      phase: Medium Term Estimates
    - amount: 509566569
      financial_year: 2018-19
      phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2016-17
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2018-19
  is_selected: false
government:
  name: Free State
  slug: free-state
government_functions: []
intro: "## Vision\r\n\r\nA transformed economy and a prosperous society that is living\
  \ in harmony with its\r\nnatural resources through integrated and sustainable economic\
  \ growth.\r\n\r\n\r\n\r\n## Mission\r\n\r\nRadically create a conducive, enabling\
  \ environment for the creation of decent jobs,\r\npoverty and inequality reduction\
  \ through sustainably managed environment and\r\neconomic development programmes\
  \ in the Free State."
is_vote_primary: true
name: Economic and Small Business Development, Tourism and Environmental Affairs
programme_by_economic_classification:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2016-17
  econ_classes:
  - items:
    - name: Environmental Affairs
      total_budget: 93363000
      type: programme
    - name: Administration
      total_budget: 88284000
      type: programme
    - name: Economic and Small Business Development
      total_budget: 32659000
      type: programme
    - name: Tourism
      total_budget: 8348000
      type: programme
    name: Current payments - Compensation of employees
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 51261000
      type: programme
    - name: Environmental Affairs
      total_budget: 35904000
      type: programme
    - name: Economic and Small Business Development
      total_budget: 19901000
      type: programme
    - name: Tourism
      total_budget: 6300000
      type: programme
    name: Current payments - Goods and services
    type: economic_classification_1_and_2
  - items:
    - name: Environmental Affairs
      total_budget: 39148000
      type: programme
    name: Payments for capital assets - Buildings and other fixed structures
    type: economic_classification_1_and_2
  - items:
    - name: Environmental Affairs
      total_budget: 3148000
      type: programme
    - name: Administration
      total_budget: 1670000
      type: programme
    - name: Economic and Small Business Development
      total_budget: 881000
      type: programme
    - name: Tourism
      total_budget: 249000
      type: programme
    name: Payments for capital assets - Machinery and equipment
    type: economic_classification_1_and_2
  - items:
    - name: Economic and Small Business Development
      total_budget: 55551000
      type: programme
    - name: Tourism
      total_budget: 43187000
      type: programme
    - name: Environmental Affairs
      total_budget: 182000
      type: programme
    - name: Administration
      total_budget: 4000
      type: programme
    name: Transfers and subsidies - Departmental agencies and accounts
    type: economic_classification_1_and_2
  - items:
    - name: Economic and Small Business Development
      total_budget: 13508000
      type: programme
    name: Transfers and subsidies - Public corporations and private enterprises
    type: economic_classification_1_and_2
programmes:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2016-17
  programme_budgets:
  - name: Administration
    total_budget: 141219000
  - name: Environmental Affairs
    total_budget: 171745000
  - name: Economic and Small Business Development
    total_budget: 122500000
  - name: Tourism
    total_budget: 58084000
selected_financial_year: 2016-17
selected_tab: departments
slug: economic-and-small-business-development-tourism-and-environmental-affairs
sphere:
  name: Provincial
  slug: provincial
subprogramme_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/epre-sub-programme-expenditure-2016-17
  programmes: []
title: Economic and Small Business Development, Tourism and Environmental Affairs
  budget 2016-17  - vulekamali
vote_number: 3
vote_primary:
  name: Economic and Small Business Development, Tourism and Environmental Affairs
  slug: economic-and-small-business-development-tourism-and-environmental-affairs
  url_path: /2016-17/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
