contributed_datasets: null
financial_years:
- closest_match:
    is_exact_match: true
    name: Economic and Small Business Development,  Tourism and Environmental Affairs
    organisational_unit: department
    slug: economic-and-small-business-development-tourism-and-environmental-affairs
    url_path: /2015-16/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Economic and Small Business Development, Tourism and Environmental Affairs
    organisational_unit: department
    slug: economic-and-small-business-development-tourism-and-environmental-affairs
    url_path: /2016-17/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2016-17
  is_selected: true
- closest_match:
    is_exact_match: true
    name: Economic and Small Business Development, Tourism and Environmental Affairs
    organisational_unit: department
    slug: economic-and-small-business-development-tourism-and-environmental-affairs
    url_path: /2017-18/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2017-18
  is_selected: false
government:
  name: Free State
  slug: free-state
government_functions: []
intro: "## Vision\r\n\r\nA transformed economy and a prosperous society that is living\
  \ in harmony with its\r\nnatural resources through integrated and sustainable economic\
  \ growth.\r\n\r\n\r\n\r\n## Mission\r\n\r\nRadically create a conducive, enabling\
  \ environment for the creation of decent jobs,\r\npoverty and inequality reduction\
  \ through sustainably managed environment and\r\neconomic development programmes\
  \ in the Free State."
is_vote_primary: true
name: Economic and Small Business Development, Tourism and Environmental Affairs
organisational_unit: department
programmes:
- name: Administration
  total_budget: 141219000.0
- name: Environmental Affairs
  total_budget: 171745000.0
- name: Economic and Small Business Development
  total_budget: 122500000.0
- name: Tourism
  total_budget: 58084000.0
selected_financial_year: 2016-17
slug: economic-and-small-business-development-tourism-and-environmental-affairs
sphere:
  name: Provincial
  slug: provincial
treasury_datasets:
  'EPRE for Vote 03 : Department of Economic and Small Business Development, Tourism and Environmental Affairs':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/3868892c-3259-46b8-9d4c-96a064be8bbc/resource/c18ba2bf-a7ab-495a-a453-b95a2a559bf7/download/fs-economic-small-busin-dev-tourism.xlsm
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2016/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/FS/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/FS
        - Vote 03 - Eco and Small Bus. Dev., Tourism and Env Affairs.pdf
vote_number: 3
vote_primary:
  name: Economic and Small Business Development, Tourism and Environmental Affairs
  slug: economic-and-small-business-development-tourism-and-environmental-affairs
  url_path: /2016-17/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
