contributed_datasets: null
description: 'Free State department: Economic and Small Business Development, Tourism
  and Environmental Affairs budget data for the 2016-17 financial year from National
  Treasury in partnership with IMALI YETHU.'
expenditure_over_time:
  base_financial_year: 2017-18
  nominal:
  - amount: 407139000.0
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 432354000.0
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 429772000.0
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 468788000.0
    financial_year: 2015-16
    phase: Adjusted appropriation
  - amount: 493548000.0
    financial_year: 2016-17
    phase: Main appropriation
  - amount: 511786000.0
    financial_year: 2017-18
    phase: Medium Term Estimates
  - amount: 537550000.0
    financial_year: 2018-19
    phase: Medium Term Estimates
  real:
  - amount: 533563941
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 535460947
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 503913094
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 522654712
    financial_year: 2015-16
    phase: Adjusted appropriation
  - amount: 517671637
    financial_year: 2016-17
    phase: Main appropriation
  - amount: 511786000
    financial_year: 2017-18
    phase: Medium Term Estimates
  - amount: 509566569
    financial_year: 2018-19
    phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2016-17
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: false
    url_path: /2018-19/provincial/free-state
  id: 2018-19
  is_selected: false
government:
  name: Free State
  slug: free-state
government_functions: []
intro: "## Vision\r\n\r\nA transformed economy and a prosperous society that is living\
  \ in harmony with its\r\nnatural resources through integrated and sustainable economic\
  \ growth.\r\n\r\n\r\n\r\n## Mission\r\n\r\nRadically create a conducive, enabling\
  \ environment for the creation of decent jobs,\r\npoverty and inequality reduction\
  \ through sustainably managed environment and\r\neconomic development programmes\
  \ in the Free State."
is_vote_primary: true
name: Economic and Small Business Development, Tourism and Environmental Affairs
programmes:
- name: Administration
  total_budget: 141219000.0
- name: Environmental Affairs
  total_budget: 171745000.0
- name: Economic and Small Business Development
  total_budget: 122500000.0
- name: Tourism
  total_budget: 58084000.0
selected_financial_year: 2016-17
selected_tab: departments
slug: economic-and-small-business-development-tourism-and-environmental-affairs
sphere:
  name: Provincial
  slug: provincial
title: Economic and Small Business Development, Tourism and Environmental Affairs
  budget 2016-17  - vulekamali
treasury_datasets:
  'EPRE for Vote 03 : Department of Economic and Small Business Development, Tourism and Environmental Affairs':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/3868892c-3259-46b8-9d4c-96a064be8bbc/resource/c18ba2bf-a7ab-495a-a453-b95a2a559bf7/download/fs-economic-small-busin-dev-tourism.xlsm
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2016/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/FS/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/FS
        - Vote 03 - Eco and Small Bus. Dev., Tourism and Env Affairs.pdf
vote_number: 3
vote_primary:
  name: Economic and Small Business Development, Tourism and Environmental Affairs
  slug: economic-and-small-business-development-tourism-and-environmental-affairs
  url_path: /2016-17/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
