#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
department_adjusted_budget: null
department_budget:
  document:
    description: ''
    format: PDF
    name: 'Vote 13 : Rural Environment and Agricultural Development'
    url: https://data.vulekamali.gov.za/dataset/ddc0398f-4eb6-4789-86f5-cdfd93e68fca/resource/4d2130ec-870d-4d9b-9aba-eea21cdaf990/download/nw-vote-13-rural-environment-and-agricultural-development.pdf
  name: 'North West Department: Rural Environment and Agricultural Development 2016-17'
  tables: null
description: 'North West department: Rural Environment and Agricultural Development
  budget data for the 2016-17 financial year from National Treasury in partnership
  with IMALI YETHU.'
economic_classification_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2016-17
  programmes:
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 136304000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 102617000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 1252000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Households
        total_budget: 2990000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Administration
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 10076000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 1806000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 48000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    name: Agricultural Economics Services
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 77416000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 35683000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Buildings and other fixed structures
        total_budget: 40000000
        type: economic_classification_2
      - name: Machinery and equipment
        total_budget: 2552000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Departmental agencies and accounts
        total_budget: 101830000
        type: economic_classification_2
      - name: Households
        total_budget: 168000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Environmental Services
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 133968000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 40938000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 386000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Households
        total_budget: 216483000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Farmer Support and Development
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 48150000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 10407000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Biological assets
        total_budget: 850000
        type: economic_classification_2
      - name: Machinery and equipment
        total_budget: 570000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    name: Research and Technology  Development Services
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 18308000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 10258000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Households
        total_budget: 25988000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Rural Development Coordination
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 59512000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 34116000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 845000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Households
        total_budget: 6163000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Structured Agricultural Education and  Training
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 32836000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 8301000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Households
        total_budget: 7621000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Sustainable Resource Management
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 87942000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 23269000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 5187000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    name: Veterinary Services
    type: programme
expenditure_over_time:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2016-17
  expenditure:
    base_financial_year: 2017-18
    nominal:
    - amount: 923443000
      financial_year: 2012-13
      phase: Audited Outcome
    - amount: 1072012000
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 1169275000
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 1200692000
      financial_year: 2015-16
      phase: Adjusted appropriation
    - amount: 1284840000
      financial_year: 2016-17
      phase: Main appropriation
    - amount: 1383759000
      financial_year: 2017-18
      phase: Medium Term Estimates
    - amount: 1468589000
      financial_year: 2018-19
      phase: Medium Term Estimates
    real:
    - amount: 1210190836
      financial_year: 2012-13
      phase: Audited Outcome
    - amount: 1327663352
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 1370989694
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 1338659121
      financial_year: 2015-16
      phase: Adjusted appropriation
    - amount: 1347640404
      financial_year: 2016-17
      phase: Main appropriation
    - amount: 1383759000
      financial_year: 2017-18
      phase: Medium Term Estimates
    - amount: 1392138141
      financial_year: 2018-19
      phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2016-17
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2018-19
  is_selected: false
government:
  name: North West
  slug: north-west
government_functions: []
intro: "## Vision\n\nVibrant and prosperous society in harmony with our natural resources.\r\
  \n\r\n\r\n\n\n## Mission\n\nWorking together with our partners to provide sustainable\
  \ agricultural, environmental management and comprehensive integrated rural development.\r\
  \n\r\n\r\n\n\n## Core functions of the department\n\n* The Department focus primarily\
  \ on the following mandated core functions:\r\n\r\n* Rolling out the Comprehensive\
  \ Rural Development Programme\r\n\r\n* Creating decent employment through Inclusive\
  \ Economic Growth\r\n\r\n\r\n* Protecting and Enhancing Environmental Assets and\
  \ Natural Resources"
is_vote_primary: true
name: Rural Environment and Agricultural Development
programme_by_economic_classification:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2016-17
  econ_classes:
  - items:
    - name: Administration
      total_budget: 136304000
      type: programme
    - name: Farmer Support and Development
      total_budget: 133968000
      type: programme
    - name: Veterinary Services
      total_budget: 87942000
      type: programme
    - name: Environmental Services
      total_budget: 77416000
      type: programme
    - name: Structured Agricultural Education and  Training
      total_budget: 59512000
      type: programme
    - name: Research and Technology  Development Services
      total_budget: 48150000
      type: programme
    - name: Sustainable Resource Management
      total_budget: 32836000
      type: programme
    - name: Rural Development Coordination
      total_budget: 18308000
      type: programme
    - name: Agricultural Economics Services
      total_budget: 10076000
      type: programme
    name: Current payments - Compensation of employees
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 102617000
      type: programme
    - name: Farmer Support and Development
      total_budget: 40938000
      type: programme
    - name: Environmental Services
      total_budget: 35683000
      type: programme
    - name: Structured Agricultural Education and  Training
      total_budget: 34116000
      type: programme
    - name: Veterinary Services
      total_budget: 23269000
      type: programme
    - name: Research and Technology  Development Services
      total_budget: 10407000
      type: programme
    - name: Rural Development Coordination
      total_budget: 10258000
      type: programme
    - name: Sustainable Resource Management
      total_budget: 8301000
      type: programme
    - name: Agricultural Economics Services
      total_budget: 1806000
      type: programme
    name: Current payments - Goods and services
    type: economic_classification_1_and_2
  - items:
    - name: Research and Technology  Development Services
      total_budget: 850000
      type: programme
    name: Payments for capital assets - Biological assets
    type: economic_classification_1_and_2
  - items:
    - name: Environmental Services
      total_budget: 40000000
      type: programme
    name: Payments for capital assets - Buildings and other fixed structures
    type: economic_classification_1_and_2
  - items:
    - name: Veterinary Services
      total_budget: 5187000
      type: programme
    - name: Environmental Services
      total_budget: 2552000
      type: programme
    - name: Administration
      total_budget: 1252000
      type: programme
    - name: Structured Agricultural Education and  Training
      total_budget: 845000
      type: programme
    - name: Research and Technology  Development Services
      total_budget: 570000
      type: programme
    - name: Farmer Support and Development
      total_budget: 386000
      type: programme
    - name: Agricultural Economics Services
      total_budget: 48000
      type: programme
    name: Payments for capital assets - Machinery and equipment
    type: economic_classification_1_and_2
  - items:
    - name: Environmental Services
      total_budget: 101830000
      type: programme
    name: Transfers and subsidies - Departmental agencies and accounts
    type: economic_classification_1_and_2
  - items:
    - name: Farmer Support and Development
      total_budget: 216483000
      type: programme
    - name: Rural Development Coordination
      total_budget: 25988000
      type: programme
    - name: Sustainable Resource Management
      total_budget: 7621000
      type: programme
    - name: Structured Agricultural Education and  Training
      total_budget: 6163000
      type: programme
    - name: Administration
      total_budget: 2990000
      type: programme
    - name: Environmental Services
      total_budget: 168000
      type: programme
    name: Transfers and subsidies - Households
    type: economic_classification_1_and_2
programmes:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2016-17
  programme_budgets:
  - name: Administration
    total_budget: 243163000
  - name: Sustainable Resource Management
    total_budget: 48758000
  - name: Farmer Support and Development
    total_budget: 391775000
  - name: Veterinary Services
    total_budget: 116398000
  - name: Research and Technology  Development Services
    total_budget: 59977000
  - name: Agricultural Economics Services
    total_budget: 11930000
  - name: Structured Agricultural Education and  Training
    total_budget: 100636000
  - name: Rural Development Coordination
    total_budget: 54554000
  - name: Environmental Services
    total_budget: 257649000
selected_financial_year: 2016-17
selected_tab: departments
slug: rural-environment-and-agricultural-development
sphere:
  name: Provincial
  slug: provincial
subprogramme_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/epre-sub-programme-expenditure-2016-17
  programmes: []
title: Rural Environment and Agricultural Development budget 2016-17  - vulekamali
vote_number: 13
vote_primary:
  name: Rural Environment and Agricultural Development
  slug: rural-environment-and-agricultural-development
  url_path: /2016-17/provincial/north-west/departments/rural-environment-and-agricultural-development
