#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
description: 'North West department: Rural Environment and Agricultural Development
  budget data for the 2016-17 financial year from National Treasury in partnership
  with IMALI YETHU.'
economic_classification_by_programme:
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 136304000
    - economic_classification_2_name: Goods and services
      total_budget: 102617000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 1252000
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Households
      total_budget: 2990000
  programme_name: Administration
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 10076000
    - economic_classification_2_name: Goods and services
      total_budget: 1806000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 48000
  programme_name: Agricultural Economics Services
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 77416000
    - economic_classification_2_name: Goods and services
      total_budget: 35683000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Buildings and other fixed structures
      total_budget: 40000000
    - economic_classification_2_name: Machinery and equipment
      total_budget: 2552000
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Departmental agencies and accounts
      total_budget: 101830000
    - economic_classification_2_name: Households
      total_budget: 168000
  programme_name: Environmental Services
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 133968000
    - economic_classification_2_name: Goods and services
      total_budget: 40938000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 386000
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Households
      total_budget: 216483000
  programme_name: Farmer Support and Development
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 48150000
    - economic_classification_2_name: Goods and services
      total_budget: 10407000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Biological assets
      total_budget: 850000
    - economic_classification_2_name: Machinery and equipment
      total_budget: 570000
  programme_name: Research and Technology  Development Services
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 18308000
    - economic_classification_2_name: Goods and services
      total_budget: 10258000
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Households
      total_budget: 25988000
  programme_name: Rural Development Coordination
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 59512000
    - economic_classification_2_name: Goods and services
      total_budget: 34116000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 845000
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Households
      total_budget: 6163000
  programme_name: Structured Agricultural Education and  Training
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 32836000
    - economic_classification_2_name: Goods and services
      total_budget: 8301000
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Households
      total_budget: 7621000
  programme_name: Sustainable Resource Management
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 87942000
    - economic_classification_2_name: Goods and services
      total_budget: 23269000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 5187000
  programme_name: Veterinary Services
expenditure_over_time:
  base_financial_year: 2017-18
  nominal:
  - amount: 923443000
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 1072012000
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 1169275000
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 1200692000
    financial_year: 2015-16
    phase: Adjusted appropriation
  - amount: 1284840000
    financial_year: 2016-17
    phase: Main appropriation
  - amount: 1383759000
    financial_year: 2017-18
    phase: Medium Term Estimates
  - amount: 1468589000
    financial_year: 2018-19
    phase: Medium Term Estimates
  real:
  - amount: 1210190836
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 1327663352
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 1370989694
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 1338659121
    financial_year: 2015-16
    phase: Adjusted appropriation
  - amount: 1347640404
    financial_year: 2016-17
    phase: Main appropriation
  - amount: 1383759000
    financial_year: 2017-18
    phase: Medium Term Estimates
  - amount: 1392138141
    financial_year: 2018-19
    phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2016-17
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2018-19
  is_selected: false
government:
  name: North West
  slug: north-west
government_functions: []
intro: "## Vision\n\nVibrant and prosperous society in harmony with our natural resources.\r\
  \n\r\n\r\n\n\n## Mission\n\nWorking together with our partners to provide sustainable\
  \ agricultural, environmental management and comprehensive integrated rural development.\r\
  \n\r\n\r\n\n\n## Core functions of the department\n\n* The Department focus primarily\
  \ on the following mandated core functions:\r\n\r\n* Rolling out the Comprehensive\
  \ Rural Development Programme\r\n\r\n* Creating decent employment through Inclusive\
  \ Economic Growth\r\n\r\n\r\n* Protecting and Enhancing Environmental Assets and\
  \ Natural Resources"
is_vote_primary: true
name: Rural Environment and Agricultural Development
programmes:
- name: Administration
  total_budget: 243163000
- name: Sustainable Resource Management
  total_budget: 48758000
- name: Farmer Support and Development
  total_budget: 391775000
- name: Veterinary Services
  total_budget: 116398000
- name: Research and Technology  Development Services
  total_budget: 59977000
- name: Agricultural Economics Services
  total_budget: 11930000
- name: Structured Agricultural Education and  Training
  total_budget: 100636000
- name: Rural Development Coordination
  total_budget: 54554000
- name: Environmental Services
  total_budget: 257649000
selected_financial_year: 2016-17
selected_tab: departments
slug: rural-environment-and-agricultural-development
sphere:
  name: Provincial
  slug: provincial
title: Rural Environment and Agricultural Development budget 2016-17  - vulekamali
treasury_datasets:
  'EPRE for Vote 13 : Rural Environment and Agricultural Development':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/ddc0398f-4eb6-4789-86f5-cdfd93e68fca/resource/18ca03ae-bde4-4788-8b21-e140269d29f2/download/nw-rural-env.-and-agricultural-dev..xlsm
    - format: PDF
      url: https://data.vulekamali.gov.za/dataset/ddc0398f-4eb6-4789-86f5-cdfd93e68fca/resource/4d2130ec-870d-4d9b-9aba-eea21cdaf990/download/nw-vote-13-rural-environment-and-agricultural-development.pdf
vote_number: 13
vote_primary:
  name: Rural Environment and Agricultural Development
  slug: rural-environment-and-agricultural-development
  url_path: /2016-17/provincial/north-west/departments/rural-environment-and-agricultural-development
