financial_years:
- closest_match:
    is_exact_match: true
    name: Rural, Environment and Agricultural Development
    organisational_unit: department
    slug: rural-environment-and-agricultural-development
    url_path: /2015-16/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Rural Environment and Agricultural Development
    organisational_unit: department
    slug: rural-environment-and-agricultural-development
    url_path: /2016-17/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2016-17
  is_selected: true
- closest_match:
    is_exact_match: true
    name: Rural Environment and Agricultural Development
    organisational_unit: department
    slug: rural-environment-and-agricultural-development
    url_path: /2017-18/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2017-18
  is_selected: false
government:
  name: North West
  slug: north-west
intro: "## Vision\n\nVibrant and prosperous society in harmony with our natural resources.\r\
  \n\r\n\r\n\n\n## Mission\n\nWorking together with our partners to provide sustainable\
  \ agricultural, environmental management and comprehensive integrated rural development.\r\
  \n\r\n\r\n\n\n## Core functions of the department\n\n* The Department focus primarily\
  \ on the following mandated core functions:\r\n\r\n* Rolling out the Comprehensive\
  \ Rural Development Programme\r\n\r\n* Creating decent employment through Inclusive\
  \ Economic Growth\r\n\r\n\r\n* Protecting and Enhancing Environmental Assets and\
  \ Natural Resources"
name: Rural Environment and Agricultural Development
programmes:
- name: Administration
- name: Sustainable Resource Management
- name: Farmer Support and Development
- name: Veterinary Services
- name: Research and Technology  Development Services
- name: Agricultural Economics Services
- name: Structured Agricultural Education and  Training
- name: Rural Development Coordination
- name: Environmental Services
resources:
  'EPRE for Vote 13 : Rural Environment and Agricultural Development':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://treasurydata.openup.org.za/dataset/ddc0398f-4eb6-4789-86f5-cdfd93e68fca/resource/18ca03ae-bde4-4788-8b21-e140269d29f2/download/nw-rural-env.-and-agricultural-dev..xlsm
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2016/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/NW/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/NW
        - Vote 13 - Rural Environment and Agricultural Development.pdf
slug: rural-environment-and-agricultural-development
vote_number: 13
