#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

adjusted_budget_summary: null
budget_actual: null
budget_actual_programmes: null
contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
department_adjusted_budget: null
department_budget: null
description: 'Limpopo department: Economic Development, Environmental Affairs and
  Tourism budget data for the 2019-20 financial year from National Treasury in partnership
  with IMALI YETHU.'
economic_classification_by_programme: null
expenditure_over_time: null
financial_years:
- closest_match:
    is_exact_match: false
    url_path: /2016-17/provincial/limpopo
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: false
    url_path: /2017-18/provincial/limpopo
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: false
    url_path: /2018-19/provincial/limpopo
  id: 2018-19
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2019-20/provincial/limpopo/departments/economic-development-environmental-affairs-and-tourism
  id: 2019-20
  is_selected: true
government:
  name: Limpopo
  slug: limpopo
government_functions: []
intro: ''
is_vote_primary: true
name: Economic Development, Environmental Affairs and Tourism
programme_by_economic_classification: null
programmes:
  programme_budgets: []
selected_financial_year: 2019-20
selected_tab: departments
slug: economic-development-environmental-affairs-and-tourism
sphere:
  name: provincial
  slug: provincial
subprogramme_by_programme: null
title: Economic Development, Environmental Affairs and Tourism budget 2019-20  - vulekamali
vote_number: 6
vote_primary:
  name: Economic Development, Environmental Affairs and Tourism
  slug: economic-development-environmental-affairs-and-tourism
  url_path: /2019-20/provincial/limpopo/departments/economic-development-environmental-affairs-and-tourism
website_url: null
