#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

adjusted_budget_summary: null
budget_actual: null
budget_actual_programmes: null
contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
department_adjusted_budget: null
department_budget: null
description: 'Limpopo department: Economic Development, Environmental Affairs and
  Tourism budget data for the 2019-20 financial year from National Treasury in partnership
  with IMALI YETHU.'
economic_classification_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-of-south-africa-2019-20
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2019-20-uploaded-2019-06-05-1615/aggregate/%3Fcut%3Dfinancialyear.financialyear%253A2019%257Cgovernment.government%253A%2522Limpopo%2522%257Cvotenumber.department%253A%2522Economic%2BDevelopment%252C%2BEnvironmental%2BAffairs%2Band%2BTourism%2522%26drilldown%3Dbudgetphase.budgetphase%257Ceconomicclassification1.economicclassification1%257Ceconomicclassification2.economicclassification2%257Ceconomicclassification3.economicclassification3%257Ceconomicclassification4.economicclassification4%257Ceconomicclassification5.economicclassification5%257Cfinancialyear.financialyear%257Cfunctiongroup1.functiongroup1%257Cfunctiongroup2.functiongroup2%257Cgovernment.government%257Cprognumber.prognumber%257Cprognumber.programme%257Csubprognumber.subprognumber%257Csubprognumber.subprogramme%257Cvotenumber.department%257Cvotenumber.votenumber%26pagesize%3D10000
  programmes:
  - items:
    - items:
      - name: Payments for capital assets
        total_budget: 6285000
        type: economic_classification_2
      name: Capital
      type: economic_classification_1
    - items:
      - name: Current payments
        total_budget: 390567000
        type: economic_classification_2
      - name: Transfers and subsidies
        total_budget: 8086000
        type: economic_classification_2
      name: Current
      type: economic_classification_1
    name: Administration
    type: programme
  - items:
    - items:
      - name: Payments for capital assets
        total_budget: 2617000
        type: economic_classification_2
      name: Capital
      type: economic_classification_1
    - items:
      - name: Transfers and subsidies
        total_budget: 658157000
        type: economic_classification_2
      - name: Current payments
        total_budget: 109113000
        type: economic_classification_2
      name: Current
      type: economic_classification_1
    name: Economic Development
    type: programme
  - items:
    - items:
      - name: Payments for capital assets
        total_budget: 47228000
        type: economic_classification_2
      name: Capital
      type: economic_classification_1
    - items:
      - name: Current payments
        total_budget: 366602000
        type: economic_classification_2
      - name: Transfers and subsidies
        total_budget: 4442000
        type: economic_classification_2
      name: Current
      type: economic_classification_1
    name: Environmental Affairs
    type: programme
  - items:
    - items:
      - name: Transfers and subsidies
        total_budget: 99216000
        type: economic_classification_2
      - name: Current payments
        total_budget: 30397000
        type: economic_classification_2
      name: Current
      type: economic_classification_1
    name: Tourism
    type: programme
expenditure_over_time:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-of-south-africa-2019-20
  expenditure:
    base_financial_year: 2018-19
    nominal:
    - amount: 1153443000
      financial_year: 2015-16
      phase: Audited Outcome
    - amount: 1312225000
      financial_year: 2016-17
      phase: Audited Outcome
    - amount: 1681908000
      financial_year: 2017-18
      phase: Audited Outcome
    - amount: 1665374000
      financial_year: 2018-19
      phase: Adjusted appropriation
    - amount: 1722710000
      financial_year: 2019-20
      phase: Main appropriation
    - amount: 1805669000
      financial_year: 2020-21
      phase: Medium Term Estimates
    - amount: 1903175000
      financial_year: 2021-22
      phase: Medium Term Estimates
    real:
    - amount: 1346919969
      financial_year: 2015-16
      phase: Audited Outcome
    - amount: 1441585984
      financial_year: 2016-17
      phase: Audited Outcome
    - amount: 1764526551
      financial_year: 2017-18
      phase: Audited Outcome
    - amount: 1665374000
      financial_year: 2018-19
      phase: Adjusted appropriation
    - amount: 1638209288
      financial_year: 2019-20
      phase: Main appropriation
    - amount: 1627911076
      financial_year: 2020-21
      phase: Medium Term Estimates
    - amount: 1627470757
      financial_year: 2021-22
      phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: false
    url_path: /2016-17/provincial/limpopo
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: false
    url_path: /2017-18/provincial/limpopo
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: false
    url_path: /2018-19/provincial/limpopo
  id: 2018-19
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2019-20/provincial/limpopo/departments/economic-development-environmental-affairs-and-tourism
  id: 2019-20
  is_selected: true
government:
  name: Limpopo
  slug: limpopo
government_functions: []
intro: ''
is_vote_primary: true
name: Economic Development, Environmental Affairs and Tourism
programme_by_economic_classification:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-of-south-africa-2019-20
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2019-20-uploaded-2019-06-05-1615/aggregate/%3Fcut%3Dfinancialyear.financialyear%253A2019%257Cgovernment.government%253A%2522Limpopo%2522%257Cvotenumber.department%253A%2522Economic%2BDevelopment%252C%2BEnvironmental%2BAffairs%2Band%2BTourism%2522%26drilldown%3Dbudgetphase.budgetphase%257Ceconomicclassification1.economicclassification1%257Ceconomicclassification2.economicclassification2%257Ceconomicclassification3.economicclassification3%257Ceconomicclassification4.economicclassification4%257Ceconomicclassification5.economicclassification5%257Cfinancialyear.financialyear%257Cfunctiongroup1.functiongroup1%257Cfunctiongroup2.functiongroup2%257Cgovernment.government%257Cprognumber.prognumber%257Cprognumber.programme%257Csubprognumber.subprognumber%257Csubprognumber.subprogramme%257Cvotenumber.department%257Cvotenumber.votenumber%26pagesize%3D10000
  econ_classes:
  - items:
    - name: Environmental Affairs
      total_budget: 47228000
      type: programme
    - name: Administration
      total_budget: 6285000
      type: programme
    - name: Economic Development
      total_budget: 2617000
      type: programme
    name: Capital - Payments for capital assets
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 390567000
      type: programme
    - name: Environmental Affairs
      total_budget: 366602000
      type: programme
    - name: Economic Development
      total_budget: 109113000
      type: programme
    - name: Tourism
      total_budget: 30397000
      type: programme
    name: Current - Current payments
    type: economic_classification_1_and_2
  - items:
    - name: Economic Development
      total_budget: 658157000
      type: programme
    - name: Tourism
      total_budget: 99216000
      type: programme
    - name: Administration
      total_budget: 8086000
      type: programme
    - name: Environmental Affairs
      total_budget: 4442000
      type: programme
    name: Current - Transfers and subsidies
    type: economic_classification_1_and_2
programmes:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-of-south-africa-2019-20
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2019-20-uploaded-2019-06-05-1615/aggregate/%3Fcut%3Dfinancialyear.financialyear%253A2019%257Cgovernment.government%253A%2522Limpopo%2522%257Cvotenumber.department%253A%2522Economic%2BDevelopment%252C%2BEnvironmental%2BAffairs%2Band%2BTourism%2522%26drilldown%3Dbudgetphase.budgetphase%257Ceconomicclassification1.economicclassification1%257Ceconomicclassification2.economicclassification2%257Ceconomicclassification3.economicclassification3%257Ceconomicclassification4.economicclassification4%257Ceconomicclassification5.economicclassification5%257Cfinancialyear.financialyear%257Cfunctiongroup1.functiongroup1%257Cfunctiongroup2.functiongroup2%257Cgovernment.government%257Cprognumber.prognumber%257Cprognumber.programme%257Csubprognumber.subprognumber%257Csubprognumber.subprogramme%257Cvotenumber.department%257Cvotenumber.votenumber%26pagesize%3D10000
  programme_budgets:
  - name: Administration
    total_budget: 404938000
  - name: Economic Development
    total_budget: 769887000
  - name: Environmental Affairs
    total_budget: 418272000
  - name: Tourism
    total_budget: 129613000
selected_financial_year: 2019-20
selected_tab: departments
slug: economic-development-environmental-affairs-and-tourism
sphere:
  name: Provincial
  slug: provincial
subprogramme_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-of-south-africa-2019-20
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2019-20-uploaded-2019-06-05-1615/aggregate/%3Fcut%3Dfinancialyear.financialyear%253A2019%257Cgovernment.government%253A%2522Limpopo%2522%257Cvotenumber.department%253A%2522Economic%2BDevelopment%252C%2BEnvironmental%2BAffairs%2Band%2BTourism%2522%26drilldown%3Dbudgetphase.budgetphase%257Ceconomicclassification1.economicclassification1%257Ceconomicclassification2.economicclassification2%257Ceconomicclassification3.economicclassification3%257Ceconomicclassification4.economicclassification4%257Ceconomicclassification5.economicclassification5%257Cfinancialyear.financialyear%257Cfunctiongroup1.functiongroup1%257Cfunctiongroup2.functiongroup2%257Cgovernment.government%257Cprognumber.prognumber%257Cprognumber.programme%257Csubprognumber.subprognumber%257Csubprognumber.subprogramme%257Cvotenumber.department%257Cvotenumber.votenumber%26pagesize%3D10000
  programmes:
  - items:
    - name: Corporate Services
      total_budget: 304051000
      type: subprogramme
    - name: Financial Management
      total_budget: 82862000
      type: subprogramme
    - name: Office Of The Mec
      total_budget: 9358000
      type: subprogramme
    - name: Office Of The Hod
      total_budget: 8667000
      type: subprogramme
    name: Administration
    type: programme
  - items:
    - name: Intergrated Economic Development Services
      total_budget: 611892000
      type: subprogramme
    - name: Business Regulation And Governance
      total_budget: 121800000
      type: subprogramme
    - name: Trade And Sector Development
      total_budget: 22255000
      type: subprogramme
    - name: Economic Planning And Research
      total_budget: 13940000
      type: subprogramme
    name: Economic Development
    type: programme
  - items:
    - name: Biodiversity And Natural Resources Management
      total_budget: 212181000
      type: subprogramme
    - name: Environmental Trade And Protection
      total_budget: 123357000
      type: subprogramme
    - name: Limpopo Wildlife Resorts
      total_budget: 55882000
      type: subprogramme
    - name: Environmental Empowerment Services
      total_budget: 26852000
      type: subprogramme
    name: Environmental Affairs
    type: programme
  - items:
    - name: Tourism Planning And Development
      total_budget: 129613000
      type: subprogramme
    name: Tourism
    type: programme
title: Economic Development, Environmental Affairs and Tourism budget 2019-20  - vulekamali
vote_number: 6
vote_primary:
  name: Economic Development, Environmental Affairs and Tourism
  slug: economic-development-environmental-affairs-and-tourism
  url_path: /2019-20/provincial/limpopo/departments/economic-development-environmental-affairs-and-tourism
website_url: null
