#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
description: 'Mpumalanga department: Agriculture, Rural Development, Land And Environmental
  Affairs budget data for the 2015-16 financial year from National Treasury in partnership
  with IMALI YETHU.'
expenditure_over_time:
  base_financial_year: 2017-18
  nominal:
  - amount: 1031668000
    financial_year: 2011-12
    phase: Audited Outcome
  - amount: 1028958000
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 1007100000
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 1055418000
    financial_year: 2014-15
    phase: Adjusted appropriation
  - amount: 1018624000
    financial_year: 2015-16
    phase: Main appropriation
  - amount: 1073224000
    financial_year: 2016-17
    phase: Medium Term Estimates
  - amount: 1206012000
    financial_year: 2017-18
    phase: Medium Term Estimates
  real:
  - amount: 1426951433
    financial_year: 2011-12
    phase: Audited Outcome
  - amount: 1348470390
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 1247271263
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 1237490925
    financial_year: 2014-15
    phase: Adjusted appropriation
  - amount: 1135670354
    financial_year: 2015-16
    phase: Main appropriation
  - amount: 1125681038
    financial_year: 2016-17
    phase: Medium Term Estimates
  - amount: 1206012000
    financial_year: 2017-18
    phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
  id: 2015-16
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
  id: 2018-19
  is_selected: false
government:
  name: Mpumalanga
  slug: mpumalanga
government_functions: []
intro: "## Vision\r\n\r\nVibrant, equitable, integrated and sustainable urban and\
  \ rural communities with a world class, united and prosperous agricultural, forestry\
  \ and fisheries sector with food security for all in a protected and enhanced environment.\r\
  \n\r\n\r\n\r\n## Mission\r\n\r\nTo lead and facilitate integrated, comprehensive,\
  \ sustainable development and social cohesion by participating and partnering with\
  \ all sectors of society, through agriculture, rural development, land and environment"
is_vote_primary: true
name: Agriculture, Rural Development, Land And Environmental Affairs
programmes:
- name: Administration
  total_budget: 137810000
- name: Sustainable Resource Management
  total_budget: 65495000
- name: Farmer Support and Development
  total_budget: 483630000
- name: Veterinary Services
  total_budget: 116441000
- name: Research and Technology Development Services
  total_budget: 56590000
- name: Agricultural Economics Services
  total_budget: 10727000
- name: Structured Agricultural Education and Training
  total_budget: 38769000
- name: Rural Development Coordination
  total_budget: 23479000
- name: Environmental Affairs
  total_budget: 85683000
selected_financial_year: 2015-16
selected_tab: departments
slug: agriculture-rural-development-land-and-environmental-affairs
sphere:
  name: Provincial
  slug: provincial
title: Agriculture, Rural Development, Land And Environmental Affairs budget 2015-16  -
  vulekamali
treasury_datasets:
  'EPRE for Vote 05 : Agriculture, Rural Development, Land And Environmental Affairs':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSX
      url: https://data.vulekamali.gov.za/dataset/86228ab2-8341-4509-a0c6-d5e9a4b8f14a/resource/a043951e-af6b-42f0-8504-43f8ecbecd04/download/mpu-agriculture-.xlsx
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2015/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/MPU/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/MPU
        - Vote 05 - Agriculture, Rural deve, Land and Environ.pdf
vote_number: 5
vote_primary:
  name: Agriculture, Rural Development, Land And Environmental Affairs
  slug: agriculture-rural-development-land-and-environmental-affairs
  url_path: /2015-16/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
