#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
description: 'Mpumalanga department: Agriculture, Rural Development, Land And Environmental
  Affairs budget data for the 2015-16 financial year from National Treasury in partnership
  with IMALI YETHU.'
economic_classification_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2015-16
  programmes:
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 88086000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 40537000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 3551000
        type: economic_classification_2
      - name: Buildings and other fixed structures
        total_budget: 500000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Households
        total_budget: 3678000
        type: economic_classification_2
      - name: Departmental agencies and accounts
        total_budget: 1458000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Administration
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 7830000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 2714000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 183000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    name: Agricultural Economics Services
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 66471000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 17943000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Buildings and other fixed structures
        total_budget: 1000000
        type: economic_classification_2
      - name: Machinery and equipment
        total_budget: 269000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    name: Environmental Affairs
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 170855000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 126597000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 26533000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Households
        total_budget: 159645000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Farmer Support and Development
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 36558000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 11693000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Buildings and other fixed structures
        total_budget: 8339000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    name: Research and Technology Development Services
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 16531000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 6730000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 218000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    name: Rural Development Coordination
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 26029000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 7691000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Buildings and other fixed structures
        total_budget: 5049000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    name: Structured Agricultural Education and Training
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 43016000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 5571000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Households
        total_budget: 16908000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Sustainable Resource Management
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 96189000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 15526000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Buildings and other fixed structures
        total_budget: 4726000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    name: Veterinary Services
    type: programme
expenditure_over_time:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2015-16
  expenditure:
    base_financial_year: 2017-18
    nominal:
    - amount: 1031668000
      financial_year: 2011-12
      phase: Audited Outcome
    - amount: 1028958000
      financial_year: 2012-13
      phase: Audited Outcome
    - amount: 1007100000
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 1055418000
      financial_year: 2014-15
      phase: Adjusted appropriation
    - amount: 1018624000
      financial_year: 2015-16
      phase: Main appropriation
    - amount: 1073224000
      financial_year: 2016-17
      phase: Medium Term Estimates
    - amount: 1206012000
      financial_year: 2017-18
      phase: Medium Term Estimates
    real:
    - amount: 1426951433
      financial_year: 2011-12
      phase: Audited Outcome
    - amount: 1348470390
      financial_year: 2012-13
      phase: Audited Outcome
    - amount: 1247271263
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 1237490925
      financial_year: 2014-15
      phase: Adjusted appropriation
    - amount: 1135670354
      financial_year: 2015-16
      phase: Main appropriation
    - amount: 1125681038
      financial_year: 2016-17
      phase: Medium Term Estimates
    - amount: 1206012000
      financial_year: 2017-18
      phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
  id: 2015-16
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
  id: 2018-19
  is_selected: false
government:
  name: Mpumalanga
  slug: mpumalanga
government_functions: []
intro: "## Vision\r\n\r\nVibrant, equitable, integrated and sustainable urban and\
  \ rural communities with a world class, united and prosperous agricultural, forestry\
  \ and fisheries sector with food security for all in a protected and enhanced environment.\r\
  \n\r\n\r\n\r\n## Mission\r\n\r\nTo lead and facilitate integrated, comprehensive,\
  \ sustainable development and social cohesion by participating and partnering with\
  \ all sectors of society, through agriculture, rural development, land and environment"
is_vote_primary: true
name: Agriculture, Rural Development, Land And Environmental Affairs
programme_by_economic_classification:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2015-16
  econ_classes:
  - items:
    - name: Farmer Support and Development
      total_budget: 170855000
      type: programme
    - name: Veterinary Services
      total_budget: 96189000
      type: programme
    - name: Administration
      total_budget: 88086000
      type: programme
    - name: Environmental Affairs
      total_budget: 66471000
      type: programme
    - name: Sustainable Resource Management
      total_budget: 43016000
      type: programme
    - name: Research and Technology Development Services
      total_budget: 36558000
      type: programme
    - name: Structured Agricultural Education and Training
      total_budget: 26029000
      type: programme
    - name: Rural Development Coordination
      total_budget: 16531000
      type: programme
    - name: Agricultural Economics Services
      total_budget: 7830000
      type: programme
    name: Current payments - Compensation of employees
    type: economic_classification_1_and_2
  - items:
    - name: Farmer Support and Development
      total_budget: 126597000
      type: programme
    - name: Administration
      total_budget: 40537000
      type: programme
    - name: Environmental Affairs
      total_budget: 17943000
      type: programme
    - name: Veterinary Services
      total_budget: 15526000
      type: programme
    - name: Research and Technology Development Services
      total_budget: 11693000
      type: programme
    - name: Structured Agricultural Education and Training
      total_budget: 7691000
      type: programme
    - name: Rural Development Coordination
      total_budget: 6730000
      type: programme
    - name: Sustainable Resource Management
      total_budget: 5571000
      type: programme
    - name: Agricultural Economics Services
      total_budget: 2714000
      type: programme
    name: Current payments - Goods and services
    type: economic_classification_1_and_2
  - items:
    - name: Research and Technology Development Services
      total_budget: 8339000
      type: programme
    - name: Structured Agricultural Education and Training
      total_budget: 5049000
      type: programme
    - name: Veterinary Services
      total_budget: 4726000
      type: programme
    - name: Environmental Affairs
      total_budget: 1000000
      type: programme
    - name: Administration
      total_budget: 500000
      type: programme
    name: Payments for capital assets - Buildings and other fixed structures
    type: economic_classification_1_and_2
  - items:
    - name: Farmer Support and Development
      total_budget: 26533000
      type: programme
    - name: Administration
      total_budget: 3551000
      type: programme
    - name: Environmental Affairs
      total_budget: 269000
      type: programme
    - name: Rural Development Coordination
      total_budget: 218000
      type: programme
    - name: Agricultural Economics Services
      total_budget: 183000
      type: programme
    name: Payments for capital assets - Machinery and equipment
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 1458000
      type: programme
    name: Transfers and subsidies - Departmental agencies and accounts
    type: economic_classification_1_and_2
  - items:
    - name: Farmer Support and Development
      total_budget: 159645000
      type: programme
    - name: Sustainable Resource Management
      total_budget: 16908000
      type: programme
    - name: Administration
      total_budget: 3678000
      type: programme
    name: Transfers and subsidies - Households
    type: economic_classification_1_and_2
programmes:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2015-16
  programme_budgets:
  - name: Administration
    total_budget: 137810000
  - name: Sustainable Resource Management
    total_budget: 65495000
  - name: Farmer Support and Development
    total_budget: 483630000
  - name: Veterinary Services
    total_budget: 116441000
  - name: Research and Technology Development Services
    total_budget: 56590000
  - name: Agricultural Economics Services
    total_budget: 10727000
  - name: Structured Agricultural Education and Training
    total_budget: 38769000
  - name: Rural Development Coordination
    total_budget: 23479000
  - name: Environmental Affairs
    total_budget: 85683000
selected_financial_year: 2015-16
selected_tab: departments
slug: agriculture-rural-development-land-and-environmental-affairs
sphere:
  name: Provincial
  slug: provincial
title: Agriculture, Rural Development, Land And Environmental Affairs budget 2015-16  -
  vulekamali
treasury_datasets:
  'EPRE for Vote 05 : Agriculture, Rural Development, Land And Environmental Affairs':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSX
      url: https://data.vulekamali.gov.za/dataset/86228ab2-8341-4509-a0c6-d5e9a4b8f14a/resource/a043951e-af6b-42f0-8504-43f8ecbecd04/download/mpu-agriculture-.xlsx
    - format: PDF
      url: https://data.vulekamali.gov.za/dataset/86228ab2-8341-4509-a0c6-d5e9a4b8f14a/resource/b5604abd-6a14-4030-94cd-31d9ef6dd723/download/mpu-vote-05-agriculture-rural-deve-land-and-environ.pdf
vote_number: 5
vote_primary:
  name: Agriculture, Rural Development, Land And Environmental Affairs
  slug: agriculture-rural-development-land-and-environmental-affairs
  url_path: /2015-16/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
