#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: The transparency of public funding of Basic Education in South Africa
  url_path: /datasets/contributed/the-transparency-of-public-funding-of-basic-education-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
- contributor: Centre for Child Law
  name: 'Mud to bricks: A review of school infrastructure spending and delivery'
  url_path: /datasets/contributed/mud-to-bricks-a-review-of-school-infrastructure-spending-and-delivery
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Eastern Cape Department of Health 2014/15'
  url_path: /datasets/contributed/budget-brief-eastern-cape-department-of-health-2014-15
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Eastern Cape Department of Education 2016/17'
  url_path: /datasets/contributed/budget-brief-eastern-cape-department-of-education-2016-17
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Eastern Cape Department of Human Settlements 2014/15'
  url_path: /datasets/contributed/budget-brief-eastern-cape-department-of-human-settlements-2014-15
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Department of Human Settlements, 2016/17 and 2017/18'
  url_path: /datasets/contributed/budget-brief-department-of-human-settlements
description: 'Mpumalanga department: Agriculture, Rural Development, Land And Environmental
  Affairs budget data for the 2015-16 financial year from National Treasury in partnership
  with IMALI YETHU.'
expenditure_over_time:
  base_financial_year: 2017-18
  nominal:
  - amount: 1031668000
    financial_year: 2011-12
    phase: Audited Outcome
  - amount: 1028958000
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 1007100000
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 1055418000
    financial_year: 2014-15
    phase: Adjusted appropriation
  - amount: 1018624000
    financial_year: 2015-16
    phase: Main appropriation
  - amount: 1073224000
    financial_year: 2016-17
    phase: Medium Term Estimates
  - amount: 1206012000
    financial_year: 2017-18
    phase: Medium Term Estimates
  real:
  - amount: 1426951433
    financial_year: 2011-12
    phase: Audited Outcome
  - amount: 1348470390
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 1247271263
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 1237490925
    financial_year: 2014-15
    phase: Adjusted appropriation
  - amount: 1135670354
    financial_year: 2015-16
    phase: Main appropriation
  - amount: 1125681038
    financial_year: 2016-17
    phase: Medium Term Estimates
  - amount: 1206012000
    financial_year: 2017-18
    phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
  id: 2015-16
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
  id: 2018-19
  is_selected: false
government:
  name: Mpumalanga
  slug: mpumalanga
government_functions: []
intro: "## Vision\r\n\r\nVibrant, equitable, integrated and sustainable urban and\
  \ rural communities with a world class, united and prosperous agricultural, forestry\
  \ and fisheries sector with food security for all in a protected and enhanced environment.\r\
  \n\r\n\r\n\r\n## Mission\r\n\r\nTo lead and facilitate integrated, comprehensive,\
  \ sustainable development and social cohesion by participating and partnering with\
  \ all sectors of society, through agriculture, rural development, land and environment"
is_vote_primary: true
name: Agriculture, Rural Development, Land And Environmental Affairs
programmes:
- name: Administration
  total_budget: 137810000
- name: Sustainable Resource Management
  total_budget: 65495000
- name: Farmer Support and Development
  total_budget: 483630000
- name: Veterinary Services
  total_budget: 116441000
- name: Research and Technology Development Services
  total_budget: 56590000
- name: Agricultural Economics Services
  total_budget: 10727000
- name: Structured Agricultural Education and Training
  total_budget: 38769000
- name: Rural Development Coordination
  total_budget: 23479000
- name: Environmental Affairs
  total_budget: 85683000
selected_financial_year: 2015-16
selected_tab: departments
slug: agriculture-rural-development-land-and-environmental-affairs
sphere:
  name: Provincial
  slug: provincial
title: Agriculture, Rural Development, Land And Environmental Affairs budget 2015-16  -
  vulekamali
treasury_datasets: {}
vote_number: 5
vote_primary:
  name: Agriculture, Rural Development, Land And Environmental Affairs
  slug: agriculture-rural-development-land-and-environmental-affairs
  url_path: /2015-16/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
