financial_years:
- closest_match:
    is_exact_match: true
    name: Economic Development, Environment and Tourism
    organisational_unit: department
    slug: economic-development-environment-and-tourism
    url_path: /2015-16/provincial/mpumalanga/departments/economic-development-environment-and-tourism
  id: 2015-16
  is_selected: true
- closest_match:
    is_exact_match: true
    name: Economic Development, Environment and Tourism
    organisational_unit: department
    slug: economic-development-environment-and-tourism
    url_path: /2016-17/provincial/mpumalanga/departments/economic-development-environment-and-tourism
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Economic Development, Environment and Tourism
    organisational_unit: department
    slug: economic-development-environment-and-tourism
    url_path: /2017-18/provincial/mpumalanga/departments/economic-development-environment-and-tourism
  id: 2017-18
  is_selected: false
government:
  name: Mpumalanga
  slug: mpumalanga
name: Economic Development, Environment and Tourism
narrative: {}
resources:
  'EPRE for Vote 06 : Economic Development, Environment and Tourism':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSX
      url: https://treasurydata.openup.org.za/dataset/6a84f5ec-cb0d-40b8-9e57-59b55d965c2b/resource/268a8634-32c7-4ffb-9a13-669e7d083cc7/download/mpu-eco-dev-environ-and-tourism.xlsx
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2015/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/MPU/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/MPU
        - Vote 06 - Economic Development and Tourism.pdf
slug: economic-development-environment-and-tourism
vote_number: 6
