financial_years:
- closest_match:
    is_exact_match: true
    name: Economic Development, Environment and Tourism
    organisational_unit: department
    slug: economic-development-environment-and-tourism
    url_path: /2015-16/provincial/mpumalanga/departments/economic-development-environment-and-tourism
  id: 2015-16
  is_selected: true
- closest_match:
    is_exact_match: true
    name: Economic Development, Environment and Tourism
    organisational_unit: department
    slug: economic-development-environment-and-tourism
    url_path: /2016-17/provincial/mpumalanga/departments/economic-development-environment-and-tourism
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Economic Development, Environment and Tourism
    organisational_unit: department
    slug: economic-development-environment-and-tourism
    url_path: /2017-18/provincial/mpumalanga/departments/economic-development-environment-and-tourism
  id: 2017-18
  is_selected: false
government:
  name: Mpumalanga
  slug: mpumalanga
name: Economic Development, Environment and Tourism
narratives:
- content: "An Inclusive, Globally Competitive Economy\r\n\r\n"
  name: Vision
- content: "Drive economic growth that creates decent employment and promote sustainable\
    \ development through partnerships.\r\n\r\nFurthermore, the focus of the Department\
    \ was to conduct research in order to assist in identifying gaps in the economy\
    \ and suggest possible intervention. To this end, the outcome of the research\
    \ including suggestions will be communicated to all municipalities for implementation.\r\
    \n\r\nFollowing the 2014 general elections, the fifth Provincial Administration\
    \ prioritised five priority sectors with the potential to create the much needed\
    \ jobs and could thus assist in reducing unemployment, poverty and inequality\
    \ in the Province. These five priority sectors are: Agriculture, ICT, Tourism,\
    \ Manufacturing and Mining. These sectors are the basis of the support the Department\
    \ is providing to small businesses and co-operatives, and this has resulted in\
    \ the following priorities aimed strengthening the said support:\r\n\r\n* Development\
    \ of the Provincial Tourism Act\r\n\r\n* Development of the Township Strategy\r\
    \n\r\n* SMME Development Strategy\r\n\r\n* Development of the Informal Sector\
    \ Strategy\r\n\r\n* Support infrastructure projects aimed at supporting co-operatives\
    \ in these sectors\r\n\r\n* Conduct research and produce a plan for the green\
    \ economy\r\n\r\n* Develop the Tourism Act\r\n\r\nIn terms of role delineation\
    \ between the Department and its Public Entities, the Executive Council\r\nLekgotla\
    \ has adopted the Organisational Re-design Report which paves the way for the\
    \ new organisational structure of the Department and remodeling of the Public\
    \ Entities, particularly MEGA and MTPA\r\n\r\n"
  name: Mission
resources:
  'EPRE for Vote 06 : Economic Development, Environment and Tourism':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSX
      url: https://treasurydata.openup.org.za/dataset/6a84f5ec-cb0d-40b8-9e57-59b55d965c2b/resource/268a8634-32c7-4ffb-9a13-669e7d083cc7/download/mpu-eco-dev-environ-and-tourism.xlsx
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2015/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/MPU/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/MPU
        - Vote 06 - Economic Development and Tourism.pdf
slug: economic-development-environment-and-tourism
vote_number: 6
