financial_years:
- closest_match:
    is_exact_match: true
    name: Agriculture, Environmental Affairs and Rural Development
    organisational_unit: department
    slug: agriculture-environmental-affairs-and-rural-development
    url_path: /2015-16/provincial/kwazulu-natal/departments/agriculture-environmental-affairs-and-rural-development
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Agriculture, Environmental Affairs and Rural Development
    organisational_unit: department
    slug: agriculture-environmental-affairs-and-rural-development
    url_path: /2016-17/provincial/kwazulu-natal/departments/agriculture-environmental-affairs-and-rural-development
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Agriculture, Environmental Affairs and Rural Development
    organisational_unit: department
    slug: agriculture-environmental-affairs-and-rural-development
    url_path: /2017-18/provincial/kwazulu-natal/departments/agriculture-environmental-affairs-and-rural-development
  id: 2017-18
  is_selected: true
government:
  name: KwaZulu-Natal
  slug: kwazulu-natal
name: Agriculture, Environmental Affairs and Rural Development
narrative: {}
resources:
  'EPRE for Vote 03 : Agriculture, Environmental Affairs and Rural Development':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://treasurydata.openup.org.za/dataset/15f4fb23-dcb1-4892-bc20-a6164671ee7a/resource/482d09ee-6f6d-47fc-9473-da6e7d90dccc/download/kzn-agriculture-and-rural-dev.xlsm
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2017/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/KZN/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/KZN
        - Vote 03 - Agriculture.pdf
slug: agriculture-environmental-affairs-and-rural-development
vote_number: 3
