#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
description: 'KwaZulu-Natal department: Economic Development, Tourism and Environmental
  Affairs budget data for the 2017-18 financial year from National Treasury in partnership
  with IMALI YETHU.'
economic_classification_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2017-18
  programmes:
  - items:
    - items:
      - name: Goods and services
        total_budget: 144493000
        type: economic_classification_2
      - name: Compensation of employees
        total_budget: 97461000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 1081000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Households
        total_budget: 549000
        type: economic_classification_2
      - name: Provinces and municipalities
        total_budget: 62000
        type: economic_classification_2
      - name: Departmental agencies and accounts
        total_budget: 9000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Administration
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 22646000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 14026000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Departmental agencies and accounts
        total_budget: 75990000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Business Regulation and Governance
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 16877000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 11850000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Departmental agencies and accounts
        total_budget: 5000000
        type: economic_classification_2
      - name: Higher education institutions
        total_budget: 4980000
        type: economic_classification_2
      - name: Public corporations and private enterprises
        total_budget: 800000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Economic Planning
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 123726000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 116845000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 1243000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Departmental agencies and accounts
        total_budget: 707720000
        type: economic_classification_2
      - name: Non-profit institutions
        total_budget: 6880000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Environmental Affairs
    type: programme
  - items:
    - items:
      - name: Goods and services
        total_budget: 185214000
        type: economic_classification_2
      - name: Compensation of employees
        total_budget: 65304000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 450000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Non-profit institutions
        total_budget: 54400000
        type: economic_classification_2
      - name: Public corporations and private enterprises
        total_budget: 45074000
        type: economic_classification_2
      - name: Higher education institutions
        total_budget: 6000000
        type: economic_classification_2
      - name: Households
        total_budget: 1611000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Integrated Economic Development Services
    type: programme
  - items:
    - items:
      - name: Goods and services
        total_budget: 28038000
        type: economic_classification_2
      - name: Compensation of employees
        total_budget: 19382000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 70000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Departmental agencies and accounts
        total_budget: 183059000
        type: economic_classification_2
      - name: Provinces and municipalities
        total_budget: 500000
        type: economic_classification_2
      - name: Public corporations and private enterprises
        total_budget: 500000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Tourism
    type: programme
  - items:
    - items:
      - name: Goods and services
        total_budget: 71074000
        type: economic_classification_2
      - name: Compensation of employees
        total_budget: 17969000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Departmental agencies and accounts
        total_budget: 495922000
        type: economic_classification_2
      - name: Public corporations and private enterprises
        total_budget: 137705000
        type: economic_classification_2
      - name: Non-profit institutions
        total_budget: 119393000
        type: economic_classification_2
      - name: Households
        total_budget: 500000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Trade and Sector Development
    type: programme
expenditure_over_time:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2017-18
  expenditure:
    base_financial_year: 2017-18
    nominal:
    - amount: 3311354000
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 2955803000
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 2983585000
      financial_year: 2015-16
      phase: Audited Outcome
    - amount: 2604611000
      financial_year: 2016-17
      phase: Adjusted appropriation
    - amount: 2784403000
      financial_year: 2017-18
      phase: Main appropriation
    - amount: 3005556000
      financial_year: 2018-19
      phase: Medium Term Estimates
    - amount: 3180694000
      financial_year: 2019-20
      phase: Medium Term Estimates
    real:
    - amount: 4101039308
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 3465716321
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 3326417828
      financial_year: 2015-16
      phase: Audited Outcome
    - amount: 2731919165
      financial_year: 2016-17
      phase: Adjusted appropriation
    - amount: 2784403000
      financial_year: 2017-18
      phase: Main appropriation
    - amount: 2849094705
      financial_year: 2018-19
      phase: Medium Term Estimates
    - amount: 2863596801
      financial_year: 2019-20
      phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
  id: 2017-18
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
  id: 2018-19
  is_selected: false
government:
  name: KwaZulu-Natal
  slug: kwazulu-natal
government_functions: []
intro: "## Vision\r\n\r\nThe vision of the Department of Economic Development, Tourism\
  \ and Environmental Affairs (EDTEA) is: Leading the attainment of inclusive and\
  \ sustainable economic growth for job creation\r\n\r\n\r\n\r\n## Mission\r\n\r\n\
  The department\u2019s mission is to: Provide leadership and facilitate integrated\
  \ economic planning, be a catalyst for economic transformation and sustainable development,\
  \ implement strategies that drive economic growth and promote sound environmental\
  \ management, create a conducive environment for trade, investment and tourism and\
  \ monitor and enforce sound business and consumer regulations.\r\n\r\n\r\n\r\n##\
  \ Core functions\r\n\r\nThe department\u2019s core functions are summarised as follows:\r\
  \n\r\n* To drive the economic development strategies of the province.\r\n\r\n* To\
  \ facilitate strategies to enhance the competitiveness of priority sectors of the\
  \ economy, in line with the industrial development strategy.\r\n\r\n* To promote\
  \ the development of small business and social enterprises.\r\n\r\n* To promote\
  \ and facilitate economic empowerment programmes.\r\n\r\n* To manage the Enterprise\
  \ Development and Growth Funds.\r\n\r\n* To provide an effective and efficient consumer\
  \ protection service.\r\n\r\n* To ensure effective and prudent business regulation\
  \ in the province.\r\n\r\n* To provide effective and efficient environmental management.\r\
  \n\r\n* To provide conservation services."
is_vote_primary: true
name: Economic Development, Tourism and Environmental Affairs
programme_by_economic_classification:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2017-18
  econ_classes:
  - items:
    - name: Environmental Affairs
      total_budget: 123726000
      type: programme
    - name: Administration
      total_budget: 97461000
      type: programme
    - name: Integrated Economic Development Services
      total_budget: 65304000
      type: programme
    - name: Business Regulation and Governance
      total_budget: 22646000
      type: programme
    - name: Tourism
      total_budget: 19382000
      type: programme
    - name: Trade and Sector Development
      total_budget: 17969000
      type: programme
    - name: Economic Planning
      total_budget: 16877000
      type: programme
    name: Current payments - Compensation of employees
    type: economic_classification_1_and_2
  - items:
    - name: Integrated Economic Development Services
      total_budget: 185214000
      type: programme
    - name: Administration
      total_budget: 144493000
      type: programme
    - name: Environmental Affairs
      total_budget: 116845000
      type: programme
    - name: Trade and Sector Development
      total_budget: 71074000
      type: programme
    - name: Tourism
      total_budget: 28038000
      type: programme
    - name: Business Regulation and Governance
      total_budget: 14026000
      type: programme
    - name: Economic Planning
      total_budget: 11850000
      type: programme
    name: Current payments - Goods and services
    type: economic_classification_1_and_2
  - items:
    - name: Environmental Affairs
      total_budget: 1243000
      type: programme
    - name: Administration
      total_budget: 1081000
      type: programme
    - name: Integrated Economic Development Services
      total_budget: 450000
      type: programme
    - name: Tourism
      total_budget: 70000
      type: programme
    name: Payments for capital assets - Machinery and equipment
    type: economic_classification_1_and_2
  - items:
    - name: Environmental Affairs
      total_budget: 707720000
      type: programme
    - name: Trade and Sector Development
      total_budget: 495922000
      type: programme
    - name: Tourism
      total_budget: 183059000
      type: programme
    - name: Business Regulation and Governance
      total_budget: 75990000
      type: programme
    - name: Economic Planning
      total_budget: 5000000
      type: programme
    - name: Administration
      total_budget: 9000
      type: programme
    name: Transfers and subsidies - Departmental agencies and accounts
    type: economic_classification_1_and_2
  - items:
    - name: Integrated Economic Development Services
      total_budget: 6000000
      type: programme
    - name: Economic Planning
      total_budget: 4980000
      type: programme
    name: Transfers and subsidies - Higher education institutions
    type: economic_classification_1_and_2
  - items:
    - name: Integrated Economic Development Services
      total_budget: 1611000
      type: programme
    - name: Administration
      total_budget: 549000
      type: programme
    - name: Trade and Sector Development
      total_budget: 500000
      type: programme
    name: Transfers and subsidies - Households
    type: economic_classification_1_and_2
  - items:
    - name: Trade and Sector Development
      total_budget: 119393000
      type: programme
    - name: Integrated Economic Development Services
      total_budget: 54400000
      type: programme
    - name: Environmental Affairs
      total_budget: 6880000
      type: programme
    name: Transfers and subsidies - Non-profit institutions
    type: economic_classification_1_and_2
  - items:
    - name: Tourism
      total_budget: 500000
      type: programme
    - name: Administration
      total_budget: 62000
      type: programme
    name: Transfers and subsidies - Provinces and municipalities
    type: economic_classification_1_and_2
  - items:
    - name: Trade and Sector Development
      total_budget: 137705000
      type: programme
    - name: Integrated Economic Development Services
      total_budget: 45074000
      type: programme
    - name: Economic Planning
      total_budget: 800000
      type: programme
    - name: Tourism
      total_budget: 500000
      type: programme
    name: Transfers and subsidies - Public corporations and private enterprises
    type: economic_classification_1_and_2
programmes:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2017-18
  programme_budgets:
  - name: Administration
    total_budget: 243655000
  - name: Integrated Economic Development Services
    total_budget: 358053000
  - name: Trade and Sector Development
    total_budget: 842563000
  - name: Business Regulation and Governance
    total_budget: 112662000
  - name: Economic Planning
    total_budget: 39507000
  - name: Tourism
    total_budget: 231549000
  - name: Environmental Affairs
    total_budget: 956414000
selected_financial_year: 2017-18
selected_tab: departments
slug: economic-development-tourism-and-environmental-affairs
sphere:
  name: Provincial
  slug: provincial
title: Economic Development, Tourism and Environmental Affairs budget 2017-18  - vulekamali
treasury_datasets:
  'EPRE for Vote 04 : Economic Development, Tourism and Environmental Affairs':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/640d176a-d754-4241-a8ac-15f2126b7181/resource/109ae7dc-e3d4-4d02-aa89-d5ee1f4a242e/download/kzn-eco-dev-tou-and-envir.xlsm
    - format: PDF
      url: https://data.vulekamali.gov.za/dataset/640d176a-d754-4241-a8ac-15f2126b7181/resource/d7875214-f891-4082-88f8-466527d0db6f/download/kzn-vote-04-eco-dev-tourism-and-environmental-affairs.pdf
vote_number: 4
vote_primary:
  name: Economic Development, Tourism and Environmental Affairs
  slug: economic-development-tourism-and-environmental-affairs
  url_path: /2017-18/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
