contributed_datasets: null
financial_years:
- closest_match:
    is_exact_match: true
    name: Economic Development, Tourism and Environmental Affairs
    organisational_unit: department
    slug: economic-development-tourism-and-environmental-affairs
    url_path: /2015-16/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Economic Development, Tourism and Environmental Affairs
    organisational_unit: department
    slug: economic-development-tourism-and-environmental-affairs
    url_path: /2016-17/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Economic Development, Tourism and Environmental Affairs
    organisational_unit: department
    slug: economic-development-tourism-and-environmental-affairs
    url_path: /2017-18/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
  id: 2017-18
  is_selected: true
government:
  name: KwaZulu-Natal
  slug: kwazulu-natal
government_functions: []
intro: "## Vision\r\n\r\nThe vision of the Department of Economic Development, Tourism\
  \ and Environmental Affairs (EDTEA) is: Leading the attainment of inclusive and\
  \ sustainable economic growth for job creation\r\n\r\n\r\n\r\n## Mission\r\n\r\n\
  The department\u2019s mission is to: Provide leadership and facilitate integrated\
  \ economic planning, be a catalyst for economic transformation and sustainable development,\
  \ implement strategies that drive economic growth and promote sound environmental\
  \ management, create a conducive environment for trade, investment and tourism and\
  \ monitor and enforce sound business and consumer regulations.\r\n\r\n\r\n\r\n##\
  \ Core functions\r\n\r\nThe department\u2019s core functions are summarised as follows:\r\
  \n\r\n* To drive the economic development strategies of the province.\r\n\r\n* To\
  \ facilitate strategies to enhance the competitiveness of priority sectors of the\
  \ economy, in line with the industrial development strategy.\r\n\r\n* To promote\
  \ the development of small business and social enterprises.\r\n\r\n* To promote\
  \ and facilitate economic empowerment programmes.\r\n\r\n* To manage the Enterprise\
  \ Development and Growth Funds.\r\n\r\n* To provide an effective and efficient consumer\
  \ protection service.\r\n\r\n* To ensure effective and prudent business regulation\
  \ in the province.\r\n\r\n* To provide effective and efficient environmental management.\r\
  \n\r\n* To provide conservation services."
is_vote_primary: true
name: Economic Development, Tourism and Environmental Affairs
organisational_unit: department
programmes:
- name: Administration
  total_budget: 243655000.0
- name: Integrated Economic Development Services
  total_budget: 358053000.0
- name: Trade and Sector Development
  total_budget: 842563000.0
- name: Business Regulation and Governance
  total_budget: 112662000.0
- name: Economic Planning
  total_budget: 39507000.0
- name: Tourism
  total_budget: 231549000.0
- name: Environmental Affairs
  total_budget: 956414000.0
selected_financial_year: 2017-18
slug: economic-development-tourism-and-environmental-affairs
sphere:
  name: Provincial
  slug: provincial
treasury_datasets:
  'EPRE for Vote 04 : Economic Development, Tourism and Environmental Affairs':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/640d176a-d754-4241-a8ac-15f2126b7181/resource/109ae7dc-e3d4-4d02-aa89-d5ee1f4a242e/download/kzn-eco-dev-tou-and-envir.xlsm
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2017/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/KZN/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/KZN%20-%20Vote%2004%20-%20Eco%20Dev,%20Tourism%20and%20Environmental%20Affairs.pdf
vote_number: 4
vote_primary:
  name: Economic Development, Tourism and Environmental Affairs
  slug: economic-development-tourism-and-environmental-affairs
  url_path: /2017-18/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
