# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Online Budget Data Portal
email: feedback@vulekamali.gov.za
description: "South Africa's National and Provincial budget data from National Treasury in partnership with IMALI YETHU."
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://vulekamali.gov.za"
twitter_username: jekyllrb
github_username:  jekyll
latest_year: 2019-20

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - packages
  - node_modules
  - env
  - generate
  - backstop_data
  - tooling
  - generate
  - _includes
  - .history
  - .vscode
  - 2015-16
  - 2015-16/national
  - 2015-16/datasets
  - 2015-16/provincial
  - 2016-17
  - 2016-17/national
  - 2016-17/datasets
  - 2016-17/provincial
  - 2017-18
  - 2017-18/national
  - 2017-18/datasets
  - 2017-18/provincial
  - 2018-19
  - 2018-19/national
  - 2018-19/datasets
  - 2018-19/provincial
  - guides
  - datasets

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

defaults:
  -
    scope:
      path:            "20*/search-result.md"
    values:
      sitemap:         false