# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Online Budget Data Portal
email: feedback@vulekamali.gov.za
description: South Africa's National and Provincial budget data from National Treasury in partnership with IMALI YETHU.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://vulekamali.gov.za"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - env
  - generate
  - backstop_data
  - tooling
  - generate
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "2015-16"
    values:
      financial_year: 2015-16
      active: departments
      nested: true
  -
    scope:
      path: "2016-17"
    values:
      financial_year: 2016-17
      active: departments
      nested: true
  -
    scope:
      path: "2017-18"
    values:
      financial_year: 2017-18
      active: departments
      nested: true
  -
    scope:
      path: "2018-19"
    values:
      financial_year: 2018-19
      active: departments
      nested: true

  -
    scope:
      path: "2015-16/datasets"
    values:
      financial_year: 2015-16
      years: [
        ['2015-16', '/2015-16/contributed-data', 'active'],
        ['2016-17', '/2016-17/contributed-data', 'link'],
        ['2017-18', '/2017-18/contributed-data', 'link'],
        ['2018-19', '/2018-19/contributed-data', 'link'],
      ]
      active: contributed-data
      nested: true
  -
    scope:
      path: "2016-17/datasets"
    values:
      financial_year: 2016-17
      years: [
        ['2015-16', '/2015-16/contributed-data', 'link'],
        ['2016-17', '/2016-17/contributed-data', 'active'],
        ['2017-18', '/2017-18/contributed-data', 'link'],
        ['2018-19', '/2018-19/contributed-data', 'link'],
      ]
      active: contributed-data
      nested: true
  -
    scope:
      path: "2017-18/datasets"
    values:
      financial_year: 2017-18
      years: [
        ['2015-16', '/2015-16/contributed-data', 'link'],
        ['2016-17', '/2016-17/contributed-data', 'link'],
        ['2017-18', '/2017-18/contributed-data', 'active'],
        ['2018-19', '/2018-19/contributed-data', 'link'],
      ]
      active: contributed-data
      nested: true
  -
    scope:
      path: "2018-19/datasets"
    values:
      financial_year: 2018-19
      years: [
        ['2015-16', '/2015-16/contributed-data', 'link'],
        ['2016-17', '/2016-17/contributed-data', 'link'],
        ['2017-18', '/2017-18/contributed-data', 'link'],
        ['2018-19', '/2018-19/contributed-data', 'active'],
      ]
      active: contributed-data
      nested: true
