#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
description: 'Free State department: Economic And Small Business Development, Tourism
  And Environmental Affairs budget data for the 2018-19 financial year from National
  Treasury in partnership with IMALI YETHU.'
expenditure_over_time:
  base_financial_year: 2017-18
  nominal:
  - amount: 429772000.0
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 463414000.0
    financial_year: 2015-16
    phase: Audited Outcome
  - amount: 463076000.0
    financial_year: 2016-17
    phase: Audited Outcome
  - amount: 505148000.0
    financial_year: 2017-18
    phase: Adjusted appropriation
  - amount: 631931000.0
    financial_year: 2018-19
    phase: Main appropriation
  - amount: 632942000.0
    financial_year: 2019-20
    phase: Medium Term Estimates
  - amount: 675859000.0
    financial_year: 2020-21
    phase: Medium Term Estimates
  real:
  - amount: 503913094
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 516663206
    financial_year: 2015-16
    phase: Audited Outcome
  - amount: 485710226
    financial_year: 2016-17
    phase: Audited Outcome
  - amount: 505148000
    financial_year: 2017-18
    phase: Adjusted appropriation
  - amount: 599034343
    financial_year: 2018-19
    phase: Main appropriation
  - amount: 569841263
    financial_year: 2019-20
    phase: Medium Term Estimates
  - amount: 576535155
    financial_year: 2020-21
    phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2018-19
  is_selected: true
government:
  name: Free State
  slug: free-state
government_functions: []
intro: "## Mandate\n\n\nThere are several legislations and policies that the Department\
  \ has to operate within as it conducts its mandate. Below is the main legislation\
  \ the Department has to comply to:\n\n * Tourism second amendment Act, 2000 (Act\
  \ No.70 of 2000)\n * National Environmental Management Act No. 107 of 1998, as amended\n\
  \ * Environment Conservation Act No. 73 of 1989, as amended\n * National Environmental\
  \ Management: Air Quality Management Act No. 39 of 2004\n * NEM: Biodiversity Act,\
  \ 2004 (Act No.10 of 2004)\n * NEM: Protected Areas Act, 2003 (Act No. 57 of 2003)\n\
  \ * The Free State Nature Conservation Ordinance,1969 (Ord. No.8 of 1969)\n * Environment\
  \ Conservation Act of 1989, as amended.\n * World Heritage Conservation Act, 1999\n\
  \ * Conservation of Agricultural Resources Act, 1983 (Act No. 43 of 1983)\n * Animal\
  \ Protection Act, 1962 (Act No. 71 of 1962)\n * National Forest Act, 1998 (Act No.\
  \ 84 of 1998)\n * Veld and Forest Fire Act, 1998 (Act No. 101 of 1998)\n * Game\
  \ Theft Act, 1991 (Act No. 105 of 1991)\n * National Heritage Resources, 1999 (\
  \ Act No. 25 of 1999)\n * National Water Act, 1998 (Act No. 36 of 1998)\n * Co-operative\
  \ Act, 2005 (Act No 14. of  2005)\n\n## Vision\n\nA transformed economy and a prosperous\
  \ society that is living in harmony with its natural resources through integrated\
  \ and sustainable economic growth.\n\n## Mission\n\nRadically create a conducive,\
  \ enabling environment for the creation of decent jobs, poverty and inequality reduction\
  \ through sustainably managed environment and economic development programmes in\
  \ the Free State\n\n"
is_vote_primary: true
name: Economic And Small Business Development, Tourism And Environmental Affairs
programmes:
- name: Administration
  total_budget: 160448000.0
- name: Environmental Affairs
  total_budget: 163770000.0
- name: Economic And Small Business Development
  total_budget: 295583000.0
- name: Tourism
  total_budget: 12130000.0
- name: Direct Charges
  total_budget: 0.0
selected_financial_year: 2018-19
selected_tab: departments
slug: economic-and-small-business-development-tourism-and-environmental-affairs
sphere:
  name: Provincial
  slug: provincial
title: Economic And Small Business Development, Tourism And Environmental Affairs
  budget 2018-19  - vulekamali
treasury_datasets:
  EPRE for Vote 3 - Economic And Small Business Development, Tourism And Environmental Affairs:
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: PDF
      url: https://data.vulekamali.gov.za/dataset/da4b8658-8126-4cc9-bb68-31546075acb8/resource/0f791799-813f-4fd3-b568-f6ec01587ac1/download/fs-vote-03-economic-development-tourism-and-enviroment.pdf
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/da4b8658-8126-4cc9-bb68-31546075acb8/resource/0873d7d9-4d16-4e9f-8b6e-ab91d465ad69/download/fs-economic-small-busin-dev-tourism.xlsm
vote_number: 3
vote_primary:
  name: Economic And Small Business Development, Tourism And Environmental Affairs
  slug: economic-and-small-business-development-tourism-and-environmental-affairs
  url_path: /2018-19/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
