#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: The transparency of public funding of Basic Education in South Africa
  url_path: /datasets/contributed/the-transparency-of-public-funding-of-basic-education-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
- contributor: Centre for Child Law
  name: 'Mud to bricks: A review of school infrastructure spending and delivery'
  url_path: /datasets/contributed/mud-to-bricks-a-review-of-school-infrastructure-spending-and-delivery
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Eastern Cape Department of Health 2014/15'
  url_path: /datasets/contributed/budget-brief-eastern-cape-department-of-health-2014-15
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Eastern Cape Department of Education 2016/17'
  url_path: /datasets/contributed/budget-brief-eastern-cape-department-of-education-2016-17
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Eastern Cape Department of Human Settlements 2014/15'
  url_path: /datasets/contributed/budget-brief-eastern-cape-department-of-human-settlements-2014-15
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Department of Human Settlements, 2016/17 and 2017/18'
  url_path: /datasets/contributed/budget-brief-department-of-human-settlements
description: 'North West department: Rural Environment and Agricultural Development
  budget data for the 2017-18 financial year from National Treasury in partnership
  with IMALI YETHU.'
expenditure_over_time:
  base_financial_year: 2017-18
  nominal:
  - amount: 1072012000
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 1169275000
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 1183763000
    financial_year: 2015-16
    phase: Audited Outcome
  - amount: 1286341000
    financial_year: 2016-17
    phase: Adjusted appropriation
  - amount: 1370637000
    financial_year: 2017-18
    phase: Main appropriation
  - amount: 1441393000
    financial_year: 2018-19
    phase: Medium Term Estimates
  - amount: 1556073000
    financial_year: 2019-20
    phase: Medium Term Estimates
  real:
  - amount: 1327663352
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 1370989694
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 1319784872
    financial_year: 2015-16
    phase: Audited Outcome
  - amount: 1349214769
    financial_year: 2016-17
    phase: Adjusted appropriation
  - amount: 1370637000
    financial_year: 2017-18
    phase: Main appropriation
  - amount: 1366357893
    financial_year: 2018-19
    phase: Medium Term Estimates
  - amount: 1400941324
    financial_year: 2019-20
    phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2017-18
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2018-19
  is_selected: false
government:
  name: North West
  slug: north-west
government_functions:
- Agriculture, rural development and land reform
- Economic affairs
intro: "## Vision\n\nVibrant and prosperous society in harmony with our natural resources.\r\
  \n\r\n\n\n## Mission\n\nWorking together with our partners to provide a transformed\
  \ sustainable, agricultural, environmental management and comprehensive integrated\
  \ rural development.\r\n\r\n\n\n## Core functions\n\nThe Department focus primarily\
  \ on the following mandated core functions:-\r\n\r\n* Rolling out the Comprehensive\
  \ Rural Development Programme;\r\n\r\n* Creating decent employment through Inclusive\
  \ Economic Growth; and\r\n\r\n* Protecting and Enhancing Environmental Assets and\
  \ Natural Resources."
is_vote_primary: true
name: Rural Environment and Agricultural Development
programmes:
- name: Administration
  total_budget: 267168000
- name: Sustainable Resource Management
  total_budget: 30890000
- name: Farmer Support and Development
  total_budget: 420177000
- name: Veterinary Services
  total_budget: 129387000
- name: Research and Technology  Development Services
  total_budget: 54996000
- name: Agricultural Economics Services
  total_budget: 11622000
- name: Structured Agricultural Education and  Training
  total_budget: 103085000
- name: Rural Development Coordination
  total_budget: 77272000
- name: Environmental Services
  total_budget: 276040000
selected_financial_year: 2017-18
selected_tab: departments
slug: rural-environment-and-agricultural-development
sphere:
  name: Provincial
  slug: provincial
title: Rural Environment and Agricultural Development budget 2017-18  - vulekamali
treasury_datasets: {}
vote_number: 13
vote_primary:
  name: Rural Environment and Agricultural Development
  slug: rural-environment-and-agricultural-development
  url_path: /2017-18/provincial/north-west/departments/rural-environment-and-agricultural-development
