#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
description: 'North West department: Rural Environment and Agricultural Development
  budget data for the 2017-18 financial year from National Treasury in partnership
  with IMALI YETHU.'
expenditure_over_time:
  base_financial_year: 2017-18
  nominal:
  - amount: 1072012000
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 1169275000
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 1183763000
    financial_year: 2015-16
    phase: Audited Outcome
  - amount: 1286341000
    financial_year: 2016-17
    phase: Adjusted appropriation
  - amount: 1370637000
    financial_year: 2017-18
    phase: Main appropriation
  - amount: 1441393000
    financial_year: 2018-19
    phase: Medium Term Estimates
  - amount: 1556073000
    financial_year: 2019-20
    phase: Medium Term Estimates
  real:
  - amount: 1327663352
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 1370989694
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 1319784872
    financial_year: 2015-16
    phase: Audited Outcome
  - amount: 1349214769
    financial_year: 2016-17
    phase: Adjusted appropriation
  - amount: 1370637000
    financial_year: 2017-18
    phase: Main appropriation
  - amount: 1366357893
    financial_year: 2018-19
    phase: Medium Term Estimates
  - amount: 1400941324
    financial_year: 2019-20
    phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2017-18
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2018-19
  is_selected: false
government:
  name: North West
  slug: north-west
government_functions:
- Agriculture, rural development and land reform
- Economic affairs
intro: "## Vision\n\nVibrant and prosperous society in harmony with our natural resources.\r\
  \n\r\n\n\n## Mission\n\nWorking together with our partners to provide a transformed\
  \ sustainable, agricultural, environmental management and comprehensive integrated\
  \ rural development.\r\n\r\n\n\n## Core functions\n\nThe Department focus primarily\
  \ on the following mandated core functions:-\r\n\r\n* Rolling out the Comprehensive\
  \ Rural Development Programme;\r\n\r\n* Creating decent employment through Inclusive\
  \ Economic Growth; and\r\n\r\n* Protecting and Enhancing Environmental Assets and\
  \ Natural Resources."
is_vote_primary: true
name: Rural Environment and Agricultural Development
programmes:
- name: Administration
  total_budget: 267168000
- name: Sustainable Resource Management
  total_budget: 30890000
- name: Farmer Support and Development
  total_budget: 420177000
- name: Veterinary Services
  total_budget: 129387000
- name: Research and Technology  Development Services
  total_budget: 54996000
- name: Agricultural Economics Services
  total_budget: 11622000
- name: Structured Agricultural Education and  Training
  total_budget: 103085000
- name: Rural Development Coordination
  total_budget: 77272000
- name: Environmental Services
  total_budget: 276040000
selected_financial_year: 2017-18
selected_tab: departments
slug: rural-environment-and-agricultural-development
sphere:
  name: Provincial
  slug: provincial
title: Rural Environment and Agricultural Development budget 2017-18  - vulekamali
treasury_datasets:
  'EPRE for Vote 13 : Rural Environment and Agricultural Development':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/82b4c8ec-e041-4a12-95fc-48662316eb8d/resource/a6ef8951-3cb3-489d-8426-867e6f50ff96/download/nw-rural-env.-and-agricultural-dev..xlsm
    - format: PDF
      url: https://data.vulekamali.gov.za/dataset/82b4c8ec-e041-4a12-95fc-48662316eb8d/resource/9c70d8d5-8d88-41cd-91aa-bd4d7755ad72/download/nw-vote-13-rural-environment-and-agricultural-development.pdf
vote_number: 13
vote_primary:
  name: Rural Environment and Agricultural Development
  slug: rural-environment-and-agricultural-development
  url_path: /2017-18/provincial/north-west/departments/rural-environment-and-agricultural-development
