contributed_datasets: null
financial_years:
- closest_match:
    is_exact_match: true
    name: Rural, Environment and Agricultural Development
    organisational_unit: department
    slug: rural-environment-and-agricultural-development
    url_path: /2015-16/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Rural Environment and Agricultural Development
    organisational_unit: department
    slug: rural-environment-and-agricultural-development
    url_path: /2016-17/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Rural Environment and Agricultural Development
    organisational_unit: department
    slug: rural-environment-and-agricultural-development
    url_path: /2017-18/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2017-18
  is_selected: true
government:
  name: North West
  slug: north-west
government_functions:
- Agriculture, rural development and land reform
- Economic affairs
intro: "## Vision\n\nVibrant and prosperous society in harmony with our natural resources.\r\
  \n\r\n\n\n## Mission\n\nWorking together with our partners to provide a transformed\
  \ sustainable, agricultural, environmental management and comprehensive integrated\
  \ rural development.\r\n\r\n\n\n## Core functions\n\nThe Department focus primarily\
  \ on the following mandated core functions:-\r\n\r\n* Rolling out the Comprehensive\
  \ Rural Development Programme;\r\n\r\n* Creating decent employment through Inclusive\
  \ Economic Growth; and\r\n\r\n* Protecting and Enhancing Environmental Assets and\
  \ Natural Resources."
is_vote_primary: true
name: Rural Environment and Agricultural Development
organisational_unit: department
programmes:
- name: Administration
  total_budget: 267168000.0
- name: Sustainable Resource Management
  total_budget: 30890000.0
- name: Farmer Support and Development
  total_budget: 420177000.0
- name: Veterinary Services
  total_budget: 129387000.0
- name: Research and Technology  Development Services
  total_budget: 54996000.0
- name: Agricultural Economics Services
  total_budget: 11622000.0
- name: Structured Agricultural Education and  Training
  total_budget: 103085000.0
- name: Rural Development Coordination
  total_budget: 77272000.0
- name: Environmental Services
  total_budget: 276040000.0
selected_financial_year: 2017-18
slug: rural-environment-and-agricultural-development
sphere:
  name: Provincial
  slug: provincial
treasury_datasets:
  'EPRE for Vote 13 : Rural Environment and Agricultural Development':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/82b4c8ec-e041-4a12-95fc-48662316eb8d/resource/a6ef8951-3cb3-489d-8426-867e6f50ff96/download/nw-rural-env.-and-agricultural-dev..xlsm
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2017/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/NW/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/NW
        - Vote 13 - Rural Environment and Agricultural Development.pdf
vote_number: 13
vote_primary:
  name: Rural Environment and Agricultural Development
  slug: rural-environment-and-agricultural-development
  url_path: /2017-18/provincial/north-west/departments/rural-environment-and-agricultural-development
