financial_years:
- id: 2015-16
  is_selected: false
- id: 2016-17
  is_selected: false
- id: 2017-18
  is_selected: true
government:
  name: Free State
name: Department of Economic and Small Business Development, Tourism and Environmental
  Affairs
vote_number: 3
