financial_years:
- closest_match:
    is_exact_match: false
    name: Free State
    organisational_unit: government
    url_path: /2015-16/provincial/free-state
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Department of Economic and Small Business Development, Tourism and Environmental
      Affairs
    organisational_unit: department
    url_path: /2016-17/provincial/free-state/departments/department-of-economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Department of Economic and Small Business Development, Tourism and Environmental
      Affairs
    organisational_unit: department
    url_path: /2017-18/provincial/free-state/departments/department-of-economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2017-18
  is_selected: true
government:
  name: Free State
name: Department of Economic and Small Business Development, Tourism and Environmental
  Affairs
vote_number: 3
