financial_years:
- closest_match:
    is_exact_match: false
    name: Free State
    organisational_unit: government
    slug: free-state
    url_path: /2015-16/provincial/free-state
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Department of Economic and Small Business Development, Tourism and Environmental
      Affairs
    organisational_unit: department
    slug: department-of-economic-and-small-business-development-tourism-and-environmental-affairs
    url_path: /2016-17/provincial/free-state/departments/department-of-economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Department of Economic and Small Business Development, Tourism and Environmental
      Affairs
    organisational_unit: department
    slug: department-of-economic-and-small-business-development-tourism-and-environmental-affairs
    url_path: /2017-18/provincial/free-state/departments/department-of-economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2017-18
  is_selected: true
government:
  name: Free State
  slug: free-state
name: Department of Economic and Small Business Development, Tourism and Environmental
  Affairs
narrative: {}
resources:
  'EPRE for Vote 03 : Department of Economic and Small Business Development, Tourism and Environmental Affairs':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://treasurydata.openup.org.za/dataset/30874949-d94b-4186-9711-fc06aaf96e60/resource/1ac9bf2d-53e3-481a-96ab-773f95fc805e/download/fs-economic-small-busin-dev-tourism.xlsm
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2017/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/FS/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/FS
        - Vote 03 - Economic Development, Tourism and Enviroment.pdf
slug: department-of-economic-and-small-business-development-tourism-and-environmental-affairs
vote_number: 3
