#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
description: 'Free State department: Economic and Small Business Development, Tourism
  and Environmental Affairs budget data for the 2017-18 financial year from National
  Treasury in partnership with IMALI YETHU.'
economic_classification_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2017-18
  programmes:
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 91911000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 51631000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 648000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Departmental agencies and accounts
        total_budget: 4000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Administration
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 44050000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 37237000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 2000000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Departmental agencies and accounts
        total_budget: 105425000
        type: economic_classification_2
      - name: Public corporations and private enterprises
        total_budget: 32260000
        type: economic_classification_2
      - name: Households
        total_budget: 1000000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Economic and Small Business Development
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 93952000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 48374000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Buildings and other fixed structures
        total_budget: 30895000
        type: economic_classification_2
      - name: Machinery and equipment
        total_budget: 839000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Departmental agencies and accounts
        total_budget: 196000
        type: economic_classification_2
      - name: Households
        total_budget: 80000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Environmental Affairs
    type: programme
  - items:
    - items:
      - name: Goods and services
        total_budget: 10207000
        type: economic_classification_2
      - name: Compensation of employees
        total_budget: 7978000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 91000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    name: Tourism
    type: programme
expenditure_over_time:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2017-18
  expenditure:
    base_financial_year: 2017-18
    nominal:
    - amount: 432354000
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 429772000
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 463414000
      financial_year: 2015-16
      phase: Audited Outcome
    - amount: 474996000
      financial_year: 2016-17
      phase: Adjusted appropriation
    - amount: 558778000
      financial_year: 2017-18
      phase: Main appropriation
    - amount: 602361000
      financial_year: 2018-19
      phase: Medium Term Estimates
    - amount: 621180000
      financial_year: 2019-20
      phase: Medium Term Estimates
    real:
    - amount: 535460947
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 503913094
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 516663206
      financial_year: 2015-16
      phase: Audited Outcome
    - amount: 498212852
      financial_year: 2016-17
      phase: Adjusted appropriation
    - amount: 558778000
      financial_year: 2017-18
      phase: Main appropriation
    - amount: 571003679
      financial_year: 2018-19
      phase: Medium Term Estimates
    - amount: 559251868
      financial_year: 2019-20
      phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2017-18
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2018-19
  is_selected: false
government:
  name: Free State
  slug: free-state
government_functions: []
intro: "## Vision\r\n\r\nA transformed economy and a prosperous society that is living\
  \ in harmony with its natural resources through integrated and sustainable economic\
  \ growth.\r\n\r\n\r\n\r\n## Mission\r\n\r\nRadically create a conducive, enabling\
  \ environment for the creation of decent jobs, poverty and inequality reduction\
  \ through sustainably managed environment and economic development programmes in\
  \ the Free State\r\n\r\n\r\n\r\n## Core functions\r\n\r\nIntegrated and sustainable\
  \ Economic Development.\r\n\r\n* To stimulate integrated, regulated, informed and\
  \ sustainable economic\r\ndevelopment through trade & investment facilitation, sector\
  \ development and\r\nindustrialization, by providing services to the stakeholders\
  \ which we service.\r\n\r\n* Environmental assets conserved, valued, sustainably\
  \ used, protected and\r\ncontinually enhanced to benefit the present and future\
  \ generations.\r\n\r\n* To manage the environment in order to lead sustainable development\
  \ of the\r\nenvironment for a better life for all in the province.\r\n\r\n* Radical\
  \ efficacy in business processes.\r\n\r\n* To ensure rapid and efficient business\
  \ processes within the Department:\r\n- Doing business unusual (fast and efficient).\r\
  \n\r\n- Enabling line function to achieve their mandates.\r\n\r\n* To create a conducive\
  \ environment for sustainable tourism growth and\r\ndevelopment in the Province.\r\
  \n\r\n* A tourism industry that is supported by sound policies that seeks to transform\r\
  \nthe tourism industry through robust product development to effectively\r\npromote\
  \ and market the Province as a tourist destination of choice."
is_vote_primary: true
name: Economic and Small Business Development, Tourism and Environmental Affairs
programme_by_economic_classification:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2017-18
  econ_classes:
  - items:
    - name: Environmental Affairs
      total_budget: 93952000
      type: programme
    - name: Administration
      total_budget: 91911000
      type: programme
    - name: Economic and Small Business Development
      total_budget: 44050000
      type: programme
    - name: Tourism
      total_budget: 7978000
      type: programme
    name: Current payments - Compensation of employees
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 51631000
      type: programme
    - name: Environmental Affairs
      total_budget: 48374000
      type: programme
    - name: Economic and Small Business Development
      total_budget: 37237000
      type: programme
    - name: Tourism
      total_budget: 10207000
      type: programme
    name: Current payments - Goods and services
    type: economic_classification_1_and_2
  - items:
    - name: Environmental Affairs
      total_budget: 30895000
      type: programme
    name: Payments for capital assets - Buildings and other fixed structures
    type: economic_classification_1_and_2
  - items:
    - name: Economic and Small Business Development
      total_budget: 2000000
      type: programme
    - name: Environmental Affairs
      total_budget: 839000
      type: programme
    - name: Administration
      total_budget: 648000
      type: programme
    - name: Tourism
      total_budget: 91000
      type: programme
    name: Payments for capital assets - Machinery and equipment
    type: economic_classification_1_and_2
  - items:
    - name: Economic and Small Business Development
      total_budget: 105425000
      type: programme
    - name: Environmental Affairs
      total_budget: 196000
      type: programme
    - name: Administration
      total_budget: 4000
      type: programme
    name: Transfers and subsidies - Departmental agencies and accounts
    type: economic_classification_1_and_2
  - items:
    - name: Economic and Small Business Development
      total_budget: 1000000
      type: programme
    - name: Environmental Affairs
      total_budget: 80000
      type: programme
    name: Transfers and subsidies - Households
    type: economic_classification_1_and_2
  - items:
    - name: Economic and Small Business Development
      total_budget: 32260000
      type: programme
    name: Transfers and subsidies - Public corporations and private enterprises
    type: economic_classification_1_and_2
programmes:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2017-18
  programme_budgets:
  - name: Administration
    total_budget: 144194000
  - name: Environmental Affairs
    total_budget: 174336000
  - name: Economic and Small Business Development
    total_budget: 221972000
  - name: Tourism
    total_budget: 18276000
selected_financial_year: 2017-18
selected_tab: departments
slug: economic-and-small-business-development-tourism-and-environmental-affairs
sphere:
  name: Provincial
  slug: provincial
subprogramme_by_programme: null
title: Economic and Small Business Development, Tourism and Environmental Affairs
  budget 2017-18  - vulekamali
treasury_datasets:
  'EPRE for Vote 03 : Department of Economic and Small Business Development, Tourism and Environmental Affairs':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/30874949-d94b-4186-9711-fc06aaf96e60/resource/1ac9bf2d-53e3-481a-96ab-773f95fc805e/download/fs-economic-small-busin-dev-tourism.xlsm
    - format: PDF
      url: https://data.vulekamali.gov.za/dataset/30874949-d94b-4186-9711-fc06aaf96e60/resource/2a03a454-a2e1-48bb-b4ba-b534c373085d/download/fs-vote-03-economic-development-tourism-and-enviroment.pdf
vote_number: 3
vote_primary:
  name: Economic and Small Business Development, Tourism and Environmental Affairs
  slug: economic-and-small-business-development-tourism-and-environmental-affairs
  url_path: /2017-18/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
