#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
description: 'Mpumalanga department: Agriculture, Rural Development, Land and Environmental
  Affairs budget data for the 2017-18 financial year from National Treasury in partnership
  with IMALI YETHU.'
economic_classification_by_programme:
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 102096000
    - economic_classification_2_name: Goods and services
      total_budget: 46599000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 2440000
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Households
      total_budget: 5088000
    - economic_classification_2_name: Departmental agencies and accounts
      total_budget: 1750000
    - economic_classification_2_name: Provinces and municipalities
      total_budget: 160000
  programme_name: Administration
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 8228000
    - economic_classification_2_name: Goods and services
      total_budget: 2820000
  programme_name: Agricultural Economics Services
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 79829000
    - economic_classification_2_name: Goods and services
      total_budget: 27604000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Buildings and other fixed structures
      total_budget: 5300000
  programme_name: Environmental Affairs
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 183979000
    - economic_classification_2_name: Goods and services
      total_budget: 126709000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 4065000
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Households
      total_budget: 216868000
  programme_name: Farmer Support and Development
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 47787000
    - economic_classification_2_name: Goods and services
      total_budget: 10521000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Buildings and other fixed structures
      total_budget: 4200000
    - economic_classification_2_name: Machinery and equipment
      total_budget: 1100000
  programme_name: Research and Technology Development Services
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 16413000
    - economic_classification_2_name: Goods and services
      total_budget: 5556000
  programme_name: Rural Development Coordination
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 14179000
    - economic_classification_2_name: Goods and services
      total_budget: 9870000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Buildings and other fixed structures
      total_budget: 2300000
  programme_name: Structured Agricultural Education and Training
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 50189000
    - economic_classification_2_name: Goods and services
      total_budget: 6957000
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Households
      total_budget: 11934000
  programme_name: Sustainable Resource Management
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 106817000
    - economic_classification_2_name: Goods and services
      total_budget: 21879000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Buildings and other fixed structures
      total_budget: 1500000
    - economic_classification_2_name: Machinery and equipment
      total_budget: 64000
  programme_name: Veterinary Services
expenditure_over_time:
  base_financial_year: 2017-18
  nominal:
  - amount: 1007100000
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 1004444000
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 1005346000
    financial_year: 2015-16
    phase: Audited Outcome
  - amount: 974133000
    financial_year: 2016-17
    phase: Adjusted appropriation
  - amount: 1124801000
    financial_year: 2017-18
    phase: Main appropriation
  - amount: 1178845000
    financial_year: 2018-19
    phase: Medium Term Estimates
  - amount: 1250489000
    financial_year: 2019-20
    phase: Medium Term Estimates
  real:
  - amount: 1247271263
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 1177723266
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 1120866627
    financial_year: 2015-16
    phase: Audited Outcome
  - amount: 1021746668
    financial_year: 2016-17
    phase: Adjusted appropriation
  - amount: 1124801000
    financial_year: 2017-18
    phase: Main appropriation
  - amount: 1117477447
    financial_year: 2018-19
    phase: Medium Term Estimates
  - amount: 1125822320
    financial_year: 2019-20
    phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
  id: 2017-18
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
  id: 2018-19
  is_selected: false
government:
  name: Mpumalanga
  slug: mpumalanga
government_functions: []
intro: "## Vision\r\n\r\nVibrant, equitable, and sustainable urban and rural communities\
  \ with a united and prosperous agricultural sector\r\n\r\n## Mission\r\n\r\nTo facilitate\
  \ an integrated, comprehensive, sustainable, social and agricultural development\
  \ in rural and urban communities, through ensuring cohesion and collaboration by\
  \ all sectors\r\nof society.\r\n\r\n## Core functions\r\n\r\nThe Department will\
  \ continue with the implementation of the following priority policy initiatives\
  \ in response to Outcome 7 and Outcome 10 in particular\r\n\r\n* Accelerate the\
  \ implementation of Mpumalanga Fortune 40 Young Farmer Incubator Programme\r\n\r\
  \n* Provide Irrigation Infrastructure\r\n\r\n* Identify and capacitate farmers to\
  \ increase food production\r\n\r\n* Increase Meat Production: (Red and White meat)\r\
  \n\r\n* Increase Grain Production: (Maize, Soya bean, Sorghum)\r\n\r\n* Increase\
  \ Tropical Fruit and Vegetable Production\r\n\r\n* Development and refurbishment\
  \ of the agro-processing facilities for Meat, grains, fruit and vegetable\r\n\r\n\
  * Improve Research Development Programme\r\n\r\n* Provide support to affected farmers\
  \ through Disaster Relief Schemes\r\n\r\n* Monitor climate change through Climate\
  \ Change Response Tools\r\n\r\n* Ambient Air Quality Monitoring Stations Commissioned;\
  \ Operated And Maintained"
is_vote_primary: true
name: Agriculture, Rural Development, Land and Environmental Affairs
programmes:
- name: Administration
  total_budget: 158133000
- name: Sustainable Resource Management
  total_budget: 69080000
- name: Farmer Support and Development
  total_budget: 531621000
- name: Veterinary Services
  total_budget: 130260000
- name: Research and Technology Development Services
  total_budget: 63608000
- name: Agricultural Economics Services
  total_budget: 11048000
- name: Structured Agricultural Education and Training
  total_budget: 26349000
- name: Rural Development Coordination
  total_budget: 21969000
- name: Environmental Affairs
  total_budget: 112733000
selected_financial_year: 2017-18
selected_tab: departments
slug: agriculture-rural-development-land-and-environmental-affairs
sphere:
  name: Provincial
  slug: provincial
title: Agriculture, Rural Development, Land and Environmental Affairs budget 2017-18  -
  vulekamali
treasury_datasets:
  'EPRE for Vote 05 : Agriculture, Rural Development, Land and Environmental Affairs':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/12e49641-21e5-4275-9ade-0a7dd036a505/resource/3a6e1679-6da3-4c94-900a-cc3c13ebd6ae/download/mpu-agric.-rural-dev.-land-and-env.-affairs.xlsm
    - format: PDF
      url: https://data.vulekamali.gov.za/dataset/12e49641-21e5-4275-9ade-0a7dd036a505/resource/5a8ad9a0-a348-4fbc-ad16-97b377937d0a/download/mpu-vote-05-agric.-rural-dev.-land-and-env.-affairs.pdf
vote_number: 5
vote_primary:
  name: Agriculture, Rural Development, Land and Environmental Affairs
  slug: agriculture-rural-development-land-and-environmental-affairs
  url_path: /2017-18/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
