financial_years:
- closest_match:
    is_exact_match: true
    name: Economic Development, Environment and Tourism
    organisational_unit: department
    slug: economic-development-environment-and-tourism
    url_path: /2015-16/provincial/mpumalanga/departments/economic-development-environment-and-tourism
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Economic Development, Environment and Tourism
    organisational_unit: department
    slug: economic-development-environment-and-tourism
    url_path: /2016-17/provincial/mpumalanga/departments/economic-development-environment-and-tourism
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Economic Development, Environment and Tourism
    organisational_unit: department
    slug: economic-development-environment-and-tourism
    url_path: /2017-18/provincial/mpumalanga/departments/economic-development-environment-and-tourism
  id: 2017-18
  is_selected: true
government:
  name: Mpumalanga
  slug: mpumalanga
intro: "## Vision\n\nAn Inclusive, Global Competitive Economy\r\n\r\n\n\n## Mission\n\
  \nDrive economic growth that creates decent employment and promote sustainable\r\
  \ndevelopment through partnership.\r\n\r\n\r\n\r\n"
name: Economic Development, Environment and Tourism
resources:
  'EPRE for Vote 06 : Economic Development, Environment and Tourism':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://treasurydata.openup.org.za/dataset/3075ee2c-23ba-4e66-a2cc-6d58a1fd23ad/resource/d536d1e2-8863-4410-9e0d-1f5d4cb7e96f/download/mpu-eco.-development-and-tourism.xlsm
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2017/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/MPU/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/MPU
        - Vote 06 - Economic Development and Tourism.pdf
slug: economic-development-environment-and-tourism
vote_number: 6
