#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

adjusted_budget_summary: null
budget_actual:
  dataset_detail_page: /datasets/budgeted-and-actual-provincial-expenditure/budgeted-and-actual-provincial-expenditure
  expenditure:
    base_financial_year: 2018-19
    nominal:
    - amount: 140757000
      financial_year: 2016-17
      phase: Main appropriation
    - amount: 148991000
      financial_year: 2017-18
      phase: Main appropriation
    - amount: null
      financial_year: 2016-17
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2016-17
      phase: Final Appropriation
    - amount: null
      financial_year: 2016-17
      phase: Audit Outcome
    - amount: null
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2017-18
      phase: Final Appropriation
    - amount: null
      financial_year: 2017-18
      phase: Audit Outcome
    - amount: null
      financial_year: 2018-19
      phase: Main appropriation
    - amount: null
      financial_year: 2018-19
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2018-19
      phase: Final Appropriation
    - amount: null
      financial_year: 2018-19
      phase: Audit Outcome
    - amount: null
      financial_year: 2019-20
      phase: Main appropriation
    - amount: null
      financial_year: 2019-20
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2019-20
      phase: Final Appropriation
    - amount: null
      financial_year: 2019-20
      phase: Audit Outcome
    real:
    - amount: 154633022
      financial_year: 2016-17
      phase: Main appropriation
    - amount: 156309724
      financial_year: 2017-18
      phase: Main appropriation
    - amount: null
      financial_year: 2016-17
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2016-17
      phase: Final Appropriation
    - amount: null
      financial_year: 2016-17
      phase: Audit Outcome
    - amount: null
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2017-18
      phase: Final Appropriation
    - amount: null
      financial_year: 2017-18
      phase: Audit Outcome
    - amount: null
      financial_year: 2018-19
      phase: Main appropriation
    - amount: null
      financial_year: 2018-19
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2018-19
      phase: Final Appropriation
    - amount: null
      financial_year: 2018-19
      phase: Audit Outcome
    - amount: null
      financial_year: 2019-20
      phase: Main appropriation
    - amount: null
      financial_year: 2019-20
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2019-20
      phase: Final Appropriation
    - amount: null
      financial_year: 2019-20
      phase: Audit Outcome
  notices:
  - Please note that the data for 2019 has not been published on vulekamali.
  - This department did not exist for some years displayed.
budget_actual_programmes:
  dataset_detail_page: /datasets/budgeted-and-actual-provincial-expenditure/budgeted-and-actual-provincial-expenditure
  notices:
  - One or more programmes did not exist for some years displayed.
  programmes:
  - items:
    - amount: 10411000
      financial_year: 2016-17
      phase: Main appropriation
    - amount: 10773000
      financial_year: 2017-18
      phase: Main appropriation
    - amount: null
      financial_year: 2016-17
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2016-17
      phase: Final Appropriation
    - amount: null
      financial_year: 2016-17
      phase: Audit Outcome
    - amount: null
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2017-18
      phase: Final Appropriation
    - amount: null
      financial_year: 2017-18
      phase: Audit Outcome
    - amount: null
      financial_year: 2018-19
      phase: Main appropriation
    - amount: null
      financial_year: 2018-19
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2018-19
      phase: Final Appropriation
    - amount: null
      financial_year: 2018-19
      phase: Audit Outcome
    - amount: null
      financial_year: 2019-20
      phase: Main appropriation
    - amount: null
      financial_year: 2019-20
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2019-20
      phase: Final Appropriation
    - amount: null
      financial_year: 2019-20
      phase: Audit Outcome
    name: ENVIRONMENTAL POLICY,PLANNING AND COORDINATION
  - items:
    - amount: 12669000
      financial_year: 2016-17
      phase: Main appropriation
    - amount: 13543000
      financial_year: 2017-18
      phase: Main appropriation
    - amount: null
      financial_year: 2016-17
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2016-17
      phase: Final Appropriation
    - amount: null
      financial_year: 2016-17
      phase: Audit Outcome
    - amount: null
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2017-18
      phase: Final Appropriation
    - amount: null
      financial_year: 2017-18
      phase: Audit Outcome
    - amount: null
      financial_year: 2018-19
      phase: Main appropriation
    - amount: null
      financial_year: 2018-19
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2018-19
      phase: Final Appropriation
    - amount: null
      financial_year: 2018-19
      phase: Audit Outcome
    - amount: null
      financial_year: 2019-20
      phase: Main appropriation
    - amount: null
      financial_year: 2019-20
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2019-20
      phase: Final Appropriation
    - amount: null
      financial_year: 2019-20
      phase: Audit Outcome
    name: ENVIRONMENTAL EMPOWERMENT SERVICES
  - items:
    - amount: 14011000
      financial_year: 2016-17
      phase: Main appropriation
    - amount: 11176000
      financial_year: 2017-18
      phase: Main appropriation
    - amount: null
      financial_year: 2016-17
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2016-17
      phase: Final Appropriation
    - amount: null
      financial_year: 2016-17
      phase: Audit Outcome
    - amount: null
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2017-18
      phase: Final Appropriation
    - amount: null
      financial_year: 2017-18
      phase: Audit Outcome
    - amount: null
      financial_year: 2018-19
      phase: Main appropriation
    - amount: null
      financial_year: 2018-19
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2018-19
      phase: Final Appropriation
    - amount: null
      financial_year: 2018-19
      phase: Audit Outcome
    - amount: null
      financial_year: 2019-20
      phase: Main appropriation
    - amount: null
      financial_year: 2019-20
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2019-20
      phase: Final Appropriation
    - amount: null
      financial_year: 2019-20
      phase: Audit Outcome
    name: COMPLIANCE AND ENFORCEMENT
  - items:
    - amount: 14308000
      financial_year: 2016-17
      phase: Main appropriation
    - amount: 14251000
      financial_year: 2017-18
      phase: Main appropriation
    - amount: null
      financial_year: 2016-17
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2016-17
      phase: Final Appropriation
    - amount: null
      financial_year: 2016-17
      phase: Audit Outcome
    - amount: null
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2017-18
      phase: Final Appropriation
    - amount: null
      financial_year: 2017-18
      phase: Audit Outcome
    - amount: null
      financial_year: 2018-19
      phase: Main appropriation
    - amount: null
      financial_year: 2018-19
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2018-19
      phase: Final Appropriation
    - amount: null
      financial_year: 2018-19
      phase: Audit Outcome
    - amount: null
      financial_year: 2019-20
      phase: Main appropriation
    - amount: null
      financial_year: 2019-20
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2019-20
      phase: Final Appropriation
    - amount: null
      financial_year: 2019-20
      phase: Audit Outcome
    name: ENVIRONMENTAL QUALITY MANAGEMENT
  - items:
    - amount: 28050000
      financial_year: 2016-17
      phase: Main appropriation
    - amount: 34229000
      financial_year: 2017-18
      phase: Main appropriation
    - amount: null
      financial_year: 2016-17
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2016-17
      phase: Final Appropriation
    - amount: null
      financial_year: 2016-17
      phase: Audit Outcome
    - amount: null
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2017-18
      phase: Final Appropriation
    - amount: null
      financial_year: 2017-18
      phase: Audit Outcome
    - amount: null
      financial_year: 2018-19
      phase: Main appropriation
    - amount: null
      financial_year: 2018-19
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2018-19
      phase: Final Appropriation
    - amount: null
      financial_year: 2018-19
      phase: Audit Outcome
    - amount: null
      financial_year: 2019-20
      phase: Main appropriation
    - amount: null
      financial_year: 2019-20
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2019-20
      phase: Final Appropriation
    - amount: null
      financial_year: 2019-20
      phase: Audit Outcome
    name: BIODIVERSITY MANAGEMENT
  - items:
    - amount: 61308000
      financial_year: 2016-17
      phase: Main appropriation
    - amount: 65019000
      financial_year: 2017-18
      phase: Main appropriation
    - amount: null
      financial_year: 2016-17
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2016-17
      phase: Final Appropriation
    - amount: null
      financial_year: 2016-17
      phase: Audit Outcome
    - amount: null
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2017-18
      phase: Final Appropriation
    - amount: null
      financial_year: 2017-18
      phase: Audit Outcome
    - amount: null
      financial_year: 2018-19
      phase: Main appropriation
    - amount: null
      financial_year: 2018-19
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2018-19
      phase: Final Appropriation
    - amount: null
      financial_year: 2018-19
      phase: Audit Outcome
    - amount: null
      financial_year: 2019-20
      phase: Main appropriation
    - amount: null
      financial_year: 2019-20
      phase: Adjusted appropriation
    - amount: null
      financial_year: 2019-20
      phase: Final Appropriation
    - amount: null
      financial_year: 2019-20
      phase: Audit Outcome
    name: ADMINISTRATION
contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
department_adjusted_budget: null
department_budget: null
description: 'Northern Cape department: Environment and Nature Conservation budget
  data for the 2019-20 financial year from National Treasury in partnership with IMALI
  YETHU.'
economic_classification_by_programme: null
expenditure_over_time: null
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2018-19
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2019-20/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2019-20
  is_selected: true
government:
  name: Northern Cape
  slug: northern-cape
government_functions: []
intro: ''
is_vote_primary: true
name: Environment and Nature Conservation
programme_by_economic_classification: null
programmes:
  programme_budgets: []
selected_financial_year: 2019-20
selected_tab: departments
slug: environment-and-nature-conservation
sphere:
  name: provincial
  slug: provincial
subprogramme_by_programme: null
title: Environment and Nature Conservation budget 2019-20  - vulekamali
vote_number: 13
vote_primary:
  name: Environment and Nature Conservation
  slug: environment-and-nature-conservation
  url_path: /2019-20/provincial/northern-cape/departments/environment-and-nature-conservation
website_url: null
