financial_years:
- closest_match:
    is_exact_match: true
    name: Economic Development, Environmental Affairs and Tourism
    organisational_unit: department
    url_path: /2015-16/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Economic Development, Environmental Affairs and Tourism
    organisational_unit: department
    url_path: /2016-17/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2016-17
  is_selected: true
- closest_match:
    is_exact_match: true
    name: Economic Development, Environmental Affairs and Tourism
    organisational_unit: department
    url_path: /2017-18/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2017-18
  is_selected: false
government:
  name: Eastern Cape
name: Economic Development, Environmental Affairs and Tourism
vote_number: 9
