contributed_datasets: null
description: 'Eastern Cape department: Economic Development, Environmental Affairs
  and Tourism budget data for the 2016-17 financial year from National Treasury in
  partnership with IMALI YETHU.'
expenditure_over_time:
  base_financial_year: 2017-18
  nominal:
  - amount: 807407000
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 1353816000
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 1134358000
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 1241921000
    financial_year: 2015-16
    phase: Adjusted appropriation
  - amount: 1147490000
    financial_year: 2016-17
    phase: Main appropriation
  - amount: 1310328000
    financial_year: 2017-18
    phase: Medium Term Estimates
  - amount: 1386857000
    financial_year: 2018-19
    phase: Medium Term Estimates
  real:
  - amount: 1058123298
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 1676671425
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 1330049071
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 1384625594
    financial_year: 2015-16
    phase: Adjusted appropriation
  - amount: 1203577011
    financial_year: 2016-17
    phase: Main appropriation
  - amount: 1310328000
    financial_year: 2017-18
    phase: Medium Term Estimates
  - amount: 1314660893
    financial_year: 2018-19
    phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2016-17
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2018-19
  is_selected: false
government:
  name: Eastern Cape
  slug: eastern-cape
government_functions: []
intro: "## vision\n\nsustainable development underpinned by economic growth and sound\
  \ enviromental management\r\n\r\n\r\n\n\n## mission \n\nto lead economic enviromental\
  \ management in the easter cape\r\n\r\n\r\n\n\n## core fucntion and responsibilities\n\
  \nthe core function of the department are summarised as follows\r\n\r\n* to drive\
  \ economic growth and development in easter cape\r\n\r\n* to develop and promote\
  \ the provisional tourism sector\r\n\r\n* to provided consumer protection services,\
  \ gambling and betting regulations , trade inspection and\r\nregulate the liqour\
  \ industry; and\r\n\r\n* to develop regularly framework and monitor the implementation\
  \ of policy for the protection \r\nbiodiversity and the enviroment in the province\r\
  \n\r\n"
is_vote_primary: true
name: Economic Development, Environmental Affairs and Tourism
programmes:
- name: Administration
  total_budget: 213366000
- name: Economic Development  and Tourism
  total_budget: 627725000
- name: Environmental  Affairs
  total_budget: 306399000
selected_financial_year: 2016-17
selected_tab: departments
slug: economic-development-environmental-affairs-and-tourism
sphere:
  name: Provincial
  slug: provincial
title: Economic Development, Environmental Affairs and Tourism budget 2016-17  - vulekamali
treasury_datasets:
  'EPRE for Vote 09 : Economic Development, Environmental Affairs and Tourism':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/a84b303e-28ab-4573-8922-3cb6aae14704/resource/b0679cd8-7bce-4f30-b82f-41b546109b15/download/ec-eco-dev-environment-and-tourism.xlsm
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2016/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/EC/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/EC
        - Vote 09 - Eco Dev, Environ Affairs and Tourism.pdf
vote_number: 9
vote_primary:
  name: Economic Development, Environmental Affairs and Tourism
  slug: economic-development-environmental-affairs-and-tourism
  url_path: /2016-17/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
