#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
description: 'Eastern Cape department: Economic Development, Environmental Affairs
  and Tourism budget data for the 2016-17 financial year from National Treasury in
  partnership with IMALI YETHU.'
economic_classification_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2016-17
  programmes:
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 113788000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 85295000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 11310000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Households
        total_budget: 2973000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Administration
    type: programme
  - items:
    - items:
      - name: Goods and services
        total_budget: 76342000
        type: economic_classification_2
      - name: Compensation of employees
        total_budget: 44202000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Buildings and other fixed structures
        total_budget: 129500000
        type: economic_classification_2
      - name: Machinery and equipment
        total_budget: 700000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Departmental agencies and accounts
        total_budget: 339235000
        type: economic_classification_2
      - name: Public corporations and private enterprises
        total_budget: 34026000
        type: economic_classification_2
      - name: Higher education institutions
        total_budget: 3220000
        type: economic_classification_2
      - name: Provinces and municipalities
        total_budget: 500000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Economic Development  and Tourism
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 79983000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 17270000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 640000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Departmental agencies and accounts
        total_budget: 196205000
        type: economic_classification_2
      - name: Provinces and municipalities
        total_budget: 11001000
        type: economic_classification_2
      - name: Non-profit institutions
        total_budget: 1300000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Environmental  Affairs
    type: programme
expenditure_over_time:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2016-17
  expenditure:
    base_financial_year: 2017-18
    nominal:
    - amount: 807407000
      financial_year: 2012-13
      phase: Audited Outcome
    - amount: 1353816000
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 1134358000
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 1241921000
      financial_year: 2015-16
      phase: Adjusted appropriation
    - amount: 1147490000
      financial_year: 2016-17
      phase: Main appropriation
    - amount: 1310328000
      financial_year: 2017-18
      phase: Medium Term Estimates
    - amount: 1386857000
      financial_year: 2018-19
      phase: Medium Term Estimates
    real:
    - amount: 1058123298
      financial_year: 2012-13
      phase: Audited Outcome
    - amount: 1676671425
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 1330049071
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 1384625594
      financial_year: 2015-16
      phase: Adjusted appropriation
    - amount: 1203577011
      financial_year: 2016-17
      phase: Main appropriation
    - amount: 1310328000
      financial_year: 2017-18
      phase: Medium Term Estimates
    - amount: 1314660893
      financial_year: 2018-19
      phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2016-17
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2018-19
  is_selected: false
government:
  name: Eastern Cape
  slug: eastern-cape
government_functions: []
intro: "## vision\n\nsustainable development underpinned by economic growth and sound\
  \ enviromental management\r\n\r\n\r\n\n\n## mission \n\nto lead economic enviromental\
  \ management in the easter cape\r\n\r\n\r\n\n\n## core fucntion and responsibilities\n\
  \nthe core function of the department are summarised as follows\r\n\r\n* to drive\
  \ economic growth and development in easter cape\r\n\r\n* to develop and promote\
  \ the provisional tourism sector\r\n\r\n* to provided consumer protection services,\
  \ gambling and betting regulations , trade inspection and\r\nregulate the liqour\
  \ industry; and\r\n\r\n* to develop regularly framework and monitor the implementation\
  \ of policy for the protection \r\nbiodiversity and the enviroment in the province\r\
  \n\r\n"
is_vote_primary: true
name: Economic Development, Environmental Affairs and Tourism
programme_by_economic_classification:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2016-17
  econ_classes:
  - items:
    - name: Administration
      total_budget: 113788000
      type: programme
    - name: Environmental  Affairs
      total_budget: 79983000
      type: programme
    - name: Economic Development  and Tourism
      total_budget: 44202000
      type: programme
    name: Current payments - Compensation of employees
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 85295000
      type: programme
    - name: Economic Development  and Tourism
      total_budget: 76342000
      type: programme
    - name: Environmental  Affairs
      total_budget: 17270000
      type: programme
    name: Current payments - Goods and services
    type: economic_classification_1_and_2
  - items:
    - name: Economic Development  and Tourism
      total_budget: 129500000
      type: programme
    name: Payments for capital assets - Buildings and other fixed structures
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 11310000
      type: programme
    - name: Economic Development  and Tourism
      total_budget: 700000
      type: programme
    - name: Environmental  Affairs
      total_budget: 640000
      type: programme
    name: Payments for capital assets - Machinery and equipment
    type: economic_classification_1_and_2
  - items:
    - name: Economic Development  and Tourism
      total_budget: 339235000
      type: programme
    - name: Environmental  Affairs
      total_budget: 196205000
      type: programme
    name: Transfers and subsidies - Departmental agencies and accounts
    type: economic_classification_1_and_2
  - items:
    - name: Economic Development  and Tourism
      total_budget: 3220000
      type: programme
    name: Transfers and subsidies - Higher education institutions
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 2973000
      type: programme
    name: Transfers and subsidies - Households
    type: economic_classification_1_and_2
  - items:
    - name: Environmental  Affairs
      total_budget: 1300000
      type: programme
    name: Transfers and subsidies - Non-profit institutions
    type: economic_classification_1_and_2
  - items:
    - name: Environmental  Affairs
      total_budget: 11001000
      type: programme
    - name: Economic Development  and Tourism
      total_budget: 500000
      type: programme
    name: Transfers and subsidies - Provinces and municipalities
    type: economic_classification_1_and_2
  - items:
    - name: Economic Development  and Tourism
      total_budget: 34026000
      type: programme
    name: Transfers and subsidies - Public corporations and private enterprises
    type: economic_classification_1_and_2
programmes:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2016-17
  programme_budgets:
  - name: Administration
    total_budget: 213366000
  - name: Economic Development  and Tourism
    total_budget: 627725000
  - name: Environmental  Affairs
    total_budget: 306399000
selected_financial_year: 2016-17
selected_tab: departments
slug: economic-development-environmental-affairs-and-tourism
sphere:
  name: Provincial
  slug: provincial
subprogramme_by_programme: null
title: Economic Development, Environmental Affairs and Tourism budget 2016-17  - vulekamali
treasury_datasets:
  'EPRE for Vote 09 : Economic Development, Environmental Affairs and Tourism':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/a84b303e-28ab-4573-8922-3cb6aae14704/resource/b0679cd8-7bce-4f30-b82f-41b546109b15/download/ec-eco-dev-environment-and-tourism.xlsm
    - format: PDF
      url: https://data.vulekamali.gov.za/dataset/a84b303e-28ab-4573-8922-3cb6aae14704/resource/0b96adaf-9392-4b06-86de-bc95956ffef0/download/ec-vote-09-eco-dev-environ-affairs-and-tourism.pdf
vote_number: 9
vote_primary:
  name: Economic Development, Environmental Affairs and Tourism
  slug: economic-development-environmental-affairs-and-tourism
  url_path: /2016-17/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
