#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
description: 'KwaZulu-Natal department: Economic Development, Tourism and Environmental
  Affairs budget data for the 2016-17 financial year from National Treasury in partnership
  with IMALI YETHU.'
expenditure_over_time:
  base_financial_year: 2017-18
  nominal:
  - amount: 2421869000
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 3311354000
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 2955803000
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 2997119000
    financial_year: 2015-16
    phase: Adjusted appropriation
  - amount: 2702992000
    financial_year: 2016-17
    phase: Main appropriation
  - amount: 2844613000
    financial_year: 2017-18
    phase: Medium Term Estimates
  - amount: 3022744000
    financial_year: 2018-19
    phase: Medium Term Estimates
  real:
  - amount: 3173908591
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 4101039308
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 3465716321
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 3341506970
    financial_year: 2015-16
    phase: Adjusted appropriation
  - amount: 2835108831
    financial_year: 2016-17
    phase: Main appropriation
  - amount: 2844613000
    financial_year: 2017-18
    phase: Medium Term Estimates
  - amount: 2865387943
    financial_year: 2018-19
    phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
  id: 2016-17
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
  id: 2018-19
  is_selected: false
government:
  name: KwaZulu-Natal
  slug: kwazulu-natal
government_functions: []
intro: "## Vision\r\n\r\nThe vision of the Department of Economic Development, Tourism\
  \ and Environmental Affairs (DEDTEA) is: Leading the attainment of inclusive and\
  \ sustainable economic growth for job creation.\r\n\r\n\r\n\r\n\r\n## Mission statement\r\
  \n\r\nThe department?s mission is to: Provide leadership and facilitate integrated\
  \ economic planning, be a catalyst for economic transformation and sustainable development,\
  \ implement strategies that drive economic growth and promote sound environmental\
  \ management, create a conducive environment for trade, investment and tourism and\
  \ monitor and enforce sound business and consumer regulations\r\n\r\n\r\n\r\n\r\n\
  ## Core functions\r\n\r\nThe department?s core functions are summarised as follows:\r\
  \n\r\n* To drive the economic development strategies of the province.\r\n\r\n* To\
  \ facilitate strategies to enhance the competitiveness of priority sectors of the\
  \ economy, in line with\r\nthe industrial development strategy.\r\n\r\n* To promote\
  \ the development of small business and social enterprises.\r\n\r\n* To promote\
  \ and facilitate economic empowerment programmes.\r\n\r\n* To manage the Enterprise\
  \ Development and Growth Funds.\r\n\r\n* To provide an effective and efficient consumer\
  \ protection service.\r\n\r\n* To ensure effective and prudent business regulation\
  \ in the province.\r\n\r\n* To provide effective and efficient environmental management.\r\
  \n\r\n* To provide conservation services."
is_vote_primary: true
name: Economic Development, Tourism and Environmental Affairs
programmes:
- name: Administration
  total_budget: 226179000
- name: Integrated Economic Development Services
  total_budget: 414345000
- name: Trade and Sector Development
  total_budget: 769338000
- name: Business Regulation and Governance
  total_budget: 111786000
- name: Economic Planning
  total_budget: 38525000
- name: Tourism
  total_budget: 285323000
- name: Environmental Affairs
  total_budget: 857496000
selected_financial_year: 2016-17
selected_tab: departments
slug: economic-development-tourism-and-environmental-affairs
sphere:
  name: Provincial
  slug: provincial
title: Economic Development, Tourism and Environmental Affairs budget 2016-17  - vulekamali
treasury_datasets:
  'EPRE for Vote 04 : Economic Development, Tourism and Environmental Affairs':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/593de25b-b3a6-4ffa-b854-9606b9fd06dd/resource/4d812f4d-439c-487e-a633-f92776a319ef/download/kzn-eco-dev-tou-and-envir.xlsm
    - format: PDF
      url: https://data.vulekamali.gov.za/dataset/593de25b-b3a6-4ffa-b854-9606b9fd06dd/resource/7aaddec5-abe0-4281-b90c-fe4c532e9311/download/kzn-vote-04-economic-development-and-tourism.pdf
vote_number: 4
vote_primary:
  name: Economic Development, Tourism and Environmental Affairs
  slug: economic-development-tourism-and-environmental-affairs
  url_path: /2016-17/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
