financial_years:
- closest_match:
    is_exact_match: true
    name: Environmental Affairs and Development Planning
    organisational_unit: department
    slug: environmental-affairs-and-development-planning
    url_path: /2015-16/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2015-16
  is_selected: true
- closest_match:
    is_exact_match: true
    name: Environmental Affairs and Development Planning
    organisational_unit: department
    slug: environmental-affairs-and-development-planning
    url_path: /2016-17/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Environmental Affairs and Development Planning
    organisational_unit: department
    slug: environmental-affairs-and-development-planning
    url_path: /2017-18/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2017-18
  is_selected: false
government:
  name: Western Cape
  slug: western-cape
intro: "## Vision\n\nA resilient, sustainable, quality and inclusive living environment.\r\
  \n\r\n\n\n## Mission\n\nTo promote a resilient, sustainable, quality and inclusive\
  \ living environment in support of human well-being.\r\n\r\n\n\n## Core functions\n\
  \nThe core functions of the Department of Environmental Affairs and Development\
  \ Planning are to promote sustainable economic development and social equity by\
  \ upholding the environmental integrity of the Western Cape. This will be achieved\
  \ through:\r\n\r\n* Ensuring cohesive and integrated environmental governance in\
  \ the Western Cape;\r\n\r\n* Strategically advance the environmental sustainability\
  \ of the Western Cape;\r\n\r\n* Sustain the environmental quality of the Western\
  \ Cape; and\r\n\r\n* Ensure integrated environmental and land management in the\
  \ Western Cape."
name: Environmental Affairs and Development Planning
programmes:
- name: Administration
- name: Environmental Policy, Planning and Coordination
- name: Compliance and Enforcement
- name: Environmental Quality Management
- name: Biodiversity Management
- name: Environmental Empowerment Services
- name: Development Planning
resources:
  'EPRE for Vote 09 : Environmental Affairs and Development Planning':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSX
      url: https://treasurydata.openup.org.za/dataset/9ede39c4-d52e-4d18-8416-3aeee6b82ec6/resource/ba980123-2e03-4f5f-987d-151ea8bcf79a/download/wc-environ-affairs-and-dev-planning.xlsx
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2015/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/WC/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/WC
        - Vote 09 - Environ Affaris and Dev Planning.pdf
selected_financial_year: 2015-16
slug: environmental-affairs-and-development-planning
sphere:
  name: Provincial
  slug: provincial
vote_number: 9
