#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

adjusted_budget_summary: null
budget_actual: null
budget_actual_programmes: null
contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
department_adjusted_budget: null
department_budget:
  document:
    description: ''
    format: PDF
    name: 'Vote 09 : Environmental Affairs and Development Planning'
    url: https://data.vulekamali.gov.za/dataset/9ede39c4-d52e-4d18-8416-3aeee6b82ec6/resource/ffa323f2-5cb4-46c7-887a-8278214b476e/download/wc-vote-09-environ-affaris-and-dev-planning.pdf
  name: 'Western Cape Department: Environmental Affairs and Development Planning 2015-16'
  tables:
    description: ''
    format: XLSX
    name: 'Vote 09 : Environmental Affairs and Development Planning'
    url: https://data.vulekamali.gov.za/dataset/9ede39c4-d52e-4d18-8416-3aeee6b82ec6/resource/ba980123-2e03-4f5f-987d-151ea8bcf79a/download/wc-environ-affairs-and-dev-planning.xlsx
description: 'Western Cape department: Environmental Affairs and Development Planning
  budget data for the 2015-16 financial year from National Treasury in partnership
  with IMALI YETHU.'
economic_classification_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2015-16
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2015-16/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2015%257Cgovernment.government%253A%2522Western%2BCape%2522%257Cdepartment.department%253A%2522Environmental%2BAffairs%2Band%2BDevelopment%2BPlanning%2522%26drilldown%3Dbudget_phase.budget_phase%257Cdepartment.department%257Ceconomic_classification_1.economic_classification_1%257Ceconomic_classification_2.economic_classification_2%257Ceconomic_classification_3.economic_classification_3%257Ceconomic_classification_4.economic_classification_4%257Cfinancial_year.financial_year%257Cgovernment.government%257Cprogramme_number.programme%257Cprogramme_number.programme_number%26pagesize%3D10000
  programmes:
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 44090000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 11368000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 2572000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Households
        total_budget: 60000
        type: economic_classification_2
      - name: Departmental agencies and accounts
        total_budget: 6000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Administration
    type: programme
  - items:
    - items:
      - name: Goods and services
        total_budget: 8918000
        type: economic_classification_2
      - name: Compensation of employees
        total_budget: 6792000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 37000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Departmental agencies and accounts
        total_budget: 243974000
        type: economic_classification_2
      - name: Non-profit institutions
        total_budget: 1400000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Biodiversity Management
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 18917000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 3857000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 136000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    name: Compliance and Enforcement
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 42509000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 11635000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 236000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Provinces and municipalities
        total_budget: 5500000
        type: economic_classification_2
      - name: Non-profit institutions
        total_budget: 5000000
        type: economic_classification_2
      - name: Departmental agencies and accounts
        total_budget: 2000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Development Planning
    type: programme
  - items:
    - items:
      - name: Goods and services
        total_budget: 1334000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Provinces and municipalities
        total_budget: 500000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Environmental Empowerment Services
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 14139000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 5546000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 92000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    name: Environmental Policy, Planning and Coordination
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 53305000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 20581000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 468000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Departmental agencies and accounts
        total_budget: 2000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Environmental Quality Management
    type: programme
expenditure_over_time:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2015-16
  expenditure:
    base_financial_year: 2017-18
    nominal:
    - amount: 348467000
      financial_year: 2011-12
      phase: Audited Outcome
    - amount: 376880000
      financial_year: 2012-13
      phase: Audited Outcome
    - amount: 412199000
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 482162000
      financial_year: 2014-15
      phase: Adjusted appropriation
    - amount: 502976000
      financial_year: 2015-16
      phase: Main appropriation
    - amount: 537907000
      financial_year: 2016-17
      phase: Medium Term Estimates
    - amount: 588326000
      financial_year: 2017-18
      phase: Medium Term Estimates
    real:
    - amount: 481982076
      financial_year: 2011-12
      phase: Audited Outcome
    - amount: 493908906
      financial_year: 2012-13
      phase: Audited Outcome
    - amount: 510499421
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 565341030
      financial_year: 2014-15
      phase: Adjusted appropriation
    - amount: 560771130
      financial_year: 2015-16
      phase: Main appropriation
    - amount: 564198816
      financial_year: 2016-17
      phase: Medium Term Estimates
    - amount: 588326000
      financial_year: 2017-18
      phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2015-16
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2018-19
  is_selected: false
government:
  name: Western Cape
  slug: western-cape
government_functions: []
intro: "## Vision\n\nA resilient, sustainable, quality and inclusive living environment.\r\
  \n\r\n\n\n## Mission\n\nTo promote a resilient, sustainable, quality and inclusive\
  \ living environment in support of human well-being.\r\n\r\n\n\n## Core functions\n\
  \nThe core functions of the Department of Environmental Affairs and Development\
  \ Planning are to promote sustainable economic development and social equity by\
  \ upholding the environmental integrity of the Western Cape. This will be achieved\
  \ through:\r\n\r\n* Ensuring cohesive and integrated environmental governance in\
  \ the Western Cape;\r\n\r\n* Strategically advance the environmental sustainability\
  \ of the Western Cape;\r\n\r\n* Sustain the environmental quality of the Western\
  \ Cape; and\r\n\r\n* Ensure integrated environmental and land management in the\
  \ Western Cape."
is_vote_primary: true
name: Environmental Affairs and Development Planning
programme_by_economic_classification:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2015-16
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2015-16/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2015%257Cgovernment.government%253A%2522Western%2BCape%2522%257Cdepartment.department%253A%2522Environmental%2BAffairs%2Band%2BDevelopment%2BPlanning%2522%26drilldown%3Dbudget_phase.budget_phase%257Cdepartment.department%257Ceconomic_classification_1.economic_classification_1%257Ceconomic_classification_2.economic_classification_2%257Ceconomic_classification_3.economic_classification_3%257Ceconomic_classification_4.economic_classification_4%257Cfinancial_year.financial_year%257Cgovernment.government%257Cprogramme_number.programme%257Cprogramme_number.programme_number%26pagesize%3D10000
  econ_classes:
  - items:
    - name: Environmental Quality Management
      total_budget: 53305000
      type: programme
    - name: Administration
      total_budget: 44090000
      type: programme
    - name: Development Planning
      total_budget: 42509000
      type: programme
    - name: Compliance and Enforcement
      total_budget: 18917000
      type: programme
    - name: Environmental Policy, Planning and Coordination
      total_budget: 14139000
      type: programme
    - name: Biodiversity Management
      total_budget: 6792000
      type: programme
    name: Current payments - Compensation of employees
    type: economic_classification_1_and_2
  - items:
    - name: Environmental Quality Management
      total_budget: 20581000
      type: programme
    - name: Development Planning
      total_budget: 11635000
      type: programme
    - name: Administration
      total_budget: 11368000
      type: programme
    - name: Biodiversity Management
      total_budget: 8918000
      type: programme
    - name: Environmental Policy, Planning and Coordination
      total_budget: 5546000
      type: programme
    - name: Compliance and Enforcement
      total_budget: 3857000
      type: programme
    - name: Environmental Empowerment Services
      total_budget: 1334000
      type: programme
    name: Current payments - Goods and services
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 2572000
      type: programme
    - name: Environmental Quality Management
      total_budget: 468000
      type: programme
    - name: Development Planning
      total_budget: 236000
      type: programme
    - name: Compliance and Enforcement
      total_budget: 136000
      type: programme
    - name: Environmental Policy, Planning and Coordination
      total_budget: 92000
      type: programme
    - name: Biodiversity Management
      total_budget: 37000
      type: programme
    name: Payments for capital assets - Machinery and equipment
    type: economic_classification_1_and_2
  - items:
    - name: Biodiversity Management
      total_budget: 243974000
      type: programme
    - name: Administration
      total_budget: 6000
      type: programme
    - name: Environmental Quality Management
      total_budget: 2000
      type: programme
    - name: Development Planning
      total_budget: 2000
      type: programme
    name: Transfers and subsidies - Departmental agencies and accounts
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 60000
      type: programme
    name: Transfers and subsidies - Households
    type: economic_classification_1_and_2
  - items:
    - name: Development Planning
      total_budget: 5000000
      type: programme
    - name: Biodiversity Management
      total_budget: 1400000
      type: programme
    name: Transfers and subsidies - Non-profit institutions
    type: economic_classification_1_and_2
  - items:
    - name: Development Planning
      total_budget: 5500000
      type: programme
    - name: Environmental Empowerment Services
      total_budget: 500000
      type: programme
    name: Transfers and subsidies - Provinces and municipalities
    type: economic_classification_1_and_2
programmes:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2015-16
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2015-16/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2015%257Cgovernment.government%253A%2522Western%2BCape%2522%257Cdepartment.department%253A%2522Environmental%2BAffairs%2Band%2BDevelopment%2BPlanning%2522%26drilldown%3Dbudget_phase.budget_phase%257Cdepartment.department%257Ceconomic_classification_1.economic_classification_1%257Ceconomic_classification_2.economic_classification_2%257Ceconomic_classification_3.economic_classification_3%257Ceconomic_classification_4.economic_classification_4%257Cfinancial_year.financial_year%257Cgovernment.government%257Cprogramme_number.programme%257Cprogramme_number.programme_number%26pagesize%3D10000
  programme_budgets:
  - name: Administration
    total_budget: 58096000
  - name: Environmental Policy, Planning and Coordination
    total_budget: 19777000
  - name: Compliance and Enforcement
    total_budget: 22910000
  - name: Environmental Quality Management
    total_budget: 74356000
  - name: Biodiversity Management
    total_budget: 261121000
  - name: Environmental Empowerment Services
    total_budget: 1834000
  - name: Development Planning
    total_budget: 64882000
selected_financial_year: 2015-16
selected_tab: departments
slug: environmental-affairs-and-development-planning
sphere:
  name: Provincial
  slug: provincial
subprogramme_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/epre-sub-programme-expenditure-2015-16
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aepre-sub-programme-expenditure-2015-16-v2/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2015%257Cgovernment.government%253A%2522Western%2BCape%2522%257Cdepartment.department%253A%2522Environmental%2BAffairs%2Band%2BDevelopment%2BPlanning%2522%26drilldown%3Ddepartment.department%257Cfinancial_year.financial_year%257Cgovernment.government%257Cphase.phase%257Cprogramme_number.programme%257Cprogramme_number.programme_number%257Csubprogramme.subprogramme%26pagesize%3D10000
  programmes: []
title: Environmental Affairs and Development Planning budget 2015-16  - vulekamali
vote_number: 9
vote_primary:
  name: Environmental Affairs and Development Planning
  slug: environmental-affairs-and-development-planning
  url_path: /2015-16/provincial/western-cape/departments/environmental-affairs-and-development-planning
