#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: The transparency of public funding of Basic Education in South Africa
  url_path: /datasets/contributed/the-transparency-of-public-funding-of-basic-education-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
- contributor: Centre for Child Law
  name: 'Mud to bricks: A review of school infrastructure spending and delivery'
  url_path: /datasets/contributed/mud-to-bricks-a-review-of-school-infrastructure-spending-and-delivery
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Eastern Cape Department of Health 2014/15'
  url_path: /datasets/contributed/budget-brief-eastern-cape-department-of-health-2014-15
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Eastern Cape Department of Education 2016/17'
  url_path: /datasets/contributed/budget-brief-eastern-cape-department-of-education-2016-17
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Eastern Cape Department of Human Settlements 2014/15'
  url_path: /datasets/contributed/budget-brief-eastern-cape-department-of-human-settlements-2014-15
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Department of Human Settlements, 2016/17 and 2017/18'
  url_path: /datasets/contributed/budget-brief-department-of-human-settlements
description: 'Mpumalanga department: Agriculture, Rural Development, Land and Environmental
  Affairs budget data for the 2016-17 financial year from National Treasury in partnership
  with IMALI YETHU.'
expenditure_over_time:
  base_financial_year: 2017-18
  nominal:
  - amount: 1028958000
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 1007100000
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 1004444000
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 1002624000
    financial_year: 2015-16
    phase: Adjusted appropriation
  - amount: 974133000
    financial_year: 2016-17
    phase: Main appropriation
  - amount: 1224529000
    financial_year: 2017-18
    phase: Medium Term Estimates
  - amount: 1300848000
    financial_year: 2018-19
    phase: Medium Term Estimates
  real:
  - amount: 1348470390
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 1247271263
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 1177723266
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 1117831852
    financial_year: 2015-16
    phase: Adjusted appropriation
  - amount: 1021746668
    financial_year: 2016-17
    phase: Main appropriation
  - amount: 1224529000
    financial_year: 2017-18
    phase: Medium Term Estimates
  - amount: 1233129294
    financial_year: 2018-19
    phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
  id: 2016-17
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
  id: 2018-19
  is_selected: false
government:
  name: Mpumalanga
  slug: mpumalanga
government_functions: []
intro: "## Vision\r\n\r\nVibrant, equitable, and sustainable urban and rural communities\
  \ with a united and\r\nprosperous agricultural sector.\r\n\r\n\r\n\r\n## Mission\r\
  \n\r\nTo facilitate an integrated, comprehensive & sustainable social & Agricultural\r\
  \ndevelopment in rural and urban communities through ensuring cohesion and collaboration\r\
  \nby all sectors of society.\r\n\r\n\r\n\r\n## Core functions and responsibilities\r\
  \n\r\nThe Department will continue with the implementation of the following priority\
  \ policy\r\ninitiatives in response to Outcome 7 and Outcome 10 in particular\r\n\
  \r\n* Land and agrarian reform development\r\n\r\n* Crop and Livestock production\
  \ (Integrated Food Security and Nutrition Programme\r\n(IFSNP))\r\n\r\n* Livestock\
  \ improvement strategy , and Aquaculture and fisheries strategy\r\n\r\n* The Agricultural\
  \ Risk Disaster Management Implementation Strategy\r\n\r\n* Provincial Land Care\
  \ Strategy (Integrated resource management)\r\n\r\n* Provincial Comprehensive Rural\
  \ Development Strategy\r\n\r\n* Protect and enhance our environmental assets and\
  \ natural resources\r\n\r\n* Rural Development"
is_vote_primary: true
name: Agriculture, Rural Development, Land and Environmental Affairs
programmes:
- name: Administration
  total_budget: 134005000
- name: Sustainable Resource Management
  total_budget: 80075000
- name: Farmer Support and Development
  total_budget: 359281000
- name: Veterinary Services
  total_budget: 117753000
- name: Research and Technology Development Services
  total_budget: 61825000
- name: Agricultural Economics Services
  total_budget: 9516000
- name: Structured Agricultural Education and Training
  total_budget: 17379000
- name: Rural Development Coordination
  total_budget: 101337000
- name: Environmental Affairs
  total_budget: 92962000
selected_financial_year: 2016-17
selected_tab: departments
slug: agriculture-rural-development-land-and-environmental-affairs
sphere:
  name: Provincial
  slug: provincial
title: Agriculture, Rural Development, Land and Environmental Affairs budget 2016-17  -
  vulekamali
treasury_datasets: {}
vote_number: 5
vote_primary:
  name: Agriculture, Rural Development, Land and Environmental Affairs
  slug: agriculture-rural-development-land-and-environmental-affairs
  url_path: /2016-17/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
