#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
description: 'Mpumalanga department: Agriculture, Rural Development, Land and Environmental
  Affairs budget data for the 2016-17 financial year from National Treasury in partnership
  with IMALI YETHU.'
economic_classification_by_programme:
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 93305000
    - economic_classification_2_name: Goods and services
      total_budget: 35999000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 610000
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Households
      total_budget: 3941000
    - economic_classification_2_name: Provinces and municipalities
      total_budget: 150000
  programme_name: Administration
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 7071000
    - economic_classification_2_name: Goods and services
      total_budget: 2445000
  programme_name: Agricultural Economics Services
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 73609000
    - economic_classification_2_name: Goods and services
      total_budget: 17853000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Buildings and other fixed structures
      total_budget: 1500000
  programme_name: Environmental Affairs
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 170061000
    - economic_classification_2_name: Goods and services
      total_budget: 96322000
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Households
      total_budget: 92898000
  programme_name: Farmer Support and Development
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 43827000
    - economic_classification_2_name: Goods and services
      total_budget: 7998000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Buildings and other fixed structures
      total_budget: 10000000
  programme_name: Research and Technology Development Services
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 16991000
    - economic_classification_2_name: Goods and services
      total_budget: 8346000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 5360000
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Households
      total_budget: 70640000
  programme_name: Rural Development Coordination
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 13075000
    - economic_classification_2_name: Goods and services
      total_budget: 4304000
  programme_name: Structured Agricultural Education and Training
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 46381000
    - economic_classification_2_name: Goods and services
      total_budget: 7160000
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Households
      total_budget: 26534000
  programme_name: Sustainable Resource Management
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 98911000
    - economic_classification_2_name: Goods and services
      total_budget: 15063000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Buildings and other fixed structures
      total_budget: 3500000
    - economic_classification_2_name: Machinery and equipment
      total_budget: 279000
  programme_name: Veterinary Services
expenditure_over_time:
  base_financial_year: 2017-18
  nominal:
  - amount: 1028958000
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 1007100000
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 1004444000
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 1002624000
    financial_year: 2015-16
    phase: Adjusted appropriation
  - amount: 974133000
    financial_year: 2016-17
    phase: Main appropriation
  - amount: 1224529000
    financial_year: 2017-18
    phase: Medium Term Estimates
  - amount: 1300848000
    financial_year: 2018-19
    phase: Medium Term Estimates
  real:
  - amount: 1348470390
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 1247271263
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 1177723266
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 1117831852
    financial_year: 2015-16
    phase: Adjusted appropriation
  - amount: 1021746668
    financial_year: 2016-17
    phase: Main appropriation
  - amount: 1224529000
    financial_year: 2017-18
    phase: Medium Term Estimates
  - amount: 1233129294
    financial_year: 2018-19
    phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
  id: 2016-17
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
  id: 2018-19
  is_selected: false
government:
  name: Mpumalanga
  slug: mpumalanga
government_functions: []
intro: "## Vision\r\n\r\nVibrant, equitable, and sustainable urban and rural communities\
  \ with a united and\r\nprosperous agricultural sector.\r\n\r\n\r\n\r\n## Mission\r\
  \n\r\nTo facilitate an integrated, comprehensive & sustainable social & Agricultural\r\
  \ndevelopment in rural and urban communities through ensuring cohesion and collaboration\r\
  \nby all sectors of society.\r\n\r\n\r\n\r\n## Core functions and responsibilities\r\
  \n\r\nThe Department will continue with the implementation of the following priority\
  \ policy\r\ninitiatives in response to Outcome 7 and Outcome 10 in particular\r\n\
  \r\n* Land and agrarian reform development\r\n\r\n* Crop and Livestock production\
  \ (Integrated Food Security and Nutrition Programme\r\n(IFSNP))\r\n\r\n* Livestock\
  \ improvement strategy , and Aquaculture and fisheries strategy\r\n\r\n* The Agricultural\
  \ Risk Disaster Management Implementation Strategy\r\n\r\n* Provincial Land Care\
  \ Strategy (Integrated resource management)\r\n\r\n* Provincial Comprehensive Rural\
  \ Development Strategy\r\n\r\n* Protect and enhance our environmental assets and\
  \ natural resources\r\n\r\n* Rural Development"
is_vote_primary: true
name: Agriculture, Rural Development, Land and Environmental Affairs
programmes:
- name: Administration
  total_budget: 134005000
- name: Sustainable Resource Management
  total_budget: 80075000
- name: Farmer Support and Development
  total_budget: 359281000
- name: Veterinary Services
  total_budget: 117753000
- name: Research and Technology Development Services
  total_budget: 61825000
- name: Agricultural Economics Services
  total_budget: 9516000
- name: Structured Agricultural Education and Training
  total_budget: 17379000
- name: Rural Development Coordination
  total_budget: 101337000
- name: Environmental Affairs
  total_budget: 92962000
selected_financial_year: 2016-17
selected_tab: departments
slug: agriculture-rural-development-land-and-environmental-affairs
sphere:
  name: Provincial
  slug: provincial
title: Agriculture, Rural Development, Land and Environmental Affairs budget 2016-17  -
  vulekamali
treasury_datasets:
  'EPRE for Vote 05 : Agriculture, Rural Development, Land and Environmental Affairs':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/cf28d7c2-da01-42e7-b9e1-7e565ce37ca3/resource/b2dfbb0d-e22c-4069-8a0d-af2dee154d0e/download/mpu-agric.-rural-dev.-land-and-env.-affairs.xlsm
    - format: PDF
      url: https://data.vulekamali.gov.za/dataset/cf28d7c2-da01-42e7-b9e1-7e565ce37ca3/resource/1c8b1b06-9d7f-4f1a-a81c-0c33e6c8b0d9/download/mpu-vote-05-agriculture-rural-deve-land-and-environ.pdf
vote_number: 5
vote_primary:
  name: Agriculture, Rural Development, Land and Environmental Affairs
  slug: agriculture-rural-development-land-and-environmental-affairs
  url_path: /2016-17/provincial/mpumalanga/departments/agriculture-rural-development-land-and-environmental-affairs
