financial_years:
- id: 2015-16
  is_selected: false
- id: 2016-17
  is_selected: true
- id: 2017-18
  is_selected: false
government:
  name: Mpumalanga
name: Economic Development, Environment and Tourism
vote_number: 6
