financial_years:
- closest_match:
    is_exact_match: true
    name: Economic Development, Environment and Tourism
    organisational_unit: department
    slug: economic-development-environment-and-tourism
    url_path: /2015-16/provincial/mpumalanga/departments/economic-development-environment-and-tourism
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Economic Development, Environment and Tourism
    organisational_unit: department
    slug: economic-development-environment-and-tourism
    url_path: /2016-17/provincial/mpumalanga/departments/economic-development-environment-and-tourism
  id: 2016-17
  is_selected: true
- closest_match:
    is_exact_match: true
    name: Economic Development, Environment and Tourism
    organisational_unit: department
    slug: economic-development-environment-and-tourism
    url_path: /2017-18/provincial/mpumalanga/departments/economic-development-environment-and-tourism
  id: 2017-18
  is_selected: false
government:
  name: Mpumalanga
  slug: mpumalanga
name: Economic Development, Environment and Tourism
narrative: {}
slug: economic-development-environment-and-tourism
vote_number: 6
