contributed_datasets: null
financial_years:
- closest_match:
    is_exact_match: true
    name: Economic Development, Environmental Affairs and Tourism
    organisational_unit: department
    slug: economic-development-environmental-affairs-and-tourism
    url_path: /2015-16/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2015-16
  is_selected: true
- closest_match:
    is_exact_match: true
    name: Economic Development, Environmental Affairs and Tourism
    organisational_unit: department
    slug: economic-development-environmental-affairs-and-tourism
    url_path: /2016-17/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Economic Development, Environmental Affairs and Tourism
    organisational_unit: department
    slug: economic-development-environmental-affairs-and-tourism
    url_path: /2017-18/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2017-18
  is_selected: false
government:
  name: Eastern Cape
  slug: eastern-cape
government_functions: []
intro: "## Vision\n\nA Province where economic growth and sound environmental management\
  \ underpin sustainable\r\ndevelopment.\r\n\r\n\n\n## Mission\n\nTo lead economic\
  \ and environmental management in the Eastern Cape.\r\n\r\n\n\n## Core functions\
  \ and responsibilities\n\nThe department\u2019s strategic goal is \u201CDEDEAT will\
  \ be recognised as an innovative, professional\r\norganisation, which facilitates\
  \ and regulates participation in a growing low-carbon provincial economy\u201D\r\
  \nThe core functions are summarised as follows:\r\n\r\n* To drive economic growth\
  \ and development in the Eastern Cape;\r\n\r\n* To develop and promote the provincial\
  \ tourism sector;\r\n\r\n* To provide consumer protection services, gambling and\
  \ betting regulations, trade inspections and\r\nregulate the liquor industry; and\r\
  \n\r\n* To develop regulatory frameworks and monitor the implementation of policy\
  \ for the protection of\r\nbiodiversity and the environment in the province."
name: Economic Development, Environmental Affairs and Tourism
programmes:
- name: Administration
- name: Economic Development  and Tourism
- name: Environmental  Affairs
selected_financial_year: 2015-16
slug: economic-development-environmental-affairs-and-tourism
sphere:
  name: Provincial
  slug: provincial
treasury_datasets:
  'EPRE for Vote 09 : Economic Development, Environmental Affairs and Tourism':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSX
      url: https://data.vulekamali.gov.za/dataset/8520b356-b672-410a-9ff4-e352f20defa9/resource/fe51b1f8-d6f8-47f1-ae76-7955da050228/download/ec-eco-dev-environment-and-tourism.xlsx
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2015/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/EC/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/EC
        - Vote 09 - Eco Dev, Environ Affairs and Tourism.pdf
vote_number: 9
