#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
description: 'Eastern Cape department: Economic Development, Environmental Affairs
  and Tourism budget data for the 2015-16 financial year from National Treasury in
  partnership with IMALI YETHU.'
expenditure_over_time:
  base_financial_year: 2017-18
  nominal:
  - amount: 885651000
    financial_year: 2011-12
    phase: Audited Outcome
  - amount: 807407000
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 1353816000
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 1333359000
    financial_year: 2014-15
    phase: Adjusted appropriation
  - amount: 1181858000
    financial_year: 2015-16
    phase: Main appropriation
  - amount: 1150786000
    financial_year: 2016-17
    phase: Medium Term Estimates
  - amount: 1319405000
    financial_year: 2017-18
    phase: Medium Term Estimates
  real:
  - amount: 1224988042
    financial_year: 2011-12
    phase: Audited Outcome
  - amount: 1058123298
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 1676671425
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 1563380255
    financial_year: 2014-15
    phase: Adjusted appropriation
  - amount: 1317660975
    financial_year: 2015-16
    phase: Main appropriation
  - amount: 1207034113
    financial_year: 2016-17
    phase: Medium Term Estimates
  - amount: 1319405000
    financial_year: 2017-18
    phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2015-16
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2018-19
  is_selected: false
government:
  name: Eastern Cape
  slug: eastern-cape
government_functions: []
intro: "## Vision\n\nA Province where economic growth and sound environmental management\
  \ underpin sustainable\r\ndevelopment.\r\n\r\n\n\n## Mission\n\nTo lead economic\
  \ and environmental management in the Eastern Cape.\r\n\r\n\n\n## Core functions\
  \ and responsibilities\n\nThe department\u2019s strategic goal is \u201CDEDEAT will\
  \ be recognised as an innovative, professional\r\norganisation, which facilitates\
  \ and regulates participation in a growing low-carbon provincial economy\u201D\r\
  \nThe core functions are summarised as follows:\r\n\r\n* To drive economic growth\
  \ and development in the Eastern Cape;\r\n\r\n* To develop and promote the provincial\
  \ tourism sector;\r\n\r\n* To provide consumer protection services, gambling and\
  \ betting regulations, trade inspections and\r\nregulate the liquor industry; and\r\
  \n\r\n* To develop regulatory frameworks and monitor the implementation of policy\
  \ for the protection of\r\nbiodiversity and the environment in the province."
is_vote_primary: true
name: Economic Development, Environmental Affairs and Tourism
programmes:
- name: Administration
  total_budget: 200721000
- name: Economic Development  and Tourism
  total_budget: 683551000
- name: Environmental  Affairs
  total_budget: 297586000
selected_financial_year: 2015-16
selected_tab: departments
slug: economic-development-environmental-affairs-and-tourism
sphere:
  name: Provincial
  slug: provincial
title: Economic Development, Environmental Affairs and Tourism budget 2015-16  - vulekamali
treasury_datasets:
  'EPRE for Vote 09 : Economic Development, Environmental Affairs and Tourism':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSX
      url: https://data.vulekamali.gov.za/dataset/8520b356-b672-410a-9ff4-e352f20defa9/resource/fe51b1f8-d6f8-47f1-ae76-7955da050228/download/ec-eco-dev-environment-and-tourism.xlsx
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2015/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/EC/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/EC
        - Vote 09 - Eco Dev, Environ Affairs and Tourism.pdf
vote_number: 9
vote_primary:
  name: Economic Development, Environmental Affairs and Tourism
  slug: economic-development-environmental-affairs-and-tourism
  url_path: /2015-16/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
