financial_years:
- closest_match:
    is_exact_match: true
    name: Economic Development, Environmental Affairs and Tourism
    organisational_unit: department
    slug: economic-development-environmental-affairs-and-tourism
    url_path: /2015-16/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2015-16
  is_selected: true
- closest_match:
    is_exact_match: true
    name: Economic Development, Environmental Affairs and Tourism
    organisational_unit: department
    slug: economic-development-environmental-affairs-and-tourism
    url_path: /2016-17/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Economic Development, Environmental Affairs and Tourism
    organisational_unit: department
    slug: economic-development-environmental-affairs-and-tourism
    url_path: /2017-18/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2017-18
  is_selected: false
government:
  name: Eastern Cape
  slug: eastern-cape
name: Economic Development, Environmental Affairs and Tourism
narrative: {}
resources:
  'EPRE for Vote 09 : Economic Development, Environmental Affairs and Tourism':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSX
      url: https://treasurydata.openup.org.za/dataset/8520b356-b672-410a-9ff4-e352f20defa9/resource/fe51b1f8-d6f8-47f1-ae76-7955da050228/download/ec-eco-dev-environment-and-tourism.xlsx
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2015/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/EC/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/EC
        - Vote 09 - Eco Dev, Environ Affairs and Tourism.pdf
slug: economic-development-environmental-affairs-and-tourism
vote_number: 9
