#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

adjusted_budget_summary: null
contributed_datasets:
- contributor: Centre for Child Law
  name: Adjusted Estimates of National Expenditure 2016-17
  url_path: /datasets/contributed/adjusted-estimates-of-national-expenditure-2016-17
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
department_adjusted_budget: null
department_budget:
  document:
    description: ''
    format: PDF
    name: 'Vote 09 : Economic Development, Environmental Affairs and Tourism'
    url: https://data.vulekamali.gov.za/dataset/8520b356-b672-410a-9ff4-e352f20defa9/resource/15325ee4-1880-4a11-b0bb-5a0a59b730e7/download/ec-vote-09-eco-dev-environ-affairs-and-tourism.pdf
  name: 'Eastern Cape Department: Economic Development, Environmental Affairs and
    Tourism 2015-16'
  tables:
    description: ''
    format: XLSX
    name: 'Vote 09 : Economic Development, Environmental Affairs and Tourism'
    url: https://data.vulekamali.gov.za/dataset/8520b356-b672-410a-9ff4-e352f20defa9/resource/fe51b1f8-d6f8-47f1-ae76-7955da050228/download/ec-eco-dev-environment-and-tourism.xlsx
description: 'Eastern Cape department: Economic Development, Environmental Affairs
  and Tourism budget data for the 2015-16 financial year from National Treasury in
  partnership with IMALI YETHU.'
economic_classification_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2015-16
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2015-16/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2015%257Cgovernment.government%253A%2522Eastern%2BCape%2522%257Cdepartment.department%253A%2522Economic%2BDevelopment%252C%2BEnvironmental%2BAffairs%2Band%2BTourism%2522%26drilldown%3Dbudget_phase.budget_phase%257Cdepartment.department%257Ceconomic_classification_1.economic_classification_1%257Ceconomic_classification_2.economic_classification_2%257Ceconomic_classification_3.economic_classification_3%257Ceconomic_classification_4.economic_classification_4%257Cfinancial_year.financial_year%257Cgovernment.government%257Cprogramme_number.programme%257Cprogramme_number.programme_number%26pagesize%3D10000
  programmes:
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 107193000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 80861000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 9783000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Households
        total_budget: 2884000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Administration
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 42892000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 25264000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Departmental agencies and accounts
        total_budget: 573397000
        type: economic_classification_2
      - name: Public corporations and private enterprises
        total_budget: 37064000
        type: economic_classification_2
      - name: Higher education institutions
        total_budget: 3634000
        type: economic_classification_2
      - name: Provinces and municipalities
        total_budget: 1300000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Economic Development  and Tourism
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 75447000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 17226000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Departmental agencies and accounts
        total_budget: 193081000
        type: economic_classification_2
      - name: Provinces and municipalities
        total_budget: 10832000
        type: economic_classification_2
      - name: Non-profit institutions
        total_budget: 1000000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Environmental  Affairs
    type: programme
expenditure_over_time:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2015-16
  expenditure:
    base_financial_year: 2017-18
    nominal:
    - amount: 885651000
      financial_year: 2011-12
      phase: Audited Outcome
    - amount: 807407000
      financial_year: 2012-13
      phase: Audited Outcome
    - amount: 1353816000
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 1333359000
      financial_year: 2014-15
      phase: Adjusted appropriation
    - amount: 1181858000
      financial_year: 2015-16
      phase: Main appropriation
    - amount: 1150786000
      financial_year: 2016-17
      phase: Medium Term Estimates
    - amount: 1319405000
      financial_year: 2017-18
      phase: Medium Term Estimates
    real:
    - amount: 1224988042
      financial_year: 2011-12
      phase: Audited Outcome
    - amount: 1058123298
      financial_year: 2012-13
      phase: Audited Outcome
    - amount: 1676671425
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 1563380255
      financial_year: 2014-15
      phase: Adjusted appropriation
    - amount: 1317660975
      financial_year: 2015-16
      phase: Main appropriation
    - amount: 1207034113
      financial_year: 2016-17
      phase: Medium Term Estimates
    - amount: 1319405000
      financial_year: 2017-18
      phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2015-16
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2018-19
  is_selected: false
government:
  name: Eastern Cape
  slug: eastern-cape
government_functions: []
intro: "## Vision\n\nA Province where economic growth and sound environmental management\
  \ underpin sustainable\r\ndevelopment.\r\n\r\n\n\n## Mission\n\nTo lead economic\
  \ and environmental management in the Eastern Cape.\r\n\r\n\n\n## Core functions\
  \ and responsibilities\n\nThe department\u2019s strategic goal is \u201CDEDEAT will\
  \ be recognised as an innovative, professional\r\norganisation, which facilitates\
  \ and regulates participation in a growing low-carbon provincial economy\u201D\r\
  \nThe core functions are summarised as follows:\r\n\r\n* To drive economic growth\
  \ and development in the Eastern Cape;\r\n\r\n* To develop and promote the provincial\
  \ tourism sector;\r\n\r\n* To provide consumer protection services, gambling and\
  \ betting regulations, trade inspections and\r\nregulate the liquor industry; and\r\
  \n\r\n* To develop regulatory frameworks and monitor the implementation of policy\
  \ for the protection of\r\nbiodiversity and the environment in the province."
is_vote_primary: true
name: Economic Development, Environmental Affairs and Tourism
programme_by_economic_classification:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2015-16
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2015-16/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2015%257Cgovernment.government%253A%2522Eastern%2BCape%2522%257Cdepartment.department%253A%2522Economic%2BDevelopment%252C%2BEnvironmental%2BAffairs%2Band%2BTourism%2522%26drilldown%3Dbudget_phase.budget_phase%257Cdepartment.department%257Ceconomic_classification_1.economic_classification_1%257Ceconomic_classification_2.economic_classification_2%257Ceconomic_classification_3.economic_classification_3%257Ceconomic_classification_4.economic_classification_4%257Cfinancial_year.financial_year%257Cgovernment.government%257Cprogramme_number.programme%257Cprogramme_number.programme_number%26pagesize%3D10000
  econ_classes:
  - items:
    - name: Administration
      total_budget: 107193000
      type: programme
    - name: Environmental  Affairs
      total_budget: 75447000
      type: programme
    - name: Economic Development  and Tourism
      total_budget: 42892000
      type: programme
    name: Current payments - Compensation of employees
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 80861000
      type: programme
    - name: Economic Development  and Tourism
      total_budget: 25264000
      type: programme
    - name: Environmental  Affairs
      total_budget: 17226000
      type: programme
    name: Current payments - Goods and services
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 9783000
      type: programme
    name: Payments for capital assets - Machinery and equipment
    type: economic_classification_1_and_2
  - items:
    - name: Economic Development  and Tourism
      total_budget: 573397000
      type: programme
    - name: Environmental  Affairs
      total_budget: 193081000
      type: programme
    name: Transfers and subsidies - Departmental agencies and accounts
    type: economic_classification_1_and_2
  - items:
    - name: Economic Development  and Tourism
      total_budget: 3634000
      type: programme
    name: Transfers and subsidies - Higher education institutions
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 2884000
      type: programme
    name: Transfers and subsidies - Households
    type: economic_classification_1_and_2
  - items:
    - name: Environmental  Affairs
      total_budget: 1000000
      type: programme
    name: Transfers and subsidies - Non-profit institutions
    type: economic_classification_1_and_2
  - items:
    - name: Environmental  Affairs
      total_budget: 10832000
      type: programme
    - name: Economic Development  and Tourism
      total_budget: 1300000
      type: programme
    name: Transfers and subsidies - Provinces and municipalities
    type: economic_classification_1_and_2
  - items:
    - name: Economic Development  and Tourism
      total_budget: 37064000
      type: programme
    name: Transfers and subsidies - Public corporations and private enterprises
    type: economic_classification_1_and_2
programmes:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2015-16
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2015-16/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2015%257Cgovernment.government%253A%2522Eastern%2BCape%2522%257Cdepartment.department%253A%2522Economic%2BDevelopment%252C%2BEnvironmental%2BAffairs%2Band%2BTourism%2522%26drilldown%3Dbudget_phase.budget_phase%257Cdepartment.department%257Ceconomic_classification_1.economic_classification_1%257Ceconomic_classification_2.economic_classification_2%257Ceconomic_classification_3.economic_classification_3%257Ceconomic_classification_4.economic_classification_4%257Cfinancial_year.financial_year%257Cgovernment.government%257Cprogramme_number.programme%257Cprogramme_number.programme_number%26pagesize%3D10000
  programme_budgets:
  - name: Administration
    total_budget: 200721000
  - name: Economic Development  and Tourism
    total_budget: 683551000
  - name: Environmental  Affairs
    total_budget: 297586000
selected_financial_year: 2015-16
selected_tab: departments
slug: economic-development-environmental-affairs-and-tourism
sphere:
  name: Provincial
  slug: provincial
subprogramme_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/epre-sub-programme-expenditure-2015-16
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aepre-sub-programme-expenditure-2015-16-v2/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2015%257Cgovernment.government%253A%2522Eastern%2BCape%2522%257Cdepartment.department%253A%2522Economic%2BDevelopment%252C%2BEnvironmental%2BAffairs%2Band%2BTourism%2522%26drilldown%3Ddepartment.department%257Cfinancial_year.financial_year%257Cgovernment.government%257Cphase.phase%257Cprogramme_number.programme%257Cprogramme_number.programme_number%257Csubprogramme.subprogramme%26pagesize%3D10000
  programmes: []
title: Economic Development, Environmental Affairs and Tourism budget 2015-16  - vulekamali
vote_number: 9
vote_primary:
  name: Economic Development, Environmental Affairs and Tourism
  slug: economic-development-environmental-affairs-and-tourism
  url_path: /2015-16/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
