financial_years:
- closest_match:
    is_exact_match: true
    name: Economic Development, Tourism and Environmental Affairs
    organisational_unit: department
    slug: economic-development-tourism-and-environmental-affairs
    url_path: /2015-16/provincial/free-state/departments/economic-development-tourism-and-environmental-affairs
  id: 2015-16
  is_selected: true
- closest_match:
    is_exact_match: false
    name: Free State
    organisational_unit: government
    slug: free-state
    url_path: /2016-17/provincial/free-state
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: false
    name: Free State
    organisational_unit: government
    slug: free-state
    url_path: /2017-18/provincial/free-state
  id: 2017-18
  is_selected: false
government:
  name: Free State
  slug: free-state
intro: "## Vision\n\nA prosperous Free State that enhances the quality of life through\
  \ integrated and sustainable economic growth\r\n\r\n\n\n## Mission\n\nTo provide\
  \ sound economic and environmental management systems that ensures economic development\
  \ and poverty reduction in the Free State.\r\n\r\n\r\n\r\n"
name: Economic Development, Tourism and Environmental Affairs
programmes: []
resources:
  'EPRE for Vote 03 : Economic Development, Tourism and Environmental Affairs':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSX
      url: https://treasurydata.openup.org.za/dataset/ac327673-5469-47a8-bfcf-3f67dc4ff13c/resource/2d47397c-4c59-4a4d-ab05-ea53592a1251/download/fs-eco-and-small-bus-dev-tourism-and-env-affairs.xlsx
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2015/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/FS/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/FS
        - Vote 03 - Eco Dev, Tourism and Env Affairs.pdf
selected_financial_year: 2015-16
slug: economic-development-tourism-and-environmental-affairs
sphere:
  name: Provincial
  slug: provincial
vote_number: 3
