contributed_datasets: null
financial_years:
- closest_match:
    is_exact_match: true
    name: Economic and Small Business Development,  Tourism and Environmental Affairs
    organisational_unit: department
    slug: economic-and-small-business-development-tourism-and-environmental-affairs
    url_path: /2015-16/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2015-16
  is_selected: true
- closest_match:
    is_exact_match: true
    name: Economic and Small Business Development, Tourism and Environmental Affairs
    organisational_unit: department
    slug: economic-and-small-business-development-tourism-and-environmental-affairs
    url_path: /2016-17/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Economic and Small Business Development, Tourism and Environmental Affairs
    organisational_unit: department
    slug: economic-and-small-business-development-tourism-and-environmental-affairs
    url_path: /2017-18/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: false
    name: Free State
    organisational_unit: government
    slug: free-state
    url_path: /2018-19/provincial/free-state
  id: 2018-19
  is_selected: false
government:
  name: Free State
  slug: free-state
government_functions: []
intro: "## Vision\r\n\r\nA prosperous Free State that enhances the quality of life\
  \ through integrated and sustainable economic growth\r\n\r\n\r\n\r\n## Mission\r\
  \n\r\nTo provide sound economic and environmental management systems that ensures\
  \ economic development and poverty reduction in the Free State."
is_vote_primary: true
name: Economic and Small Business Development,  Tourism and Environmental Affairs
organisational_unit: department
programmes:
- name: Administration
  total_budget: 137393000.0
- name: Environmental Affairs
  total_budget: 154403000.0
- name: Economic and Small Business Development
  total_budget: 124645000.0
- name: Tourism
  total_budget: 55738000.0
selected_financial_year: 2015-16
slug: economic-and-small-business-development-tourism-and-environmental-affairs
sphere:
  name: Provincial
  slug: provincial
treasury_datasets:
  'EPRE for Vote 03 : Economic Development, Tourism and Environmental Affairs':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSX
      url: https://data.vulekamali.gov.za/dataset/ac327673-5469-47a8-bfcf-3f67dc4ff13c/resource/2d47397c-4c59-4a4d-ab05-ea53592a1251/download/fs-eco-and-small-bus-dev-tourism-and-env-affairs.xlsx
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2015/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/FS/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/FS
        - Vote 03 - Eco Dev, Tourism and Env Affairs.pdf
vote_number: 3
vote_primary:
  name: Economic and Small Business Development,  Tourism and Environmental Affairs
  slug: economic-and-small-business-development-tourism-and-environmental-affairs
  url_path: /2015-16/provincial/free-state/departments/economic-and-small-business-development-tourism-and-environmental-affairs
