contributed_datasets: []
financial_years:
- closest_match:
    is_exact_match: true
    name: Environmental Affairs
    organisational_unit: department
    slug: environmental-affairs
    url_path: /2015-16/national/departments/environmental-affairs
  id: 2015-16
  is_selected: true
- closest_match:
    is_exact_match: true
    name: Environmental Affairs
    organisational_unit: department
    slug: environmental-affairs
    url_path: /2016-17/national/departments/environmental-affairs
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Environmental Affairs
    organisational_unit: department
    slug: environmental-affairs
    url_path: /2017-18/national/departments/environmental-affairs
  id: 2017-18
  is_selected: false
government:
  name: South Africa
  slug: south-africa
government_functions: []
intro: "## Vote purpose\n\n_Lead South Africa\u2019s environmental sector to achieve\
  \ sustainable development\ntowards a better quality of life  \nfor all._\n\n\n\n\
  ## Mandate\n\nThe Department of Environmental Affairs is mandated to give effect\
  \ to the\nright of citizens to an environment that is not harmful to their health\
  \ or\nwellbeing, and to have the environment protected for the benefit of present\n\
  and future generations. To this end, the department provides leadership in\nenvironmental\
  \ management, conservation and protection towards sustainability\nfor the benefit\
  \ of South Africans and the global community.\n\nThis mandate is derived from the\
  \ following legislation:\n\n  * the National Environmental Management Act\_(1998),\
  \ which provides for issue specific legislation on: biodiversity and heritage resources;\
  \ oceans and coasts; climate change and air quality management; and waste and chemicals\
  \ management\n\n  * the National Environmental Management Amendment Act\_(2004),\
  \ which streamlines the process of regulating and administering the environmental\
  \ impact assessment process\n\n  * the National Environmental Management: Protected\
  \ Areas Amendment Act\_(2009), which provides for the assignment of national parks,\
  \ special parks and heritage sites to South Africa in terms of the World Heritage\
  \ Convention Act\_(1999)\n\n  * the National Environmental Management: Biodiversity\
  \ Act\_(2004), which significantly reforms South Africa\u2019s laws regulating biodiversity\n\
  \n  * the National Environmental Management: Air Quality and Atmospheric Act\_(2004),\
  \ which reforms the law regulating air quality in order to protect the environment\
  \ by providing reasonable measures for preventing pollution and ecological degradation,\
  \ securing ecologically sustainable development, and provides for national norms\
  \ and standards regulating air quality monitoring\n\n  * the National Environmental\
  \ Management: Waste Act\_(2008), which reforms the law regulating waste management\
  \ in order to protect health and the environment by providing reasonable measures\
  \ for the prevention of pollution\n\n  * the National Environmental Management:\
  \ Integrated Coastal Management Act\_(2008), which promotes the conservation of\
  \ the coastal environment and ensures sustainable development practices and the\
  \ use of natural resources.\n\n"
name: Environmental Affairs
programmes:
- name: Administration
- name: Legal, Authorisations and Compliance
- name: Oceans and Coasts
- name: Climate Change and Air Quality
- name: Biodiversity and Conservation
- name: Environmental Programmes
- name: Chemicals and Waste Management
selected_financial_year: 2015-16
slug: environmental-affairs
sphere:
  name: National
  slug: national
treasury_datasets:
  ENE for Vote 27 - Environmental Affairs:
    description: The Estimates of National Expenditure (ENE) sets out the detailed
      spending plans of each government department for the coming year.
    formats:
    - format: PDF
      url: http://www.treasury.gov.za/documents/national%20budget/2015/enebooklets/Vote%2027%20Environmental%20Affairs.pdf
    - format: XLS
      url: http://www.treasury.gov.za/documents/national%20budget/2015/enebooklets/ENE15Chap%20tab-Vote27.xls
vote_number: 27
