financial_years:
- closest_match:
    is_exact_match: true
    name: Environmental Affairs
    organisational_unit: department
    slug: environmental-affairs
    url_path: /2015-16/national/departments/environmental-affairs
  id: 2015-16
  is_selected: true
- closest_match:
    is_exact_match: true
    name: Environmental Affairs
    organisational_unit: department
    slug: environmental-affairs
    url_path: /2016-17/national/departments/environmental-affairs
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Environmental Affairs
    organisational_unit: department
    slug: environmental-affairs
    url_path: /2017-18/national/departments/environmental-affairs
  id: 2017-18
  is_selected: false
government:
  name: South Africa
  slug: south-africa
name: Environmental Affairs
slug: environmental-affairs
vote_number: 27
