#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
description: 'National department: Environmental Affairs budget data for the 2015-16
  financial year from National Treasury in partnership with IMALI YETHU.'
economic_classification_by_programme:
  dataset_detail_page: /datasets/estimates-of-national-expenditure/estimates-of-national-expenditure-2015-16
  programmes:
  - items:
    - items:
      - name: Payments for capital assets
        total_budget: 118799000.0
        type: economic_classification_2
      name: Capital
      type: economic_classification_1
    - items:
      - name: Current payments
        total_budget: 579250000.0
        type: economic_classification_2
      - name: Transfers and subsidies
        total_budget: 16000000.0
        type: economic_classification_2
      name: Current
      type: economic_classification_1
    name: Administration
    type: programme
  - items:
    - items:
      - name: Transfers and subsidies
        total_budget: 31381000.0
        type: economic_classification_2
      - name: Payments for capital assets
        total_budget: 683000.0
        type: economic_classification_2
      name: Capital
      type: economic_classification_1
    - items:
      - name: Transfers and subsidies
        total_budget: 512858000.0
        type: economic_classification_2
      - name: Current payments
        total_budget: 110678000.0
        type: economic_classification_2
      name: Current
      type: economic_classification_1
    name: Biodiversity and Conservation
    type: programme
  - items:
    - items:
      - name: Payments for capital assets
        total_budget: 572000.0
        type: economic_classification_2
      name: Capital
      type: economic_classification_1
    - items:
      - name: Current payments
        total_budget: 67177000.0
        type: economic_classification_2
      - name: Transfers and subsidies
        total_budget: 11532000.0
        type: economic_classification_2
      name: Current
      type: economic_classification_1
    name: Chemicals and Waste Management
    type: programme
  - items:
    - items:
      - name: Payments for capital assets
        total_budget: 1113000.0
        type: economic_classification_2
      name: Capital
      type: economic_classification_1
    - items:
      - name: Transfers and subsidies
        total_budget: 161823000.0
        type: economic_classification_2
      - name: Current payments
        total_budget: 77213000.0
        type: economic_classification_2
      name: Current
      type: economic_classification_1
    name: Climate Change and Air Quality
    type: programme
  - items:
    - items:
      - name: Transfers and subsidies
        total_budget: 491708000.0
        type: economic_classification_2
      - name: Payments for capital assets
        total_budget: 22196000.0
        type: economic_classification_2
      name: Capital
      type: economic_classification_1
    - items:
      - name: Transfers and subsidies
        total_budget: 2437471000.0
        type: economic_classification_2
      - name: Current payments
        total_budget: 695489000.0
        type: economic_classification_2
      name: Current
      type: economic_classification_1
    name: Environmental Programmes
    type: programme
  - items:
    - items:
      - name: Payments for capital assets
        total_budget: 917000.0
        type: economic_classification_2
      name: Capital
      type: economic_classification_1
    - items:
      - name: Current payments
        total_budget: 126600000.0
        type: economic_classification_2
      name: Current
      type: economic_classification_1
    name: Legal, Authorisations and Compliance
    type: programme
  - items:
    - items:
      - name: Payments for capital assets
        total_budget: 13822000.0
        type: economic_classification_2
      name: Capital
      type: economic_classification_1
    - items:
      - name: Current payments
        total_budget: 470707000.0
        type: economic_classification_2
      name: Current
      type: economic_classification_1
    name: Oceans and Coasts
    type: programme
expenditure_over_time:
  dataset_detail_page: /datasets/estimates-of-national-expenditure/estimates-of-national-expenditure-2015-16
  expenditure:
    base_financial_year: 2017-18
    nominal:
    - amount: 4131499000.0
      financial_year: 2011-12
      phase: Audited Outcome
    - amount: 4942661000.0
      financial_year: 2012-13
      phase: Audited Outcome
    - amount: 5200307000.0
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 5680386000.0
      financial_year: 2014-15
      phase: Adjusted appropriation
    - amount: 5947989000.0
      financial_year: 2015-16
      phase: Main appropriation
    - amount: 6467479000.0
      financial_year: 2016-17
      phase: Medium Term Estimates
    - amount: 6537923000.0
      financial_year: 2017-18
      phase: Medium Term Estimates
    real:
    - amount: 5714482196
      financial_year: 2011-12
      phase: Audited Outcome
    - amount: 6477457786
      financial_year: 2012-13
      phase: Audited Outcome
    - amount: 6440466173
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 6660324275
      financial_year: 2014-15
      phase: Adjusted appropriation
    - amount: 6631450638
      financial_year: 2015-16
      phase: Main appropriation
    - amount: 6783596411
      financial_year: 2016-17
      phase: Medium Term Estimates
    - amount: 6537923000
      financial_year: 2017-18
      phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/national/departments/environmental-affairs
  id: 2015-16
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2016-17/national/departments/environmental-affairs
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/national/departments/environmental-affairs
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/national/departments/environmental-affairs
  id: 2018-19
  is_selected: false
government:
  name: South Africa
  slug: south-africa
government_functions: []
intro: "## Vote purpose\n\n_Lead South Africa\u2019s environmental sector to achieve\
  \ sustainable development\ntowards a better quality of life  \nfor all._\n\n\n\n\
  ## Mandate\n\nThe Department of Environmental Affairs is mandated to give effect\
  \ to the\nright of citizens to an environment that is not harmful to their health\
  \ or\nwellbeing, and to have the environment protected for the benefit of present\n\
  and future generations. To this end, the department provides leadership in\nenvironmental\
  \ management, conservation and protection towards sustainability\nfor the benefit\
  \ of South Africans and the global community.\n\nThis mandate is derived from the\
  \ following legislation:\n\n  * the National Environmental Management Act\_(1998),\
  \ which provides for issue specific legislation on: biodiversity and heritage resources;\
  \ oceans and coasts; climate change and air quality management; and waste and chemicals\
  \ management\n\n  * the National Environmental Management Amendment Act\_(2004),\
  \ which streamlines the process of regulating and administering the environmental\
  \ impact assessment process\n\n  * the National Environmental Management: Protected\
  \ Areas Amendment Act\_(2009), which provides for the assignment of national parks,\
  \ special parks and heritage sites to South Africa in terms of the World Heritage\
  \ Convention Act\_(1999)\n\n  * the National Environmental Management: Biodiversity\
  \ Act\_(2004), which significantly reforms South Africa\u2019s laws regulating biodiversity\n\
  \n  * the National Environmental Management: Air Quality and Atmospheric Act\_(2004),\
  \ which reforms the law regulating air quality in order to protect the environment\
  \ by providing reasonable measures for preventing pollution and ecological degradation,\
  \ securing ecologically sustainable development, and provides for national norms\
  \ and standards regulating air quality monitoring\n\n  * the National Environmental\
  \ Management: Waste Act\_(2008), which reforms the law regulating waste management\
  \ in order to protect health and the environment by providing reasonable measures\
  \ for the prevention of pollution\n\n  * the National Environmental Management:\
  \ Integrated Coastal Management Act\_(2008), which promotes the conservation of\
  \ the coastal environment and ensures sustainable development practices and the\
  \ use of natural resources.\n\n"
is_vote_primary: true
name: Environmental Affairs
programme_by_economic_classification:
  dataset_detail_page: /datasets/estimates-of-national-expenditure/estimates-of-national-expenditure-2015-16
  econ_classes:
  - items:
    - name: Administration
      total_budget: 118799000.0
      type: programme
    - name: Environmental Programmes
      total_budget: 22196000.0
      type: programme
    - name: Oceans and Coasts
      total_budget: 13822000.0
      type: programme
    - name: Climate Change and Air Quality
      total_budget: 1113000.0
      type: programme
    - name: Legal, Authorisations and Compliance
      total_budget: 917000.0
      type: programme
    - name: Biodiversity and Conservation
      total_budget: 683000.0
      type: programme
    - name: Chemicals and Waste Management
      total_budget: 572000.0
      type: programme
    name: Capital - Payments for capital assets
    type: economic_classification_1_and_2
  - items:
    - name: Environmental Programmes
      total_budget: 491708000.0
      type: programme
    - name: Biodiversity and Conservation
      total_budget: 31381000.0
      type: programme
    name: Capital - Transfers and subsidies
    type: economic_classification_1_and_2
  - items:
    - name: Environmental Programmes
      total_budget: 695489000.0
      type: programme
    - name: Administration
      total_budget: 579250000.0
      type: programme
    - name: Oceans and Coasts
      total_budget: 470707000.0
      type: programme
    - name: Legal, Authorisations and Compliance
      total_budget: 126600000.0
      type: programme
    - name: Biodiversity and Conservation
      total_budget: 110678000.0
      type: programme
    - name: Climate Change and Air Quality
      total_budget: 77213000.0
      type: programme
    - name: Chemicals and Waste Management
      total_budget: 67177000.0
      type: programme
    name: Current - Current payments
    type: economic_classification_1_and_2
  - items:
    - name: Environmental Programmes
      total_budget: 2437471000.0
      type: programme
    - name: Biodiversity and Conservation
      total_budget: 512858000.0
      type: programme
    - name: Climate Change and Air Quality
      total_budget: 161823000.0
      type: programme
    - name: Administration
      total_budget: 16000000.0
      type: programme
    - name: Chemicals and Waste Management
      total_budget: 11532000.0
      type: programme
    name: Current - Transfers and subsidies
    type: economic_classification_1_and_2
programmes:
  dataset_detail_page: /datasets/estimates-of-national-expenditure/estimates-of-national-expenditure-2015-16
  programme_budgets:
  - name: Administration
    total_budget: 714049000.0
  - name: Legal, Authorisations and Compliance
    total_budget: 127517000.0
  - name: Oceans and Coasts
    total_budget: 484529000.0
  - name: Climate Change and Air Quality
    total_budget: 240149000.0
  - name: Biodiversity and Conservation
    total_budget: 655600000.0
  - name: Environmental Programmes
    total_budget: 3646864000.0
  - name: Chemicals and Waste Management
    total_budget: 79281000.0
selected_financial_year: 2015-16
selected_tab: departments
slug: environmental-affairs
sphere:
  name: National
  slug: national
title: Environmental Affairs budget 2015-16  - vulekamali
treasury_datasets:
  ENE for Vote 27 - Environmental Affairs:
    description: The Estimates of National Expenditure (ENE) sets out the detailed
      spending plans of each government department for the coming year.
    formats:
    - format: PDF
      url: https://data.vulekamali.gov.za/dataset/nat-dept-environmental-affairs-2015-16/resource/a48b6d51-32e2-44ac-8818-b5440b8759ec/download/vote-27-environmental-affairs.pdf
    - format: XLS
      url: https://data.vulekamali.gov.za/dataset/nat-dept-environmental-affairs-2015-16/resource/cb9eabf3-7002-419b-9bc5-d837dded43dc/download/ene15chap-tab-vote27.xls
vote_number: 27
vote_primary:
  name: Environmental Affairs
  slug: environmental-affairs
  url_path: /2015-16/national/departments/environmental-affairs
