contributed_datasets: null
financial_years:
- closest_match:
    is_exact_match: true
    name: Environmental Affairs and Development Planning
    organisational_unit: department
    slug: environmental-affairs-and-development-planning
    url_path: /2015-16/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Environmental Affairs and Development Planning
    organisational_unit: department
    slug: environmental-affairs-and-development-planning
    url_path: /2016-17/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2016-17
  is_selected: true
- closest_match:
    is_exact_match: true
    name: Environmental Affairs and Development Planning
    organisational_unit: department
    slug: environmental-affairs-and-development-planning
    url_path: /2017-18/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: false
    name: Western Cape
    organisational_unit: government
    slug: western-cape
    url_path: /2018-19/provincial/western-cape
  id: 2018-19
  is_selected: false
government:
  name: Western Cape
  slug: western-cape
government_functions: []
intro: "## Vision\n\nA resilient, sustainable, quality and inclusive living environment.\r\
  \n\r\n\n\n## Mission\n\nTo promote a resilient, sustainable, quality and inclusive\
  \ living environment in support of human well-being.\r\n\r\n\n\n## Core functions\
  \ and responsibilities\n\nThe core functions of the Department of Environmental\
  \ Affairs and Development Planning are to promote\r\nsustainable economic development\
  \ and social equity by upholding the environmental integrity of the\r\nWestern Cape.\
  \ This will be achieved through:\r\n\r\n* Ensuring cohesive and integrated environmental\
  \ governance in the Western Cape;\r\n\r\n* Strategically advancing the environmental\
  \ sustainability of the Western Cape;\r\n\r\n* Sustaining the environmental quality\
  \ of the Western Cape; and\r\n\r\n* Ensuring integrated environmental and land management\
  \ in the Western Cape."
is_vote_primary: true
name: Environmental Affairs and Development Planning
organisational_unit: department
programmes:
- name: Administration
  total_budget: 60138000.0
- name: Environmental Policy, Planning and Coordination
  total_budget: 18181000.0
- name: Compliance and Enforcement
  total_budget: 23396000.0
- name: Environmental Quality Management
  total_budget: 85185000.0
- name: Biodiversity Management
  total_budget: 277033000.0
- name: Environmental Empowerment Services
  total_budget: 2066000.0
- name: Development Planning
  total_budget: 84965000.0
selected_financial_year: 2016-17
slug: environmental-affairs-and-development-planning
sphere:
  name: Provincial
  slug: provincial
treasury_datasets:
  'EPRE for Vote 09 : Environmental Affairs and Development Planning':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/640e7dab-469f-45ad-b680-178780aff6f8/resource/ea76734f-6ec4-43cb-9fb1-025294414f4d/download/wc-environ.-affairs-and-dev-planning.xlsm
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2016/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/WC/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/WC
        - Vote 09 - Environmental Affairs and Development Planning.pdf
vote_number: 9
vote_primary:
  name: Environmental Affairs and Development Planning
  slug: environmental-affairs-and-development-planning
  url_path: /2016-17/provincial/western-cape/departments/environmental-affairs-and-development-planning
