#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

adjusted_budget_summary: null
contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
department_adjusted_budget: null
department_budget:
  document:
    description: ''
    format: PDF
    name: 'Vote 09 : Environmental Affairs and Development Planning'
    url: https://data.vulekamali.gov.za/dataset/640e7dab-469f-45ad-b680-178780aff6f8/resource/e3a776de-4f91-4245-8abd-1493bd692913/download/wc-vote-09-environmental-affairs-and-development-planning.pdf
  name: 'Western Cape Department: Environmental Affairs and Development Planning 2016-17'
  tables: null
description: 'Western Cape department: Environmental Affairs and Development Planning
  budget data for the 2016-17 financial year from National Treasury in partnership
  with IMALI YETHU.'
economic_classification_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2016-17
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2016-17/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2016%257Cgovernment.government%253A%2522Western%2BCape%2522%257Cdepartment.department%253A%2522Environmental%2BAffairs%2Band%2BDevelopment%2BPlanning%2522%26drilldown%3Dbudget_phase.budget_phase%257Cdepartment.department%257Ceconomic_classification_1.economic_classification_1%257Ceconomic_classification_2.economic_classification_2%257Ceconomic_classification_3.economic_classification_3%257Ceconomic_classification_4.economic_classification_4%257Cfinancial_year.financial_year%257Cgovernment.government%257Cprogramme_number.programme%257Cprogramme_number.programme_number%26pagesize%3D10000
  programmes:
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 47405000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 9713000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 2984000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Households
        total_budget: 31000
        type: economic_classification_2
      - name: Departmental agencies and accounts
        total_budget: 5000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Administration
    type: programme
  - items:
    - items:
      - name: Goods and services
        total_budget: 7415000
        type: economic_classification_2
      - name: Compensation of employees
        total_budget: 7068000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 33000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Departmental agencies and accounts
        total_budget: 261717000
        type: economic_classification_2
      - name: Non-profit institutions
        total_budget: 800000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Biodiversity Management
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 19583000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 3624000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 189000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    name: Compliance and Enforcement
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 44886000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 8998000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 180000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Provinces and municipalities
        total_budget: 23900000
        type: economic_classification_2
      - name: Non-profit institutions
        total_budget: 7000000
        type: economic_classification_2
      - name: Departmental agencies and accounts
        total_budget: 1000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Development Planning
    type: programme
  - items:
    - items:
      - name: Goods and services
        total_budget: 1566000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Provinces and municipalities
        total_budget: 500000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Environmental Empowerment Services
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 13174000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 4949000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 58000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    name: Environmental Policy, Planning and Coordination
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 60509000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 23853000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 821000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Departmental agencies and accounts
        total_budget: 2000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Environmental Quality Management
    type: programme
expenditure_over_time:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2016-17
  expenditure:
    base_financial_year: 2017-18
    nominal:
    - amount: 376880000
      financial_year: 2012-13
      phase: Audited Outcome
    - amount: 412199000
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 457181000
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 509476000
      financial_year: 2015-16
      phase: Adjusted appropriation
    - amount: 550964000
      financial_year: 2016-17
      phase: Main appropriation
    - amount: 591528000
      financial_year: 2017-18
      phase: Medium Term Estimates
    - amount: 582535000
      financial_year: 2018-19
      phase: Medium Term Estimates
    real:
    - amount: 493908906
      financial_year: 2012-13
      phase: Audited Outcome
    - amount: 510499421
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 536050492
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 568018021
      financial_year: 2015-16
      phase: Adjusted appropriation
    - amount: 577894016
      financial_year: 2016-17
      phase: Main appropriation
    - amount: 591528000
      financial_year: 2017-18
      phase: Medium Term Estimates
    - amount: 552209768
      financial_year: 2018-19
      phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2016-17
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2018-19
  is_selected: false
government:
  name: Western Cape
  slug: western-cape
government_functions: []
intro: "## Vision\n\nA resilient, sustainable, quality and inclusive living environment.\r\
  \n\r\n\n\n## Mission\n\nTo promote a resilient, sustainable, quality and inclusive\
  \ living environment in support of human well-being.\r\n\r\n\n\n## Core functions\
  \ and responsibilities\n\nThe core functions of the Department of Environmental\
  \ Affairs and Development Planning are to promote\r\nsustainable economic development\
  \ and social equity by upholding the environmental integrity of the\r\nWestern Cape.\
  \ This will be achieved through:\r\n\r\n* Ensuring cohesive and integrated environmental\
  \ governance in the Western Cape;\r\n\r\n* Strategically advancing the environmental\
  \ sustainability of the Western Cape;\r\n\r\n* Sustaining the environmental quality\
  \ of the Western Cape; and\r\n\r\n* Ensuring integrated environmental and land management\
  \ in the Western Cape."
is_vote_primary: true
name: Environmental Affairs and Development Planning
programme_by_economic_classification:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2016-17
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2016-17/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2016%257Cgovernment.government%253A%2522Western%2BCape%2522%257Cdepartment.department%253A%2522Environmental%2BAffairs%2Band%2BDevelopment%2BPlanning%2522%26drilldown%3Dbudget_phase.budget_phase%257Cdepartment.department%257Ceconomic_classification_1.economic_classification_1%257Ceconomic_classification_2.economic_classification_2%257Ceconomic_classification_3.economic_classification_3%257Ceconomic_classification_4.economic_classification_4%257Cfinancial_year.financial_year%257Cgovernment.government%257Cprogramme_number.programme%257Cprogramme_number.programme_number%26pagesize%3D10000
  econ_classes:
  - items:
    - name: Environmental Quality Management
      total_budget: 60509000
      type: programme
    - name: Administration
      total_budget: 47405000
      type: programme
    - name: Development Planning
      total_budget: 44886000
      type: programme
    - name: Compliance and Enforcement
      total_budget: 19583000
      type: programme
    - name: Environmental Policy, Planning and Coordination
      total_budget: 13174000
      type: programme
    - name: Biodiversity Management
      total_budget: 7068000
      type: programme
    name: Current payments - Compensation of employees
    type: economic_classification_1_and_2
  - items:
    - name: Environmental Quality Management
      total_budget: 23853000
      type: programme
    - name: Administration
      total_budget: 9713000
      type: programme
    - name: Development Planning
      total_budget: 8998000
      type: programme
    - name: Biodiversity Management
      total_budget: 7415000
      type: programme
    - name: Environmental Policy, Planning and Coordination
      total_budget: 4949000
      type: programme
    - name: Compliance and Enforcement
      total_budget: 3624000
      type: programme
    - name: Environmental Empowerment Services
      total_budget: 1566000
      type: programme
    name: Current payments - Goods and services
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 2984000
      type: programme
    - name: Environmental Quality Management
      total_budget: 821000
      type: programme
    - name: Compliance and Enforcement
      total_budget: 189000
      type: programme
    - name: Development Planning
      total_budget: 180000
      type: programme
    - name: Environmental Policy, Planning and Coordination
      total_budget: 58000
      type: programme
    - name: Biodiversity Management
      total_budget: 33000
      type: programme
    name: Payments for capital assets - Machinery and equipment
    type: economic_classification_1_and_2
  - items:
    - name: Biodiversity Management
      total_budget: 261717000
      type: programme
    - name: Administration
      total_budget: 5000
      type: programme
    - name: Environmental Quality Management
      total_budget: 2000
      type: programme
    - name: Development Planning
      total_budget: 1000
      type: programme
    name: Transfers and subsidies - Departmental agencies and accounts
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 31000
      type: programme
    name: Transfers and subsidies - Households
    type: economic_classification_1_and_2
  - items:
    - name: Development Planning
      total_budget: 7000000
      type: programme
    - name: Biodiversity Management
      total_budget: 800000
      type: programme
    name: Transfers and subsidies - Non-profit institutions
    type: economic_classification_1_and_2
  - items:
    - name: Development Planning
      total_budget: 23900000
      type: programme
    - name: Environmental Empowerment Services
      total_budget: 500000
      type: programme
    name: Transfers and subsidies - Provinces and municipalities
    type: economic_classification_1_and_2
programmes:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2016-17
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2016-17/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2016%257Cgovernment.government%253A%2522Western%2BCape%2522%257Cdepartment.department%253A%2522Environmental%2BAffairs%2Band%2BDevelopment%2BPlanning%2522%26drilldown%3Dbudget_phase.budget_phase%257Cdepartment.department%257Ceconomic_classification_1.economic_classification_1%257Ceconomic_classification_2.economic_classification_2%257Ceconomic_classification_3.economic_classification_3%257Ceconomic_classification_4.economic_classification_4%257Cfinancial_year.financial_year%257Cgovernment.government%257Cprogramme_number.programme%257Cprogramme_number.programme_number%26pagesize%3D10000
  programme_budgets:
  - name: Administration
    total_budget: 60138000
  - name: Environmental Policy, Planning and Coordination
    total_budget: 18181000
  - name: Compliance and Enforcement
    total_budget: 23396000
  - name: Environmental Quality Management
    total_budget: 85185000
  - name: Biodiversity Management
    total_budget: 277033000
  - name: Environmental Empowerment Services
    total_budget: 2066000
  - name: Development Planning
    total_budget: 84965000
selected_financial_year: 2016-17
selected_tab: departments
slug: environmental-affairs-and-development-planning
sphere:
  name: Provincial
  slug: provincial
subprogramme_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/epre-sub-programme-expenditure-2016-17
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aepre-sub-programme-expenditure-2016-17-v2/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2016%257Cgovernment.government%253A%2522Western%2BCape%2522%257Cdepartment.department%253A%2522Environmental%2BAffairs%2Band%2BDevelopment%2BPlanning%2522%26drilldown%3Ddepartment.department%257Cfinancial_year.financial_year%257Cgovernment.government%257Cphase.phase%257Cprogramme_number.programme%257Cprogramme_number.programme_number%257Csubprogramme.subprogramme%26pagesize%3D10000
  programmes: []
title: Environmental Affairs and Development Planning budget 2016-17  - vulekamali
vote_number: 9
vote_primary:
  name: Environmental Affairs and Development Planning
  slug: environmental-affairs-and-development-planning
  url_path: /2016-17/provincial/western-cape/departments/environmental-affairs-and-development-planning
