#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
description: 'Eastern Cape department: Economic Development, Environmental Affairs
  And Tourism budget data for the 2018-19 financial year from National Treasury in
  partnership with IMALI YETHU.'
economic_classification_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2018-19
  programmes:
  - items:
    - items:
      - name: Compensation Of Employees
        total_budget: 123132000.0
        type: economic_classification_2
      - name: Goods And Services
        total_budget: 100883000.0
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Machinery And Equipment
        total_budget: 9669000.0
        type: economic_classification_2
      name: Payments For Capital Assets
      type: economic_classification_1
    - items:
      - name: Households
        total_budget: 1000000.0
        type: economic_classification_2
      - name: Departmental Agencies And Accounts
        total_budget: 3000.0
        type: economic_classification_2
      name: Transfers And Subsidies
      type: economic_classification_1
    name: Administration
    type: programme
  - items:
    - items:
      - name: Compensation Of Employees
        total_budget: 59930190.0
        type: economic_classification_2
      - name: Goods And Services
        total_budget: 28950998.0
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Buildings And Other Fixed Structures
        total_budget: 34524000.0
        type: economic_classification_2
      - name: Machinery And Equipment
        total_budget: 783000.0
        type: economic_classification_2
      name: Payments For Capital Assets
      type: economic_classification_1
    - items:
      - name: Departmental Agencies And Accounts
        total_budget: 443783000.0
        type: economic_classification_2
      - name: Public Corporations And Private Enterprises
        total_budget: 22801000.0
        type: economic_classification_2
      - name: Provinces And Municipalities
        total_budget: 770000.0
        type: economic_classification_2
      name: Transfers And Subsidies
      type: economic_classification_1
    name: Economic Development  And Tourism
    type: programme
  - items:
    - items:
      - name: Compensation Of Employees
        total_budget: 82789000.0
        type: economic_classification_2
      - name: Goods And Services
        total_budget: 19427000.0
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Machinery And Equipment
        total_budget: 1216000.0
        type: economic_classification_2
      name: Payments For Capital Assets
      type: economic_classification_1
    - items:
      - name: Departmental Agencies And Accounts
        total_budget: 201871000.0
        type: economic_classification_2
      - name: Provinces And Municipalities
        total_budget: 12680000.0
        type: economic_classification_2
      - name: Non-Profit Institutions
        total_budget: 1794000.0
        type: economic_classification_2
      name: Transfers And Subsidies
      type: economic_classification_1
    name: Environmental  Affairs
    type: programme
expenditure_over_time:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2018-19
  expenditure:
    base_financial_year: 2017-18
    nominal:
    - amount: 1134358000.0
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 1246351000.0
      financial_year: 2015-16
      phase: Audited Outcome
    - amount: 1039523800.0
      financial_year: 2016-17
      phase: Audited Outcome
    - amount: 1118666000.0
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: 1146006188.0
      financial_year: 2018-19
      phase: Main appropriation
    - amount: 1140580000.0
      financial_year: 2019-20
      phase: Medium Term Estimates
    - amount: 1199467000.0
      financial_year: 2020-21
      phase: Medium Term Estimates
    real:
    - amount: 1330049071
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 1389564630
      financial_year: 2015-16
      phase: Audited Outcome
    - amount: 1090333639
      financial_year: 2016-17
      phase: Audited Outcome
    - amount: 1118666000
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: 1086348137
      financial_year: 2018-19
      phase: Main appropriation
    - amount: 1026870626
      financial_year: 2019-20
      phase: Medium Term Estimates
    - amount: 1023194029
      financial_year: 2020-21
      phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2018-19
  is_selected: true
government:
  name: Eastern Cape
  slug: eastern-cape
government_functions: []
intro: ''
is_vote_primary: true
name: Economic Development, Environmental Affairs And Tourism
programme_by_economic_classification:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2018-19
  econ_classes:
  - items:
    - name: Administration
      total_budget: 123132000.0
      type: programme
    - name: Environmental  Affairs
      total_budget: 82789000.0
      type: programme
    - name: Economic Development  And Tourism
      total_budget: 59930190.0
      type: programme
    name: Current Payments - Compensation Of Employees
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 100883000.0
      type: programme
    - name: Economic Development  And Tourism
      total_budget: 28950998.0
      type: programme
    - name: Environmental  Affairs
      total_budget: 19427000.0
      type: programme
    name: Current Payments - Goods And Services
    type: economic_classification_1_and_2
  - items:
    - name: Economic Development  And Tourism
      total_budget: 34524000.0
      type: programme
    name: Payments For Capital Assets - Buildings And Other Fixed Structures
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 9669000.0
      type: programme
    - name: Environmental  Affairs
      total_budget: 1216000.0
      type: programme
    - name: Economic Development  And Tourism
      total_budget: 783000.0
      type: programme
    name: Payments For Capital Assets - Machinery And Equipment
    type: economic_classification_1_and_2
  - items:
    - name: Economic Development  And Tourism
      total_budget: 443783000.0
      type: programme
    - name: Environmental  Affairs
      total_budget: 201871000.0
      type: programme
    - name: Administration
      total_budget: 3000.0
      type: programme
    name: Transfers And Subsidies - Departmental Agencies And Accounts
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 1000000.0
      type: programme
    name: Transfers And Subsidies - Households
    type: economic_classification_1_and_2
  - items:
    - name: Environmental  Affairs
      total_budget: 1794000.0
      type: programme
    name: Transfers And Subsidies - Non-Profit Institutions
    type: economic_classification_1_and_2
  - items:
    - name: Environmental  Affairs
      total_budget: 12680000.0
      type: programme
    - name: Economic Development  And Tourism
      total_budget: 770000.0
      type: programme
    name: Transfers And Subsidies - Provinces And Municipalities
    type: economic_classification_1_and_2
  - items:
    - name: Economic Development  And Tourism
      total_budget: 22801000.0
      type: programme
    name: Transfers And Subsidies - Public Corporations And Private Enterprises
    type: economic_classification_1_and_2
programmes:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2018-19
  programme_budgets:
  - name: Administration
    total_budget: 234687000.0
  - name: Economic Development  And Tourism
    total_budget: 591542188.0
  - name: Environmental  Affairs
    total_budget: 319777000.0
  - name: Direct Charges
    total_budget: 0.0
selected_financial_year: 2018-19
selected_tab: departments
slug: economic-development-environmental-affairs-and-tourism
sphere:
  name: Provincial
  slug: provincial
title: Economic Development, Environmental Affairs And Tourism budget 2018-19  - vulekamali
treasury_datasets:
  EPRE for Vote 9 - Economic Development, Environmental Affairs And Tourism:
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: PDF
      url: https://data.vulekamali.gov.za/dataset/b9dd0243-6f14-417e-8e49-daa4078991d7/resource/78747296-4b08-4d53-8397-322b3a6a7889/download/ec-vote-09-eco-dev.-environ.-affairs-and-tourism.pdf
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/b9dd0243-6f14-417e-8e49-daa4078991d7/resource/cd8870cb-589d-4db5-a91e-f32208c835f8/download/ec-eco-dev-environment-and-tourism.xlsm
vote_number: 9
vote_primary:
  name: Economic Development, Environmental Affairs And Tourism
  slug: economic-development-environmental-affairs-and-tourism
  url_path: /2018-19/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
