#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
description: 'Limpopo department: Economic Development, Environment And Tourism budget
  data for the 2018-19 financial year from National Treasury in partnership with IMALI
  YETHU.'
economic_classification_by_programme:
- items:
  - economic_classification_1_name: Payments
    items:
    - economic_classification_2_name: Current Payments
      total_budget: 361896648.0
    - economic_classification_2_name: Payments For Capital Assets
      total_budget: 22352394.0
    - economic_classification_2_name: Transfers And Subsidies
      total_budget: 10041852.0
  programme_name: Administration
- items: []
  programme_name: Direct Charges
- items:
  - economic_classification_1_name: Payments
    items:
    - economic_classification_2_name: Transfers And Subsidies
      total_budget: 637660414.0
    - economic_classification_2_name: Current Payments
      total_budget: 109421922.0
    - economic_classification_2_name: Payments For Capital Assets
      total_budget: 2481510.0
  programme_name: Economic Development
- items:
  - economic_classification_1_name: Payments
    items:
    - economic_classification_2_name: Current Payments
      total_budget: 325622064.0
    - economic_classification_2_name: Payments For Capital Assets
      total_budget: 53528246.0
    - economic_classification_2_name: Transfers And Subsidies
      total_budget: 4579728.0
  programme_name: Environmental Affairs
- items:
  - economic_classification_1_name: Payments
    items:
    - economic_classification_2_name: Transfers And Subsidies
      total_budget: 109209000.0
    - economic_classification_2_name: Current Payments
      total_budget: 28579760.0
  programme_name: Tourism
expenditure_over_time:
  base_financial_year: 2017-18
  nominal:
  - amount: 1112393000.0
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 1153443000.0
    financial_year: 2015-16
    phase: Audited Outcome
  - amount: 1312225000.0
    financial_year: 2016-17
    phase: Audited Outcome
  - amount: 1694971000.0
    financial_year: 2017-18
    phase: Adjusted appropriation
  - amount: 1665373538.0
    financial_year: 2018-19
    phase: Main appropriation
  - amount: 1668288000.0
    financial_year: 2019-20
    phase: Medium Term Estimates
  - amount: 1752013000.0
    financial_year: 2020-21
    phase: Medium Term Estimates
  real:
  - amount: 1304294831
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 1285980911
    financial_year: 2015-16
    phase: Audited Outcome
  - amount: 1376363927
    financial_year: 2016-17
    phase: Audited Outcome
  - amount: 1694971000
    financial_year: 2017-18
    phase: Adjusted appropriation
  - amount: 1578678597
    financial_year: 2018-19
    phase: Main appropriation
  - amount: 1501969123
    financial_year: 2019-20
    phase: Medium Term Estimates
  - amount: 1494538191
    financial_year: 2020-21
    phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/limpopo/departments/economic-development-environment-and-tourism
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/limpopo/departments/economic-development-environment-and-tourism
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/limpopo/departments/economic-development-environment-and-tourism
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/limpopo/departments/economic-development-environment-and-tourism
  id: 2018-19
  is_selected: true
government:
  name: Limpopo
  slug: limpopo
government_functions: []
intro: ''
is_vote_primary: true
name: Economic Development, Environment And Tourism
programmes:
- name: Administration
  total_budget: 394290894.0
- name: Economic Development
  total_budget: 749563846.0
- name: Environmental Affairs
  total_budget: 383730038.0
- name: Tourism
  total_budget: 137788760.0
- name: Direct Charges
  total_budget: 0.0
selected_financial_year: 2018-19
selected_tab: departments
slug: economic-development-environment-and-tourism
sphere:
  name: Provincial
  slug: provincial
title: Economic Development, Environment And Tourism budget 2018-19  - vulekamali
treasury_datasets:
  EPRE for Vote 6 - Economic Development, Environment And Tourism:
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: PDF
      url: https://data.vulekamali.gov.za/dataset/95eda5cb-c3c4-4d60-ba28-b7891b4f98f2/resource/acf32d84-5c97-418f-acbd-92914dda1ce3/download/lim-vote-06-economic-dev.-environ.-tourism.pdf
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/95eda5cb-c3c4-4d60-ba28-b7891b4f98f2/resource/97a6f9c1-4132-4ddc-8006-50653fe89ef7/download/lim-eco.-dev.-env.-and-tourism.xlsm
vote_number: 6
vote_primary:
  name: Economic Development, Environment And Tourism
  slug: economic-development-environment-and-tourism
  url_path: /2018-19/provincial/limpopo/departments/economic-development-environment-and-tourism
