#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: The transparency of public funding of Basic Education in South Africa
  url_path: /datasets/contributed/the-transparency-of-public-funding-of-basic-education-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
- contributor: Centre for Child Law
  name: 'Mud to bricks: A review of school infrastructure spending and delivery'
  url_path: /datasets/contributed/mud-to-bricks-a-review-of-school-infrastructure-spending-and-delivery
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Eastern Cape Department of Health 2014/15'
  url_path: /datasets/contributed/budget-brief-eastern-cape-department-of-health-2014-15
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Eastern Cape Department of Education 2016/17'
  url_path: /datasets/contributed/budget-brief-eastern-cape-department-of-education-2016-17
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Eastern Cape Department of Human Settlements 2014/15'
  url_path: /datasets/contributed/budget-brief-eastern-cape-department-of-human-settlements-2014-15
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Department of Human Settlements, 2016/17 and 2017/18'
  url_path: /datasets/contributed/budget-brief-department-of-human-settlements
description: 'Limpopo department: Economic Development, Environment And Tourism budget
  data for the 2018-19 financial year from National Treasury in partnership with IMALI
  YETHU.'
expenditure_over_time:
  base_financial_year: 2017-18
  nominal:
  - amount: 1112393000.0
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 1153443000.0
    financial_year: 2015-16
    phase: Audited Outcome
  - amount: 1312225000.0
    financial_year: 2016-17
    phase: Audited Outcome
  - amount: 1694971000.0
    financial_year: 2017-18
    phase: Adjusted appropriation
  - amount: 1665373538.0
    financial_year: 2018-19
    phase: Main appropriation
  - amount: 1668288000.0
    financial_year: 2019-20
    phase: Medium Term Estimates
  - amount: 1752013000.0
    financial_year: 2020-21
    phase: Medium Term Estimates
  real:
  - amount: 1304294831
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 1285980911
    financial_year: 2015-16
    phase: Audited Outcome
  - amount: 1376363927
    financial_year: 2016-17
    phase: Audited Outcome
  - amount: 1694971000
    financial_year: 2017-18
    phase: Adjusted appropriation
  - amount: 1578678597
    financial_year: 2018-19
    phase: Main appropriation
  - amount: 1501969123
    financial_year: 2019-20
    phase: Medium Term Estimates
  - amount: 1494538191
    financial_year: 2020-21
    phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/limpopo/departments/economic-development-environment-and-tourism
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/limpopo/departments/economic-development-environment-and-tourism
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/limpopo/departments/economic-development-environment-and-tourism
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/limpopo/departments/economic-development-environment-and-tourism
  id: 2018-19
  is_selected: true
government:
  name: Limpopo
  slug: limpopo
government_functions: []
intro: ''
is_vote_primary: true
name: Economic Development, Environment And Tourism
programmes:
- name: Administration
  total_budget: 394290894.0
- name: Economic Development
  total_budget: 749563846.0
- name: Environmental Affairs
  total_budget: 383730038.0
- name: Tourism
  total_budget: 137788760.0
- name: Direct Charges
  total_budget: 0.0
selected_financial_year: 2018-19
selected_tab: departments
slug: economic-development-environment-and-tourism
sphere:
  name: Provincial
  slug: provincial
title: Economic Development, Environment And Tourism budget 2018-19  - vulekamali
treasury_datasets: {}
vote_number: 6
vote_primary:
  name: Economic Development, Environment And Tourism
  slug: economic-development-environment-and-tourism
  url_path: /2018-19/provincial/limpopo/departments/economic-development-environment-and-tourism
