financial_years:
- closest_match:
    is_exact_match: true
    name: Economic Development, Environment, Conservation and Tourism
    organisational_unit: department
    slug: economic-development-environment-conservation-and-tourism
    url_path: /2015-16/provincial/north-west/departments/economic-development-environment-conservation-and-tourism
  id: 2015-16
  is_selected: true
- closest_match:
    is_exact_match: false
    name: North West
    organisational_unit: government
    slug: north-west
    url_path: /2016-17/provincial/north-west
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: false
    name: North West
    organisational_unit: government
    slug: north-west
    url_path: /2017-18/provincial/north-west
  id: 2017-18
  is_selected: false
government:
  name: North West
  slug: north-west
name: Economic Development, Environment, Conservation and Tourism
narrative: {}
resources:
  'EPRE for Vote 06 : Economic Development, Environment, Conservation':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSX
      url: https://treasurydata.openup.org.za/dataset/981d7c0c-e43c-4f8c-83b1-2675a66ceefc/resource/f5d39468-8b6c-43c8-bda2-e462b85b8d71/download/nw-economy-and-enterprise-development.xlsx
  'EPRE for Vote 06 : Economic Development, Environment, Conservation and Tourism':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2015/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/NW/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/NW
        - Vote 06 - Economic Development.pdf
  'EPRE for Vote 06 : Tourism':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSX
      url: https://treasurydata.openup.org.za/dataset/981d7c0c-e43c-4f8c-83b1-2675a66ceefc/resource/2495f4b2-db67-4f90-a85f-3a5f9940db47/download/nw-tourism.xlsx
slug: economic-development-environment-conservation-and-tourism
vote_number: 6
