financial_years:
- closest_match:
    is_exact_match: true
    name: Rural, Environment and Agricultural Development
    organisational_unit: department
    slug: rural-environment-and-agricultural-development
    url_path: /2015-16/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2015-16
  is_selected: true
- closest_match:
    is_exact_match: true
    name: Rural Environment and Agricultural Development
    organisational_unit: department
    slug: rural-environment-and-agricultural-development
    url_path: /2016-17/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Rural Environment and Agricultural Development
    organisational_unit: department
    slug: rural-environment-and-agricultural-development
    url_path: /2017-18/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2017-18
  is_selected: false
government:
  name: North West
  slug: north-west
intro: "## Vision\r\n\r\nVibrant and prosperous society in harmony with our natural\
  \ resources.\r\n\r\n\r\n\r\n## Mission\r\n\r\nWorking together with our partners\
  \ to provide sustainable agricultural, environmental management and comprehensive\
  \ integrated rural development.\r\n\r\n\r\n\r\n## Core functions\r\n\r\nThe Department\
  \ focus primarily on the following mandated core functions:\r\n\r\n* Rolling out\
  \ the Comprehensive Rural Development Programme\r\n\r\n* Creating decent employment\
  \ through Inclusive Economic Growth\r\n\r\n* Protecting and Enhancing our Environmental\
  \ Assets and Natural Resources"
name: Rural, Environment and Agricultural Development
programmes: []
resources:
  'EPRE for Vote 13 : Agricultural and Rural Development':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSX
      url: https://treasurydata.openup.org.za/dataset/edcb5554-1da5-4c84-ade7-b140e6ef1ac9/resource/38e86002-accf-4660-97fd-cbbe69300b49/download/nw-rural-environ-and-agric-development.xlsx
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2015/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/NW/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/NW
        - Vote 13 - Agriculture and Rural Development.pdf
slug: rural-environment-and-agricultural-development
vote_number: 13
