#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
description: 'North West department: Rural, Environment and Agricultural Development
  budget data for the 2015-16 financial year from National Treasury in partnership
  with IMALI YETHU.'
economic_classification_by_programme:
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 128350000
    - economic_classification_2_name: Goods and services
      total_budget: 85671000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 3127000
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Households
      total_budget: 2815000
  programme_name: Administration
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 9488000
    - economic_classification_2_name: Goods and services
      total_budget: 1700000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 45000
  programme_name: Agricultural Economics Services
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 72897000
    - economic_classification_2_name: Goods and services
      total_budget: 21291000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Buildings and other fixed structures
      total_budget: 59049000
    - economic_classification_2_name: Machinery and equipment
      total_budget: 2000000
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Households
      total_budget: 158000
  programme_name: Environmental Services
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 134285000
    - economic_classification_2_name: Goods and services
      total_budget: 35701000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 5363000
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Households
      total_budget: 216308000
  programme_name: Farmer Support and Development
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 45340000
    - economic_classification_2_name: Goods and services
      total_budget: 9797000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Biological assets
      total_budget: 800000
    - economic_classification_2_name: Machinery and equipment
      total_budget: 537000
  programme_name: Research and Technology  Development Services
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 18943000
    - economic_classification_2_name: Goods and services
      total_budget: 13915000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 200000
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Households
      total_budget: 16428000
  programme_name: Rural Development Coordination
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 56039000
    - economic_classification_2_name: Goods and services
      total_budget: 27963000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 401000
  programme_name: Structured Agricultural Education and  Training
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 32256000
    - economic_classification_2_name: Goods and services
      total_budget: 7694000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 9000000
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Households
      total_budget: 7971000
  programme_name: Sustainable Resource Management
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 82807000
    - economic_classification_2_name: Goods and services
      total_budget: 12802000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 176000
  programme_name: Veterinary Services
expenditure_over_time:
  base_financial_year: 2017-18
  nominal:
  - amount: 752380000
    financial_year: 2011-12
    phase: Audited Outcome
  - amount: 843760000
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 960929000
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 1103691000
    financial_year: 2014-15
    phase: Adjusted appropriation
  - amount: 1121317000
    financial_year: 2015-16
    phase: Main appropriation
  - amount: 1151144000
    financial_year: 2016-17
    phase: Medium Term Estimates
  - amount: 1247809000
    financial_year: 2017-18
    phase: Medium Term Estimates
  real:
  - amount: 1040654279
    financial_year: 2011-12
    phase: Audited Outcome
  - amount: 1105764644
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 1190089492
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 1294091626
    financial_year: 2014-15
    phase: Adjusted appropriation
  - amount: 1250163430
    financial_year: 2015-16
    phase: Main appropriation
  - amount: 1207409611
    financial_year: 2016-17
    phase: Medium Term Estimates
  - amount: 1247809000
    financial_year: 2017-18
    phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2015-16
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/north-west/departments/rural-environment-and-agricultural-development
  id: 2018-19
  is_selected: false
government:
  name: North West
  slug: north-west
government_functions: []
intro: "## Vision\r\n\r\nVibrant and prosperous society in harmony with our natural\
  \ resources.\r\n\r\n\r\n\r\n## Mission\r\n\r\nWorking together with our partners\
  \ to provide sustainable agricultural, environmental management and comprehensive\
  \ integrated rural development.\r\n\r\n\r\n\r\n## Core functions\r\n\r\nThe Department\
  \ focus primarily on the following mandated core functions:\r\n\r\n* Rolling out\
  \ the Comprehensive Rural Development Programme\r\n\r\n* Creating decent employment\
  \ through Inclusive Economic Growth\r\n\r\n* Protecting and Enhancing our Environmental\
  \ Assets and Natural Resources"
is_vote_primary: true
name: Rural, Environment and Agricultural Development
programmes:
- name: Administration
  total_budget: 219963000
- name: Sustainable Resource Management
  total_budget: 56921000
- name: Farmer Support and Development
  total_budget: 391657000
- name: Veterinary Services
  total_budget: 95785000
- name: Research and Technology  Development Services
  total_budget: 56474000
- name: Agricultural Economics Services
  total_budget: 11233000
- name: Structured Agricultural Education and  Training
  total_budget: 84403000
- name: Rural Development Coordination
  total_budget: 49486000
- name: Environmental Services
  total_budget: 155395000
selected_financial_year: 2015-16
selected_tab: departments
slug: rural-environment-and-agricultural-development
sphere:
  name: Provincial
  slug: provincial
title: Rural, Environment and Agricultural Development budget 2015-16  - vulekamali
treasury_datasets:
  'EPRE for Vote 13 : Rural, Environment and Agricultural Development':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSX
      url: https://data.vulekamali.gov.za/dataset/edcb5554-1da5-4c84-ade7-b140e6ef1ac9/resource/38e86002-accf-4660-97fd-cbbe69300b49/download/nw-rural-environ-and-agric-development.xlsx
vote_number: 13
vote_primary:
  name: Rural, Environment and Agricultural Development
  slug: rural-environment-and-agricultural-development
  url_path: /2015-16/provincial/north-west/departments/rural-environment-and-agricultural-development
