#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
description: 'KwaZulu-Natal department: Economic Development, Tourism And Environmental
  Affairs budget data for the 2018-19 financial year from National Treasury in partnership
  with IMALI YETHU.'
economic_classification_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2018-19
  programmes:
  - items:
    - items:
      - name: Goods And Services
        total_budget: 155418000.0
        type: economic_classification_2
      - name: Compensation Of Employees
        total_budget: 111297000.0
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Machinery And Equipment
        total_budget: 3813000.0
        type: economic_classification_2
      name: Payments For Capital Assets
      type: economic_classification_1
    - items:
      - name: Households
        total_budget: 510000.0
        type: economic_classification_2
      - name: Provinces And Municipalities
        total_budget: 63000.0
        type: economic_classification_2
      - name: Departmental Agencies And Accounts
        total_budget: 9000.0
        type: economic_classification_2
      name: Transfers And Subsidies
      type: economic_classification_1
    name: Administration
    type: programme
  - items:
    - items:
      - name: Compensation Of Employees
        total_budget: 21486000.0
        type: economic_classification_2
      - name: Goods And Services
        total_budget: 18200000.0
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Machinery And Equipment
        total_budget: 270000.0
        type: economic_classification_2
      name: Payments For Capital Assets
      type: economic_classification_1
    - items:
      - name: Departmental Agencies And Accounts
        total_budget: 80189000.0
        type: economic_classification_2
      name: Transfers And Subsidies
      type: economic_classification_1
    name: Business Regulation And Governance
    type: programme
  - items:
    - items:
      - name: Compensation Of Employees
        total_budget: 18196000.0
        type: economic_classification_2
      - name: Goods And Services
        total_budget: 8398000.0
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Machinery And Equipment
        total_budget: 130000.0
        type: economic_classification_2
      name: Payments For Capital Assets
      type: economic_classification_1
    - items:
      - name: Higher Education Institutions
        total_budget: 5300000.0
        type: economic_classification_2
      - name: Public Corporations And Private Enterprises
        total_budget: 3000000.0
        type: economic_classification_2
      - name: Departmental Agencies And Accounts
        total_budget: 2500000.0
        type: economic_classification_2
      - name: Provinces And Municipalities
        total_budget: 2500000.0
        type: economic_classification_2
      name: Transfers And Subsidies
      type: economic_classification_1
    name: Economic Planning
    type: programme
  - items:
    - items:
      - name: Compensation Of Employees
        total_budget: 137867000.0
        type: economic_classification_2
      - name: Goods And Services
        total_budget: 123472000.0
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Machinery And Equipment
        total_budget: 2547000.0
        type: economic_classification_2
      name: Payments For Capital Assets
      type: economic_classification_1
    - items:
      - name: Departmental Agencies And Accounts
        total_budget: 737512000.0
        type: economic_classification_2
      - name: Non-Profit Institutions
        total_budget: 7279000.0
        type: economic_classification_2
      - name: Provinces And Municipalities
        total_budget: 1000000.0
        type: economic_classification_2
      name: Transfers And Subsidies
      type: economic_classification_1
    name: Environmental Affairs
    type: programme
  - items:
    - items:
      - name: Goods And Services
        total_budget: 141928000.0
        type: economic_classification_2
      - name: Compensation Of Employees
        total_budget: 67923000.0
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Machinery And Equipment
        total_budget: 253000.0
        type: economic_classification_2
      name: Payments For Capital Assets
      type: economic_classification_1
    - items:
      - name: Public Corporations And Private Enterprises
        total_budget: 107232000.0
        type: economic_classification_2
      - name: Non-Profit Institutions
        total_budget: 54400000.0
        type: economic_classification_2
      - name: Higher Education Institutions
        total_budget: 20688000.0
        type: economic_classification_2
      - name: Departmental Agencies And Accounts
        total_budget: 20000000.0
        type: economic_classification_2
      - name: Households
        total_budget: 6886000.0
        type: economic_classification_2
      name: Transfers And Subsidies
      type: economic_classification_1
    name: Integrated Economic Development Services
    type: programme
  - items:
    - items:
      - name: Compensation Of Employees
        total_budget: 23913000.0
        type: economic_classification_2
      - name: Goods And Services
        total_budget: 20984000.0
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Departmental Agencies And Accounts
        total_budget: 195914000.0
        type: economic_classification_2
      - name: Provinces And Municipalities
        total_budget: 5375000.0
        type: economic_classification_2
      - name: Public Corporations And Private Enterprises
        total_budget: 1600000.0
        type: economic_classification_2
      name: Transfers And Subsidies
      type: economic_classification_1
    name: Tourism
    type: programme
  - items:
    - items:
      - name: Goods And Services
        total_budget: 38715000.0
        type: economic_classification_2
      - name: Compensation Of Employees
        total_budget: 15021000.0
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Departmental Agencies And Accounts
        total_budget: 554630000.0
        type: economic_classification_2
      - name: Public Corporations And Private Enterprises
        total_budget: 139830000.0
        type: economic_classification_2
      - name: Non-Profit Institutions
        total_budget: 136898000.0
        type: economic_classification_2
      - name: Provinces And Municipalities
        total_budget: 11000000.0
        type: economic_classification_2
      - name: Higher Education Institutions
        total_budget: 5150000.0
        type: economic_classification_2
      name: Transfers And Subsidies
      type: economic_classification_1
    name: Trade And Sector Development
    type: programme
expenditure_over_time:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2018-19
  expenditure:
    base_financial_year: 2017-18
    nominal:
    - amount: 2955803000.0
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 2983585000.0
      financial_year: 2015-16
      phase: Audited Outcome
    - amount: 2596897000.0
      financial_year: 2016-17
      phase: Audited Outcome
    - amount: 2796453000.0
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: 3009296000.0
      financial_year: 2018-19
      phase: Main appropriation
    - amount: 3180694000.0
      financial_year: 2019-20
      phase: Medium Term Estimates
    - amount: 3363243000.0
      financial_year: 2020-21
      phase: Medium Term Estimates
    real:
    - amount: 3465716321
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 3326417828
      financial_year: 2015-16
      phase: Audited Outcome
    - amount: 2723828120
      financial_year: 2016-17
      phase: Audited Outcome
    - amount: 2796453000
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: 2852640011
      financial_year: 2018-19
      phase: Main appropriation
    - amount: 2863596801
      financial_year: 2019-20
      phase: Medium Term Estimates
    - amount: 2868982771
      financial_year: 2020-21
      phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
  id: 2018-19
  is_selected: true
government:
  name: KwaZulu-Natal
  slug: kwazulu-natal
government_functions: []
intro: ''
is_vote_primary: true
name: Economic Development, Tourism And Environmental Affairs
programmes:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2018-19
  programme_budgets:
  - name: Administration
    total_budget: 271110000.0
  - name: Integrated Economic Development Services
    total_budget: 419310000.0
  - name: Trade And Sector Development
    total_budget: 901244000.0
  - name: Business Regulation And Governance
    total_budget: 120145000.0
  - name: Economic Planning
    total_budget: 40024000.0
  - name: Tourism
    total_budget: 247786000.0
  - name: Environmental Affairs
    total_budget: 1009677000.0
  - name: Direct Charges
    total_budget: 0.0
selected_financial_year: 2018-19
selected_tab: departments
slug: economic-development-tourism-and-environmental-affairs
sphere:
  name: Provincial
  slug: provincial
title: Economic Development, Tourism And Environmental Affairs budget 2018-19  - vulekamali
treasury_datasets:
  EPRE for Vote 4 - Economic Development, Tourism And Environmental Affairs:
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: PDF
      url: https://data.vulekamali.gov.za/dataset/fd01308b-3467-4c88-93e0-6864d4113b84/resource/00a68255-bb31-4ea3-bc84-c6cec81e6f5c/download/kzn-vote-04-eco-dev-tourism-and-environmental-affairs.pdf
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/fd01308b-3467-4c88-93e0-6864d4113b84/resource/0812ea92-ffa8-44a5-a0cc-9302c00afee0/download/kzn-eco-dev-tou-and-envir.xlsm
vote_number: 4
vote_primary:
  name: Economic Development, Tourism And Environmental Affairs
  slug: economic-development-tourism-and-environmental-affairs
  url_path: /2018-19/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
