contributed_datasets: null
financial_years:
- closest_match:
    is_exact_match: true
    name: Environment and Nature Conservation
    organisational_unit: department
    slug: environment-and-nature-conservation
    url_path: /2015-16/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Environment and Nature Conservation
    organisational_unit: department
    slug: environment-and-nature-conservation
    url_path: /2016-17/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2016-17
  is_selected: true
- closest_match:
    is_exact_match: true
    name: Environment and Nature Conservation
    organisational_unit: department
    slug: environment-and-nature-conservation
    url_path: /2017-18/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2017-18
  is_selected: false
government:
  name: Northern Cape
  slug: northern-cape
government_functions: []
intro: "## Vision \n\nA prosperous society living sustainably with the natural environment.\
  \ \r\n\r\n\n\n## Mission \n\nConserve and protect the natural environment for the\
  \ benefit, enjoyment and welfare of present and future generations by integrating\
  \ sustainable utilization with socio-economic development.\r\n\r"
name: Environment and Nature Conservation
organisational_unit: department
programmes:
- name: ADMINISTRATION
  total_budget: 61308000.0
- name: ENVIRONMENTAL POLICY,PLANNING AND COORDINATION
  total_budget: 10411000.0
- name: COMPLIANCE AND ENFORCEMENT
  total_budget: 14011000.0
- name: ENVIRONMENTAL QUALITY MANAGEMENT
  total_budget: 14308000.0
- name: BIODIVERSITY MANAGEMENT
  total_budget: 28050000.0
- name: ENVIRONMENTAL EMPOWERMENT SERVICES
  total_budget: 12669000.0
selected_financial_year: 2016-17
slug: environment-and-nature-conservation
sphere:
  name: Provincial
  slug: provincial
treasury_datasets:
  'EPRE for Vote 13 : Environment and Nature Conservation':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/5b8e7f6d-c2ab-49f7-a98d-3f4ae62bb1f6/resource/20c96dab-ecf5-434a-8291-1ac0007cfc41/download/nc-environ.-and-nature-conservation.xlsm
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2016/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/NC/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/NC
        - Vote 13 - Environment & Nature Conservation.pdf
vote_number: 13
