#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: The transparency of public funding of Basic Education in South Africa
  url_path: /datasets/contributed/the-transparency-of-public-funding-of-basic-education-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
- contributor: Centre for Child Law
  name: 'Mud to bricks: A review of school infrastructure spending and delivery'
  url_path: /datasets/contributed/mud-to-bricks-a-review-of-school-infrastructure-spending-and-delivery
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Eastern Cape Department of Health 2014/15'
  url_path: /datasets/contributed/budget-brief-eastern-cape-department-of-health-2014-15
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Eastern Cape Department of Education 2016/17'
  url_path: /datasets/contributed/budget-brief-eastern-cape-department-of-education-2016-17
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Eastern Cape Department of Human Settlements 2014/15'
  url_path: /datasets/contributed/budget-brief-eastern-cape-department-of-human-settlements-2014-15
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Department of Human Settlements, 2016/17 and 2017/18'
  url_path: /datasets/contributed/budget-brief-department-of-human-settlements
description: 'Northern Cape department: Environment and Nature Conservation budget
  data for the 2016-17 financial year from National Treasury in partnership with IMALI
  YETHU.'
expenditure_over_time:
  base_financial_year: 2017-18
  nominal:
  - amount: 102739000
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 117641000
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 127586000
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 134178000
    financial_year: 2015-16
    phase: Adjusted appropriation
  - amount: 140757000
    financial_year: 2016-17
    phase: Main appropriation
  - amount: 145977000
    financial_year: 2017-18
    phase: Medium Term Estimates
  - amount: 154824000
    financial_year: 2018-19
    phase: Medium Term Estimates
  real:
  - amount: 134641549
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 145695798
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 149596195
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 149595902
    financial_year: 2015-16
    phase: Adjusted appropriation
  - amount: 147636920
    financial_year: 2016-17
    phase: Main appropriation
  - amount: 145977000
    financial_year: 2017-18
    phase: Medium Term Estimates
  - amount: 146764272
    financial_year: 2018-19
    phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2016-17
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2018-19
  is_selected: false
government:
  name: Northern Cape
  slug: northern-cape
government_functions: []
intro: "## Vision \n\nA prosperous society living sustainably with the natural environment.\
  \ \r\n\r\n\n\n## Mission \n\nConserve and protect the natural environment for the\
  \ benefit, enjoyment and welfare of present and future generations by integrating\
  \ sustainable utilization with socio-economic development.\r\n\r"
is_vote_primary: true
name: Environment and Nature Conservation
programmes:
- name: ADMINISTRATION
  total_budget: 61308000
- name: ENVIRONMENTAL POLICY,PLANNING AND COORDINATION
  total_budget: 10411000
- name: COMPLIANCE AND ENFORCEMENT
  total_budget: 14011000
- name: ENVIRONMENTAL QUALITY MANAGEMENT
  total_budget: 14308000
- name: BIODIVERSITY MANAGEMENT
  total_budget: 28050000
- name: ENVIRONMENTAL EMPOWERMENT SERVICES
  total_budget: 12669000
selected_financial_year: 2016-17
selected_tab: departments
slug: environment-and-nature-conservation
sphere:
  name: Provincial
  slug: provincial
title: Environment and Nature Conservation budget 2016-17  - vulekamali
treasury_datasets: {}
vote_number: 13
vote_primary:
  name: Environment and Nature Conservation
  slug: environment-and-nature-conservation
  url_path: /2016-17/provincial/northern-cape/departments/environment-and-nature-conservation
