#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
description: 'Northern Cape department: Environment and Nature Conservation budget
  data for the 2016-17 financial year from National Treasury in partnership with IMALI
  YETHU.'
economic_classification_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2016-17
  programmes:
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 39352000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 21169000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 576000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Public corporations and private enterprises
        total_budget: 211000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: ADMINISTRATION
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 23001000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 4880000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 169000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    name: BIODIVERSITY MANAGEMENT
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 11390000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 2463000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Buildings and other fixed structures
        total_budget: 95000
        type: economic_classification_2
      - name: Machinery and equipment
        total_budget: 63000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    name: COMPLIANCE AND ENFORCEMENT
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 11326000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 1187000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 156000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    name: ENVIRONMENTAL EMPOWERMENT SERVICES
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 9463000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 798000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 150000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    name: ENVIRONMENTAL POLICY,PLANNING AND COORDINATION
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 9911000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 3924000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 473000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    name: ENVIRONMENTAL QUALITY MANAGEMENT
    type: programme
expenditure_over_time:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2016-17
  expenditure:
    base_financial_year: 2017-18
    nominal:
    - amount: 102739000
      financial_year: 2012-13
      phase: Audited Outcome
    - amount: 117641000
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 127586000
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 134178000
      financial_year: 2015-16
      phase: Adjusted appropriation
    - amount: 140757000
      financial_year: 2016-17
      phase: Main appropriation
    - amount: 145977000
      financial_year: 2017-18
      phase: Medium Term Estimates
    - amount: 154824000
      financial_year: 2018-19
      phase: Medium Term Estimates
    real:
    - amount: 134641549
      financial_year: 2012-13
      phase: Audited Outcome
    - amount: 145695798
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 149596195
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 149595902
      financial_year: 2015-16
      phase: Adjusted appropriation
    - amount: 147636920
      financial_year: 2016-17
      phase: Main appropriation
    - amount: 145977000
      financial_year: 2017-18
      phase: Medium Term Estimates
    - amount: 146764272
      financial_year: 2018-19
      phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2016-17
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2018-19
  is_selected: false
government:
  name: Northern Cape
  slug: northern-cape
government_functions: []
intro: "## Vision \n\nA prosperous society living sustainably with the natural environment.\
  \ \r\n\r\n\n\n## Mission \n\nConserve and protect the natural environment for the\
  \ benefit, enjoyment and welfare of present and future generations by integrating\
  \ sustainable utilization with socio-economic development.\r\n\r"
is_vote_primary: true
name: Environment and Nature Conservation
programme_by_economic_classification:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2016-17
  econ_classes:
  - items:
    - name: ADMINISTRATION
      total_budget: 39352000
      type: programme
    - name: BIODIVERSITY MANAGEMENT
      total_budget: 23001000
      type: programme
    - name: COMPLIANCE AND ENFORCEMENT
      total_budget: 11390000
      type: programme
    - name: ENVIRONMENTAL EMPOWERMENT SERVICES
      total_budget: 11326000
      type: programme
    - name: ENVIRONMENTAL QUALITY MANAGEMENT
      total_budget: 9911000
      type: programme
    - name: ENVIRONMENTAL POLICY,PLANNING AND COORDINATION
      total_budget: 9463000
      type: programme
    name: Current payments - Compensation of employees
    type: economic_classification_1_and_2
  - items:
    - name: ADMINISTRATION
      total_budget: 21169000
      type: programme
    - name: BIODIVERSITY MANAGEMENT
      total_budget: 4880000
      type: programme
    - name: ENVIRONMENTAL QUALITY MANAGEMENT
      total_budget: 3924000
      type: programme
    - name: COMPLIANCE AND ENFORCEMENT
      total_budget: 2463000
      type: programme
    - name: ENVIRONMENTAL EMPOWERMENT SERVICES
      total_budget: 1187000
      type: programme
    - name: ENVIRONMENTAL POLICY,PLANNING AND COORDINATION
      total_budget: 798000
      type: programme
    name: Current payments - Goods and services
    type: economic_classification_1_and_2
  - items:
    - name: COMPLIANCE AND ENFORCEMENT
      total_budget: 95000
      type: programme
    name: Payments for capital assets - Buildings and other fixed structures
    type: economic_classification_1_and_2
  - items:
    - name: ADMINISTRATION
      total_budget: 576000
      type: programme
    - name: ENVIRONMENTAL QUALITY MANAGEMENT
      total_budget: 473000
      type: programme
    - name: BIODIVERSITY MANAGEMENT
      total_budget: 169000
      type: programme
    - name: ENVIRONMENTAL EMPOWERMENT SERVICES
      total_budget: 156000
      type: programme
    - name: ENVIRONMENTAL POLICY,PLANNING AND COORDINATION
      total_budget: 150000
      type: programme
    - name: COMPLIANCE AND ENFORCEMENT
      total_budget: 63000
      type: programme
    name: Payments for capital assets - Machinery and equipment
    type: economic_classification_1_and_2
  - items:
    - name: ADMINISTRATION
      total_budget: 211000
      type: programme
    name: Transfers and subsidies - Public corporations and private enterprises
    type: economic_classification_1_and_2
programmes:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2016-17
  programme_budgets:
  - name: ADMINISTRATION
    total_budget: 61308000
  - name: ENVIRONMENTAL POLICY,PLANNING AND COORDINATION
    total_budget: 10411000
  - name: COMPLIANCE AND ENFORCEMENT
    total_budget: 14011000
  - name: ENVIRONMENTAL QUALITY MANAGEMENT
    total_budget: 14308000
  - name: BIODIVERSITY MANAGEMENT
    total_budget: 28050000
  - name: ENVIRONMENTAL EMPOWERMENT SERVICES
    total_budget: 12669000
selected_financial_year: 2016-17
selected_tab: departments
slug: environment-and-nature-conservation
sphere:
  name: Provincial
  slug: provincial
title: Environment and Nature Conservation budget 2016-17  - vulekamali
treasury_datasets:
  'EPRE for Vote 13 : Environment and Nature Conservation':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/5b8e7f6d-c2ab-49f7-a98d-3f4ae62bb1f6/resource/20c96dab-ecf5-434a-8291-1ac0007cfc41/download/nc-environ.-and-nature-conservation.xlsm
    - format: PDF
      url: https://data.vulekamali.gov.za/dataset/5b8e7f6d-c2ab-49f7-a98d-3f4ae62bb1f6/resource/aa467cd1-c396-4082-917d-e382d7d05fb5/download/nc-vote-13-environment-nature-conservation.pdf
vote_number: 13
vote_primary:
  name: Environment and Nature Conservation
  slug: environment-and-nature-conservation
  url_path: /2016-17/provincial/northern-cape/departments/environment-and-nature-conservation
