financial_years:
- closest_match:
    is_exact_match: true
    name: Economic Development, Environmental Affairs and Tourism
    organisational_unit: department
    slug: economic-development-environmental-affairs-and-tourism
    url_path: /2015-16/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Economic Development, Environmental Affairs and Tourism
    organisational_unit: department
    slug: economic-development-environmental-affairs-and-tourism
    url_path: /2016-17/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Economic Development, Environmental Affairs and Tourism
    organisational_unit: department
    slug: economic-development-environmental-affairs-and-tourism
    url_path: /2017-18/provincial/eastern-cape/departments/economic-development-environmental-affairs-and-tourism
  id: 2017-18
  is_selected: true
government:
  name: Eastern Cape
  slug: eastern-cape
name: Economic Development, Environmental Affairs and Tourism
narratives:
- content: "Sustainable development underpinned by ecpnomic groowth and sound environmental\
    \ management.\r\n\r\n"
  name: Vision
- content: "To lead economic development and environmental management in the Easter\
    \ Cape.\r\n\r\n"
  name: Mission
- content: "The core functions of the department are summarised as follows:\r\n\r\n\
    * To drive economic growth and development in the Eastern Cape;\r\n\r\n* To develop\
    \ and promote the provincial tourism sector;\r\n\r\n* To provide consumer protection\
    \ services,gambling and betting regulations, trade inspection and regulate the\
    \ liquor industry;and \r\n\r\n* To develop regulatory frameworks and monitor the\
    \ implementation of policies for the protection of biodiversity and environment\
    \ in the province.\r\n\r\n"
  name: Core functions
resources:
  'EPRE for Vote 09 : Economic Development, Environmental Affairs and Tourism':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://budgetdata.openup.org.za/dataset/888106f1-f873-49c6-a5da-171901423ded/resource/11519718-119b-4341-a6aa-1481ac3d740e/download/ec-eco-dev-environment-and-tourism.xlsm
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2017/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/EC/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/EC
        - Vote 09 - Eco Dev, Environ Affairs and Tourism.pdf
slug: economic-development-environmental-affairs-and-tourism
vote_number: 9
