financial_years:
- closest_match:
    is_exact_match: true
    name: Environment and Nature Conservation
    organisational_unit: department
    url_path: /2015-16/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Environment and Nature Conservation
    organisational_unit: department
    url_path: /2016-17/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Environment and Nature Conservation
    organisational_unit: department
    url_path: /2017-18/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2017-18
  is_selected: true
government:
  name: Northern Cape
name: Environment and Nature Conservation
vote_number: 13
