#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
description: 'Northern Cape department: Environment and Nature Conservation budget
  data for the 2017-18 financial year from National Treasury in partnership with IMALI
  YETHU.'
economic_classification_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2017-18
  programmes:
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 42624000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 20714000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 1469000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Public corporations and private enterprises
        total_budget: 212000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: ADMINISTRATION
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 27455000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 6600000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 174000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    name: BIODIVERSITY MANAGEMENT
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 9362000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 1648000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 100000
        type: economic_classification_2
      - name: Buildings and other fixed structures
        total_budget: 66000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    name: COMPLIANCE AND ENFORCEMENT
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 12242000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 1105000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 196000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    name: ENVIRONMENTAL EMPOWERMENT SERVICES
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 10104000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 546000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 123000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    name: ENVIRONMENTAL POLICY,PLANNING AND COORDINATION
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 10189000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 3671000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 391000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    name: ENVIRONMENTAL QUALITY MANAGEMENT
    type: programme
expenditure_over_time:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2017-18
  expenditure:
    base_financial_year: 2017-18
    nominal:
    - amount: 117641000
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 127586000
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 133652000
      financial_year: 2015-16
      phase: Audited Outcome
    - amount: 141678000
      financial_year: 2016-17
      phase: Adjusted appropriation
    - amount: 148991000
      financial_year: 2017-18
      phase: Main appropriation
    - amount: 155954000
      financial_year: 2018-19
      phase: Medium Term Estimates
    - amount: 164998000
      financial_year: 2019-20
      phase: Medium Term Estimates
    real:
    - amount: 145695798
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 149596195
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 149009461
      financial_year: 2015-16
      phase: Audited Outcome
    - amount: 148602936
      financial_year: 2016-17
      phase: Adjusted appropriation
    - amount: 148991000
      financial_year: 2017-18
      phase: Main appropriation
    - amount: 147835447
      financial_year: 2018-19
      phase: Medium Term Estimates
    - amount: 148548632
      financial_year: 2019-20
      phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2017-18
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2018-19
  is_selected: false
government:
  name: Northern Cape
  slug: northern-cape
government_functions:
- Economic affairs
intro: "## Vision\n\nA prosperous society living sustainably with the natural environment.\r\
  \n\r\n\n\n## Mission\n\nConserve and protect the natural environment for the benefit,\
  \ enjoyment and welfare of present and future generations by integrating sustainable\
  \ utilization with socio-economic development.\r\n\r\n\n\n## Core functions\n\n\
  * Environmental assets conserved, valued, sustainably used, protected and continually\
  \ enhanced; \r\n\r\n* Enhanced socio-economic benefits and employment creation for\
  \ the present and future generations from a healthy environment;\r\n\r\n* A department\
  \ that is fully capacitated to deliver its services efficiently and effectively;\
  \ \r\n\r\n* Environmental education provide to stimulate critical thinking and influence\
  \ decision making;\r\n\r\n* Ensure sustainable development and utilisation of natural\
  \ resources while securing representative and resilient ecosystems through scientific\
  \ research, spatial planning and cooperative governance;\r\n\r\n* To promote and\
  \ enforce compliance with environmental legislation"
is_vote_primary: true
name: Environment and Nature Conservation
programme_by_economic_classification:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2017-18
  econ_classes:
  - items:
    - name: ADMINISTRATION
      total_budget: 42624000
      type: programme
    - name: BIODIVERSITY MANAGEMENT
      total_budget: 27455000
      type: programme
    - name: ENVIRONMENTAL EMPOWERMENT SERVICES
      total_budget: 12242000
      type: programme
    - name: ENVIRONMENTAL QUALITY MANAGEMENT
      total_budget: 10189000
      type: programme
    - name: ENVIRONMENTAL POLICY,PLANNING AND COORDINATION
      total_budget: 10104000
      type: programme
    - name: COMPLIANCE AND ENFORCEMENT
      total_budget: 9362000
      type: programme
    name: Current payments - Compensation of employees
    type: economic_classification_1_and_2
  - items:
    - name: ADMINISTRATION
      total_budget: 20714000
      type: programme
    - name: BIODIVERSITY MANAGEMENT
      total_budget: 6600000
      type: programme
    - name: ENVIRONMENTAL QUALITY MANAGEMENT
      total_budget: 3671000
      type: programme
    - name: COMPLIANCE AND ENFORCEMENT
      total_budget: 1648000
      type: programme
    - name: ENVIRONMENTAL EMPOWERMENT SERVICES
      total_budget: 1105000
      type: programme
    - name: ENVIRONMENTAL POLICY,PLANNING AND COORDINATION
      total_budget: 546000
      type: programme
    name: Current payments - Goods and services
    type: economic_classification_1_and_2
  - items:
    - name: COMPLIANCE AND ENFORCEMENT
      total_budget: 66000
      type: programme
    name: Payments for capital assets - Buildings and other fixed structures
    type: economic_classification_1_and_2
  - items:
    - name: ADMINISTRATION
      total_budget: 1469000
      type: programme
    - name: ENVIRONMENTAL QUALITY MANAGEMENT
      total_budget: 391000
      type: programme
    - name: ENVIRONMENTAL EMPOWERMENT SERVICES
      total_budget: 196000
      type: programme
    - name: BIODIVERSITY MANAGEMENT
      total_budget: 174000
      type: programme
    - name: ENVIRONMENTAL POLICY,PLANNING AND COORDINATION
      total_budget: 123000
      type: programme
    - name: COMPLIANCE AND ENFORCEMENT
      total_budget: 100000
      type: programme
    name: Payments for capital assets - Machinery and equipment
    type: economic_classification_1_and_2
  - items:
    - name: ADMINISTRATION
      total_budget: 212000
      type: programme
    name: Transfers and subsidies - Public corporations and private enterprises
    type: economic_classification_1_and_2
programmes:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2017-18
  programme_budgets:
  - name: ADMINISTRATION
    total_budget: 65019000
  - name: ENVIRONMENTAL POLICY,PLANNING AND COORDINATION
    total_budget: 10773000
  - name: COMPLIANCE AND ENFORCEMENT
    total_budget: 11176000
  - name: ENVIRONMENTAL QUALITY MANAGEMENT
    total_budget: 14251000
  - name: BIODIVERSITY MANAGEMENT
    total_budget: 34229000
  - name: ENVIRONMENTAL EMPOWERMENT SERVICES
    total_budget: 13543000
selected_financial_year: 2017-18
selected_tab: departments
slug: environment-and-nature-conservation
sphere:
  name: Provincial
  slug: provincial
subprogramme_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/epre-sub-programme-expenditure-2017-18
  programmes: []
title: Environment and Nature Conservation budget 2017-18  - vulekamali
treasury_datasets:
  'EPRE for Vote 13 : Environment and Nature Conservation':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/3155dc62-5e61-4597-8d89-59c189ce50e5/resource/aa8f2f68-b7d8-46cb-8501-285acac2fc1b/download/nc-environ.-and-nature-conservation.xlsm
    - format: PDF
      url: https://data.vulekamali.gov.za/dataset/3155dc62-5e61-4597-8d89-59c189ce50e5/resource/e62c2590-2f7e-405d-b8df-2debb3f782fd/download/nc-vote-13-environment-and-nature-conservation.pdf
vote_number: 13
vote_primary:
  name: Environment and Nature Conservation
  slug: environment-and-nature-conservation
  url_path: /2017-18/provincial/northern-cape/departments/environment-and-nature-conservation
