contributed_datasets:
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/budget-analysis-for-advancing-socioeconomic-rights
description: 'Northern Cape department: Environment and Nature Conservation budget
  data for the 2017-18 financial year from National Treasury in partnership with IMALI
  YETHU.'
expenditure_over_time:
  base_financial_year: 2017-18
  nominal:
  - amount: 117641000
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 127586000
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 133652000
    financial_year: 2015-16
    phase: Audited Outcome
  - amount: 141678000
    financial_year: 2016-17
    phase: Adjusted appropriation
  - amount: 148991000
    financial_year: 2017-18
    phase: Main appropriation
  - amount: 155954000
    financial_year: 2018-19
    phase: Medium Term Estimates
  - amount: 164998000
    financial_year: 2019-20
    phase: Medium Term Estimates
  real:
  - amount: 145695798
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 149596195
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 149009461
    financial_year: 2015-16
    phase: Audited Outcome
  - amount: 148602936
    financial_year: 2016-17
    phase: Adjusted appropriation
  - amount: 148991000
    financial_year: 2017-18
    phase: Main appropriation
  - amount: 147835447
    financial_year: 2018-19
    phase: Medium Term Estimates
  - amount: 148548632
    financial_year: 2019-20
    phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2017-18
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2018-19
  is_selected: false
government:
  name: Northern Cape
  slug: northern-cape
government_functions:
- Economic affairs
intro: "## Vision\n\nA prosperous society living sustainably with the natural environment.\r\
  \n\r\n\n\n## Mission\n\nConserve and protect the natural environment for the benefit,\
  \ enjoyment and welfare of present and future generations by integrating sustainable\
  \ utilization with socio-economic development.\r\n\r\n\n\n## Core functions\n\n\
  * Environmental assets conserved, valued, sustainably used, protected and continually\
  \ enhanced; \r\n\r\n* Enhanced socio-economic benefits and employment creation for\
  \ the present and future generations from a healthy environment;\r\n\r\n* A department\
  \ that is fully capacitated to deliver its services efficiently and effectively;\
  \ \r\n\r\n* Environmental education provide to stimulate critical thinking and influence\
  \ decision making;\r\n\r\n* Ensure sustainable development and utilisation of natural\
  \ resources while securing representative and resilient ecosystems through scientific\
  \ research, spatial planning and cooperative governance;\r\n\r\n* To promote and\
  \ enforce compliance with environmental legislation"
is_vote_primary: true
name: Environment and Nature Conservation
programmes:
- name: ADMINISTRATION
  total_budget: 65019000
- name: ENVIRONMENTAL POLICY,PLANNING AND COORDINATION
  total_budget: 10773000
- name: COMPLIANCE AND ENFORCEMENT
  total_budget: 11176000
- name: ENVIRONMENTAL QUALITY MANAGEMENT
  total_budget: 14251000
- name: BIODIVERSITY MANAGEMENT
  total_budget: 34229000
- name: ENVIRONMENTAL EMPOWERMENT SERVICES
  total_budget: 13543000
selected_financial_year: 2017-18
selected_tab: departments
slug: environment-and-nature-conservation
sphere:
  name: Provincial
  slug: provincial
title: Environment and Nature Conservation budget 2017-18  - vulekamali
treasury_datasets:
  'EPRE for Vote 13 : Environment and Nature Conservation':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/3155dc62-5e61-4597-8d89-59c189ce50e5/resource/aa8f2f68-b7d8-46cb-8501-285acac2fc1b/download/nc-environ.-and-nature-conservation.xlsm
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2017/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/NC/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/NC%20-%20Vote%2013%20-%20Environment%20and%20Nature%20Conservation.pdf
vote_number: 13
vote_primary:
  name: Environment and Nature Conservation
  slug: environment-and-nature-conservation
  url_path: /2017-18/provincial/northern-cape/departments/environment-and-nature-conservation
