#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: The transparency of public funding of Basic Education in South Africa
  url_path: /datasets/contributed/the-transparency-of-public-funding-of-basic-education-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
- contributor: Centre for Child Law
  name: 'Mud to bricks: A review of school infrastructure spending and delivery'
  url_path: /datasets/contributed/mud-to-bricks-a-review-of-school-infrastructure-spending-and-delivery
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Eastern Cape Department of Health 2014/15'
  url_path: /datasets/contributed/budget-brief-eastern-cape-department-of-health-2014-15
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Eastern Cape Department of Education 2016/17'
  url_path: /datasets/contributed/budget-brief-eastern-cape-department-of-education-2016-17
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Eastern Cape Department of Human Settlements 2014/15'
  url_path: /datasets/contributed/budget-brief-eastern-cape-department-of-human-settlements-2014-15
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Department of Human Settlements, 2016/17 and 2017/18'
  url_path: /datasets/contributed/budget-brief-department-of-human-settlements
description: 'Western Cape department: Environmental Affairs And Development Planning
  budget data for the 2018-19 financial year from National Treasury in partnership
  with IMALI YETHU.'
expenditure_over_time:
  base_financial_year: 2017-18
  nominal:
  - amount: 457181000.0
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 502648000.0
    financial_year: 2015-16
    phase: Audited Outcome
  - amount: 537950000.0
    financial_year: 2016-17
    phase: Audited Outcome
  - amount: 555720000.0
    financial_year: 2017-18
    phase: Adjusted appropriation
  - amount: 604621000.0
    financial_year: 2018-19
    phase: Main appropriation
  - amount: 604611000.0
    financial_year: 2019-20
    phase: Medium Term Estimates
  - amount: 625955000.0
    financial_year: 2020-21
    phase: Medium Term Estimates
  real:
  - amount: 536050492
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 560405441
    financial_year: 2015-16
    phase: Audited Outcome
  - amount: 564243917
    financial_year: 2016-17
    phase: Audited Outcome
  - amount: 555720000
    financial_year: 2017-18
    phase: Adjusted appropriation
  - amount: 573146030
    financial_year: 2018-19
    phase: Main appropriation
  - amount: 544334703
    financial_year: 2019-20
    phase: Medium Term Estimates
  - amount: 533965018
    financial_year: 2020-21
    phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2018-19
  is_selected: true
government:
  name: Western Cape
  slug: western-cape
government_functions: []
intro: ''
is_vote_primary: true
name: Environmental Affairs And Development Planning
programmes:
- name: Administration
  total_budget: 68703000.0
- name: Environmental Policy, Planning And Coordination
  total_budget: 20619000.0
- name: Compliance And Enforcement
  total_budget: 24924000.0
- name: Environmental Quality Management
  total_budget: 95813000.0
- name: Biodiversity Management
  total_budget: 319724000.0
- name: Environmental Empowerment Services
  total_budget: 996000.0
- name: Development Planning
  total_budget: 73842000.0
- name: Direct Charges
  total_budget: 0.0
selected_financial_year: 2018-19
selected_tab: departments
slug: environmental-affairs-and-development-planning
sphere:
  name: Provincial
  slug: provincial
title: Environmental Affairs And Development Planning budget 2018-19  - vulekamali
treasury_datasets: {}
vote_number: 9
vote_primary:
  name: Environmental Affairs And Development Planning
  slug: environmental-affairs-and-development-planning
  url_path: /2018-19/provincial/western-cape/departments/environmental-affairs-and-development-planning
