#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

adjusted_budget_summary: null
budget_actual: null
budget_actual_programmes: null
contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
department_adjusted_budget:
  document:
    description: ''
    format: PDF
    name: "Limpopo AEPRE 2015-16 \u2013 Vote 6 - Economic Development, Environment\
      \ and Tourism"
    url: https://data.vulekamali.gov.za/dataset/2e2e0dfe-a600-41b7-aac2-92e2c32cc00e/resource/56151815-549b-412d-a33d-ceb783152504/download/lim-vote06-eco.-dev.env.-and-tourism.pdf
  name: "Limpopo AEPRE 2015-16 \u2013 Vote 6 - Economic Development, Environment and\
    \ Tourism"
  tables: null
department_budget:
  document:
    description: ''
    format: PDF
    name: 'Vote 06 : Economic Development, Environment and Tourism'
    url: https://data.vulekamali.gov.za/dataset/36bb3596-73a0-4cce-bc3b-0a1cb37ac51f/resource/04ee4f20-4d96-4ab9-8643-b8919a0add52/download/lim-vote-06-economic-dev-environm-tourism.pdf
  name: 'Limpopo Department: Economic Development, Environment and Tourism 2015-16'
  tables:
    description: ''
    format: XLSX
    name: 'Vote 06 : Economic Development, Environment and Tourism'
    url: https://data.vulekamali.gov.za/dataset/36bb3596-73a0-4cce-bc3b-0a1cb37ac51f/resource/ebefb9c9-a6ca-40d7-978c-c30d11c85107/download/lim-eco-dev-env-affairs-and-tourism.xlsx
description: 'Limpopo department: Economic Development, Environment and Tourism budget
  data for the 2015-16 financial year from National Treasury in partnership with IMALI
  YETHU.'
economic_classification_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2015-16
  department_data_csv: https://datamanager-staging.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2015-16/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2015%257Cgovernment.government%253A%2522Limpopo%2522%257Cdepartment.department%253A%2522Economic%2BDevelopment%252C%2BEnvironment%2Band%2BTourism%2522%26drilldown%3Dbudget_phase.budget_phase%257Cdepartment.department%257Ceconomic_classification_1.economic_classification_1%257Ceconomic_classification_2.economic_classification_2%257Ceconomic_classification_3.economic_classification_3%257Ceconomic_classification_4.economic_classification_4%257Cfinancial_year.financial_year%257Cgovernment.government%257Cprogramme_number.programme%257Cprogramme_number.programme_number%26pagesize%3D10000
  programmes:
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 165373000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 122449000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 5108000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Households
        total_budget: 7067000
        type: economic_classification_2
      - name: Provinces and municipalities
        total_budget: 2810000
        type: economic_classification_2
      - name: Departmental agencies and accounts
        total_budget: 1473000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Administration
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 90506000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 37280000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Buildings and other fixed structures
        total_budget: 2749000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Departmental agencies and accounts
        total_budget: 309888000
        type: economic_classification_2
      - name: Households
        total_budget: 257000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Economic Development
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 209134000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 28802000
        type: economic_classification_2
      - name: Interest and rent on land
        total_budget: 416000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 491000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Households
        total_budget: 1872000
        type: economic_classification_2
      - name: Provinces and municipalities
        total_budget: 1102000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Environmental Affairs
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 12852000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 4989000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Departmental agencies and accounts
        total_budget: 156195000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Tourism
    type: programme
expenditure_over_time:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2015-16
  expenditure:
    base_financial_year: 2017-18
    nominal:
    - amount: 866942000
      financial_year: 2011-12
      phase: Audited Outcome
    - amount: 874203000
      financial_year: 2012-13
      phase: Audited Outcome
    - amount: 1071242000
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 1149777000
      financial_year: 2014-15
      phase: Adjusted appropriation
    - amount: 1160813000
      financial_year: 2015-16
      phase: Main appropriation
    - amount: 1224371000
      financial_year: 2016-17
      phase: Medium Term Estimates
    - amount: 1284953000
      financial_year: 2017-18
      phase: Medium Term Estimates
    real:
    - amount: 1199110691
      financial_year: 2011-12
      phase: Audited Outcome
    - amount: 1145660814
      financial_year: 2012-13
      phase: Audited Outcome
    - amount: 1326709723
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 1348128043
      financial_year: 2014-15
      phase: Adjusted appropriation
    - amount: 1294197771
      financial_year: 2015-16
      phase: Main appropriation
    - amount: 1284215800
      financial_year: 2016-17
      phase: Medium Term Estimates
    - amount: 1284953000
      financial_year: 2017-18
      phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/limpopo/departments/economic-development-environment-and-tourism
  id: 2015-16
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/limpopo/departments/economic-development-environment-and-tourism
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/limpopo/departments/economic-development-environment-and-tourism
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/limpopo/departments/economic-development-environment-and-tourism
  id: 2018-19
  is_selected: false
government:
  name: Limpopo
  slug: limpopo
government_functions: []
intro: "## Vision\r\n\r\nA competitive economy within a sustainable environment.\r\
  \n\r\n\r\n\r\n## Mission\r\n\r\nTo create and facilitate the development of a competitive\
  \ economy, sustainable environment and tourism growth.\r\n\r\n\r\n\r\n## Core functions\r\
  \n\r\nThe mandate of the Department is to develop the provincial economy, promote\
  \ and manage environmental and tourism activities.\r\n\r\nTo carry out this mandate,\
  \ the department pursues the following:\r\n\r\n* Improve service delivery to communities\
  \ and stakeholders through a skilled, accountable, corrupt free, development oriented\
  \ and empowered and intergraded Public Service\r\n\r\n* Accelerate employment, economic\
  \ growth and development\r\n\r\n* Ensure sustainable development through targeted\
  \ intervention on environmental management, development of natural resources, creation\
  \ of green jobs and proactive responses to climate change\r\n\r\n* To position Limpopo\
  \ as a preferred tourism and investment destination within SADC and the World\r\n\
  \r\n* Transform Limpopo into a world class knowledge society that uses ICT as an\
  \ enabler of socio-economic development and ICT as a production sector."
is_vote_primary: true
name: Economic Development, Environment and Tourism
programme_by_economic_classification:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2015-16
  department_data_csv: https://datamanager-staging.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2015-16/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2015%257Cgovernment.government%253A%2522Limpopo%2522%257Cdepartment.department%253A%2522Economic%2BDevelopment%252C%2BEnvironment%2Band%2BTourism%2522%26drilldown%3Dbudget_phase.budget_phase%257Cdepartment.department%257Ceconomic_classification_1.economic_classification_1%257Ceconomic_classification_2.economic_classification_2%257Ceconomic_classification_3.economic_classification_3%257Ceconomic_classification_4.economic_classification_4%257Cfinancial_year.financial_year%257Cgovernment.government%257Cprogramme_number.programme%257Cprogramme_number.programme_number%26pagesize%3D10000
  econ_classes:
  - items:
    - name: Environmental Affairs
      total_budget: 209134000
      type: programme
    - name: Administration
      total_budget: 165373000
      type: programme
    - name: Economic Development
      total_budget: 90506000
      type: programme
    - name: Tourism
      total_budget: 12852000
      type: programme
    name: Current payments - Compensation of employees
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 122449000
      type: programme
    - name: Economic Development
      total_budget: 37280000
      type: programme
    - name: Environmental Affairs
      total_budget: 28802000
      type: programme
    - name: Tourism
      total_budget: 4989000
      type: programme
    name: Current payments - Goods and services
    type: economic_classification_1_and_2
  - items:
    - name: Environmental Affairs
      total_budget: 416000
      type: programme
    name: Current payments - Interest and rent on land
    type: economic_classification_1_and_2
  - items:
    - name: Economic Development
      total_budget: 2749000
      type: programme
    name: Payments for capital assets - Buildings and other fixed structures
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 5108000
      type: programme
    - name: Environmental Affairs
      total_budget: 491000
      type: programme
    name: Payments for capital assets - Machinery and equipment
    type: economic_classification_1_and_2
  - items:
    - name: Economic Development
      total_budget: 309888000
      type: programme
    - name: Tourism
      total_budget: 156195000
      type: programme
    - name: Administration
      total_budget: 1473000
      type: programme
    name: Transfers and subsidies - Departmental agencies and accounts
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 7067000
      type: programme
    - name: Environmental Affairs
      total_budget: 1872000
      type: programme
    - name: Economic Development
      total_budget: 257000
      type: programme
    name: Transfers and subsidies - Households
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 2810000
      type: programme
    - name: Environmental Affairs
      total_budget: 1102000
      type: programme
    name: Transfers and subsidies - Provinces and municipalities
    type: economic_classification_1_and_2
programmes:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2015-16
  department_data_csv: https://datamanager-staging.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2015-16/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2015%257Cgovernment.government%253A%2522Limpopo%2522%257Cdepartment.department%253A%2522Economic%2BDevelopment%252C%2BEnvironment%2Band%2BTourism%2522%26drilldown%3Dbudget_phase.budget_phase%257Cdepartment.department%257Ceconomic_classification_1.economic_classification_1%257Ceconomic_classification_2.economic_classification_2%257Ceconomic_classification_3.economic_classification_3%257Ceconomic_classification_4.economic_classification_4%257Cfinancial_year.financial_year%257Cgovernment.government%257Cprogramme_number.programme%257Cprogramme_number.programme_number%26pagesize%3D10000
  programme_budgets:
  - name: Administration
    total_budget: 304280000
  - name: Economic Development
    total_budget: 440680000
  - name: Environmental Affairs
    total_budget: 241817000
  - name: Tourism
    total_budget: 174036000
selected_financial_year: 2015-16
selected_tab: departments
slug: economic-development-environment-and-tourism
sphere:
  name: Provincial
  slug: provincial
subprogramme_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/epre-sub-programme-expenditure-2015-16
  department_data_csv: https://datamanager-staging.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aepre-sub-programme-expenditure-2015-16-v2/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2015%257Cgovernment.government%253A%2522Limpopo%2522%257Cdepartment.department%253A%2522Economic%2BDevelopment%252C%2BEnvironment%2Band%2BTourism%2522%26drilldown%3Ddepartment.department%257Cfinancial_year.financial_year%257Cgovernment.government%257Cphase.phase%257Cprogramme_number.programme%257Cprogramme_number.programme_number%257Csubprogramme.subprogramme%26pagesize%3D10000
  programmes: []
title: Economic Development, Environment and Tourism budget 2015-16  - vulekamali
vote_number: 6
vote_primary:
  name: Economic Development, Environment and Tourism
  slug: economic-development-environment-and-tourism
  url_path: /2015-16/provincial/limpopo/departments/economic-development-environment-and-tourism
