financial_years:
- closest_match:
    is_exact_match: true
    name: Economic Development, Environmental Affairs and Tourism
    organisational_unit: department
    slug: economic-development-environmental-affairs-and-tourism
    url_path: /2015-16/provincial/limpopo/departments/economic-development-environmental-affairs-and-tourism
  id: 2015-16
  is_selected: true
- closest_match:
    is_exact_match: true
    name: Economic Development, Environmental Affairs and Tourism
    organisational_unit: department
    slug: economic-development-environmental-affairs-and-tourism
    url_path: /2016-17/provincial/limpopo/departments/economic-development-environmental-affairs-and-tourism
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Economic Development, Environmental Affairs and Tourism
    organisational_unit: department
    slug: economic-development-environmental-affairs-and-tourism
    url_path: /2017-18/provincial/limpopo/departments/economic-development-environmental-affairs-and-tourism
  id: 2017-18
  is_selected: false
government:
  name: Limpopo
  slug: limpopo
name: Economic Development, Environmental Affairs and Tourism
narrative: {}
resources:
  'EPRE for Vote 06 : Economic Development, Environmental Affairs and Tourism':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSX
      url: https://treasurydata.openup.org.za/dataset/36bb3596-73a0-4cce-bc3b-0a1cb37ac51f/resource/ebefb9c9-a6ca-40d7-978c-c30d11c85107/download/lim-eco-dev-env-affairs-and-tourism.xlsx
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2015/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/LIM/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/LIM
        - Vote 06 - Economic Dev, Environm & Tourism.pdf
slug: economic-development-environmental-affairs-and-tourism
vote_number: 6
