financial_years:
- closest_match:
    is_exact_match: true
    name: Agriculture, Environmental Affairs and Rural Development
    organisational_unit: department
    url_path: /2015-16/provincial/kwazulu-natal/departments/agriculture-environmental-affairs-and-rural-development
  id: 2015-16
  is_selected: true
- closest_match:
    is_exact_match: true
    name: Agriculture, Environmental Affairs and Rural Development
    organisational_unit: department
    url_path: /2016-17/provincial/kwazulu-natal/departments/agriculture-environmental-affairs-and-rural-development
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Agriculture, Environmental Affairs and Rural Development
    organisational_unit: department
    url_path: /2017-18/provincial/kwazulu-natal/departments/agriculture-environmental-affairs-and-rural-development
  id: 2017-18
  is_selected: false
government:
  name: KwaZulu-Natal
name: Agriculture, Environmental Affairs and Rural Development
vote_number: 3
