#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
description: 'KwaZulu-Natal department: Economic Development, Tourism and Environmental
  Affairs budget data for the 2015-16 financial year from National Treasury in partnership
  with IMALI YETHU.'
economic_classification_by_programme:
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Goods and services
      total_budget: 132588000
    - economic_classification_2_name: Compensation of employees
      total_budget: 96316000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 3660000
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Households
      total_budget: 500000
    - economic_classification_2_name: Provinces and municipalities
      total_budget: 31000
  programme_name: Administration
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 18915000
    - economic_classification_2_name: Goods and services
      total_budget: 14209000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 158000
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Departmental agencies and accounts
      total_budget: 67008000
  programme_name: Business Regulation and Governance
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Goods and services
      total_budget: 22627000
    - economic_classification_2_name: Compensation of employees
      total_budget: 14840000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 15000
  programme_name: Economic Planning
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Goods and services
      total_budget: 164900000
    - economic_classification_2_name: Compensation of employees
      total_budget: 102355000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 2578000
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Departmental agencies and accounts
      total_budget: 646819000
    - economic_classification_2_name: Non-profit institutions
      total_budget: 6195000
    - economic_classification_2_name: Provinces and municipalities
      total_budget: 1000000
  programme_name: Environmental Affairs
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Goods and services
      total_budget: 108550000
    - economic_classification_2_name: Compensation of employees
      total_budget: 59230000
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Software and other intangible assets
      total_budget: 200000
    - economic_classification_2_name: Machinery and equipment
      total_budget: 155000
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Public corporations and private enterprises
      total_budget: 149700000
    - economic_classification_2_name: Non-profit institutions
      total_budget: 95000000
    - economic_classification_2_name: Households
      total_budget: 9880000
  programme_name: Integrated Economic Development Services
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Goods and services
      total_budget: 120455000
    - economic_classification_2_name: Compensation of employees
      total_budget: 13140000
  - economic_classification_1_name: Payments for financial assets
    items:
    - economic_classification_2_name: ''
      total_budget: 236000
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Departmental agencies and accounts
      total_budget: 162690000
    - economic_classification_2_name: Provinces and municipalities
      total_budget: 1250000
    - economic_classification_2_name: Public corporations and private enterprises
      total_budget: 1000000
  programme_name: Tourism
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Goods and services
      total_budget: 46138000
    - economic_classification_2_name: Compensation of employees
      total_budget: 13630000
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Departmental agencies and accounts
      total_budget: 673816000
    - economic_classification_2_name: Public corporations and private enterprises
      total_budget: 123247000
    - economic_classification_2_name: Non-profit institutions
      total_budget: 100428000
  programme_name: Trade and Sector Development
expenditure_over_time:
  base_financial_year: 2017-18
  nominal:
  - amount: 2226580000
    financial_year: 2011-12
    phase: Audited Outcome
  - amount: 2421869000
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 3311354000
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 3013455000
    financial_year: 2014-15
    phase: Adjusted appropriation
  - amount: 2973459000
    financial_year: 2015-16
    phase: Main appropriation
  - amount: 3080528000
    financial_year: 2016-17
    phase: Medium Term Estimates
  - amount: 3219734000
    financial_year: 2017-18
    phase: Medium Term Estimates
  real:
  - amount: 3079693779
    financial_year: 2011-12
    phase: Audited Outcome
  - amount: 3173908591
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 4101039308
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 3533314019
    financial_year: 2014-15
    phase: Adjusted appropriation
  - amount: 3315128286
    financial_year: 2015-16
    phase: Main appropriation
  - amount: 3231098034
    financial_year: 2016-17
    phase: Medium Term Estimates
  - amount: 3219734000
    financial_year: 2017-18
    phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
  id: 2015-16
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
  id: 2018-19
  is_selected: false
government:
  name: KwaZulu-Natal
  slug: kwazulu-natal
government_functions: []
intro: "## Vision\r\n\r\nThe vision of the Department of Economic Development, Tourism\
  \ and Environmental Affairs (DEDTEA) is: Leading the attainment of inclusive and\
  \ sustainable economic growth for job creation.\r\n\r\n\r\n\r\n## Mission\r\n\r\n\
  The department\u2019s mission is to: Provide leadership and facilitate integrated\
  \ economic planning, be a catalyst for economic transformation and sustainable development,\
  \ implement strategies that drive economic growth and promote sound environmental\
  \ management, create a conducive environment for trade, investment and tourism and\
  \ monitor and enforce sound business and consumer regulations.\r\n\r\n\r\n\r\n##\
  \ Core functions\r\n\r\nThe department\u2019s core functions are summarised as follows:\r\
  \n\r\n* To drive the economic development strategies of the province.\r\n\r\n* To\
  \ facilitate strategies to enhance the competitiveness of priority sectors of the\
  \ economy, in line with the industrial development strategy.\r\n\r\n* To promote\
  \ the development of small business and social enterprises.\r\n\r\n* To promote\
  \ and facilitate economic empowerment programmes.\r\n\r\n* To manage the Enterprise\
  \ Development and Growth Funds.\r\n\r\n* To provide an effective and efficient consumer\
  \ protection service.\r\n\r\n* To ensure effective and prudent business regulation\
  \ in the province.\r\n\r\n* To provide effective and efficient environmental management.\r\
  \n\r\n* To provide conservation services"
is_vote_primary: true
name: Economic Development, Tourism and Environmental Affairs
programmes:
- name: Administration
  total_budget: 233095000
- name: Integrated Economic Development Services
  total_budget: 422715000
- name: Trade and Sector Development
  total_budget: 957259000
- name: Business Regulation and Governance
  total_budget: 100290000
- name: Economic Planning
  total_budget: 37482000
- name: Tourism
  total_budget: 298771000
- name: Environmental Affairs
  total_budget: 923847000
selected_financial_year: 2015-16
selected_tab: departments
slug: economic-development-tourism-and-environmental-affairs
sphere:
  name: Provincial
  slug: provincial
title: Economic Development, Tourism and Environmental Affairs budget 2015-16  - vulekamali
treasury_datasets:
  'EPRE for Vote 04 : Economic Development, Tourism and Environmental Affairs':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSX
      url: https://data.vulekamali.gov.za/dataset/6baca5bf-b00a-4585-b4a0-f20334ae475a/resource/d87b0d52-4f42-4a84-92e9-c1352a68e561/download/kzn-eco-dev-tourism-and-env-affairs.xlsx
    - format: PDF
      url: https://data.vulekamali.gov.za/dataset/6baca5bf-b00a-4585-b4a0-f20334ae475a/resource/a8b61180-a924-43ea-ba12-840774cba5e5/download/kzn-vote-04-economic-development-and-tourism.pdf
vote_number: 4
vote_primary:
  name: Economic Development, Tourism and Environmental Affairs
  slug: economic-development-tourism-and-environmental-affairs
  url_path: /2015-16/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
