#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
description: 'KwaZulu-Natal department: Economic Development, Tourism and Environmental
  Affairs budget data for the 2015-16 financial year from National Treasury in partnership
  with IMALI YETHU.'
expenditure_over_time:
  base_financial_year: 2017-18
  nominal:
  - amount: 2226580000
    financial_year: 2011-12
    phase: Audited Outcome
  - amount: 2421869000
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 3311354000
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 3013455000
    financial_year: 2014-15
    phase: Adjusted appropriation
  - amount: 2973459000
    financial_year: 2015-16
    phase: Main appropriation
  - amount: 3080528000
    financial_year: 2016-17
    phase: Medium Term Estimates
  - amount: 3219734000
    financial_year: 2017-18
    phase: Medium Term Estimates
  real:
  - amount: 3079693779
    financial_year: 2011-12
    phase: Audited Outcome
  - amount: 3173908591
    financial_year: 2012-13
    phase: Audited Outcome
  - amount: 4101039308
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 3533314019
    financial_year: 2014-15
    phase: Adjusted appropriation
  - amount: 3315128286
    financial_year: 2015-16
    phase: Main appropriation
  - amount: 3231098034
    financial_year: 2016-17
    phase: Medium Term Estimates
  - amount: 3219734000
    financial_year: 2017-18
    phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
  id: 2015-16
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
  id: 2018-19
  is_selected: false
government:
  name: KwaZulu-Natal
  slug: kwazulu-natal
government_functions: []
intro: "## Vision\r\n\r\nThe vision of the Department of Economic Development, Tourism\
  \ and Environmental Affairs (DEDTEA) is: Leading the attainment of inclusive and\
  \ sustainable economic growth for job creation.\r\n\r\n\r\n\r\n## Mission\r\n\r\n\
  The department\u2019s mission is to: Provide leadership and facilitate integrated\
  \ economic planning, be a catalyst for economic transformation and sustainable development,\
  \ implement strategies that drive economic growth and promote sound environmental\
  \ management, create a conducive environment for trade, investment and tourism and\
  \ monitor and enforce sound business and consumer regulations.\r\n\r\n\r\n\r\n##\
  \ Core functions\r\n\r\nThe department\u2019s core functions are summarised as follows:\r\
  \n\r\n* To drive the economic development strategies of the province.\r\n\r\n* To\
  \ facilitate strategies to enhance the competitiveness of priority sectors of the\
  \ economy, in line with the industrial development strategy.\r\n\r\n* To promote\
  \ the development of small business and social enterprises.\r\n\r\n* To promote\
  \ and facilitate economic empowerment programmes.\r\n\r\n* To manage the Enterprise\
  \ Development and Growth Funds.\r\n\r\n* To provide an effective and efficient consumer\
  \ protection service.\r\n\r\n* To ensure effective and prudent business regulation\
  \ in the province.\r\n\r\n* To provide effective and efficient environmental management.\r\
  \n\r\n* To provide conservation services"
is_vote_primary: true
name: Economic Development, Tourism and Environmental Affairs
programmes:
- name: Administration
  total_budget: 233095000
- name: Integrated Economic Development Services
  total_budget: 422715000
- name: Trade and Sector Development
  total_budget: 957259000
- name: Business Regulation and Governance
  total_budget: 100290000
- name: Economic Planning
  total_budget: 37482000
- name: Tourism
  total_budget: 298771000
- name: Environmental Affairs
  total_budget: 923847000
selected_financial_year: 2015-16
selected_tab: departments
slug: economic-development-tourism-and-environmental-affairs
sphere:
  name: Provincial
  slug: provincial
title: Economic Development, Tourism and Environmental Affairs budget 2015-16  - vulekamali
treasury_datasets:
  'EPRE for Vote 04 : Economic Development, Tourism and Environmental Affairs':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSX
      url: https://data.vulekamali.gov.za/dataset/6baca5bf-b00a-4585-b4a0-f20334ae475a/resource/d87b0d52-4f42-4a84-92e9-c1352a68e561/download/kzn-eco-dev-tourism-and-env-affairs.xlsx
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2015/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/KZN/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/KZN
        - Vote 04 - Economic Development and Tourism.pdf
vote_number: 4
vote_primary:
  name: Economic Development, Tourism and Environmental Affairs
  slug: economic-development-tourism-and-environmental-affairs
  url_path: /2015-16/provincial/kwazulu-natal/departments/economic-development-tourism-and-environmental-affairs
