#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: The transparency of public funding of Basic Education in South Africa
  url_path: /datasets/contributed/the-transparency-of-public-funding-of-basic-education-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
- contributor: Centre for Child Law
  name: 'Mud to bricks: A review of school infrastructure spending and delivery'
  url_path: /datasets/contributed/mud-to-bricks-a-review-of-school-infrastructure-spending-and-delivery
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Eastern Cape Department of Health 2014/15'
  url_path: /datasets/contributed/budget-brief-eastern-cape-department-of-health-2014-15
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Eastern Cape Department of Education 2016/17'
  url_path: /datasets/contributed/budget-brief-eastern-cape-department-of-education-2016-17
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Eastern Cape Department of Human Settlements 2014/15'
  url_path: /datasets/contributed/budget-brief-eastern-cape-department-of-human-settlements-2014-15
- contributor: Public Service Accountability Monitor
  name: 'Budget Brief: Department of Human Settlements, 2016/17 and 2017/18'
  url_path: /datasets/contributed/budget-brief-department-of-human-settlements
description: 'National department: Environmental Affairs budget data for the 2017-18
  financial year from National Treasury in partnership with IMALI YETHU.'
expenditure_over_time:
  base_financial_year: 2017-18
  nominal:
  - amount: 5200307000.0
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 5675059000.0
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 5937920000.0
    financial_year: 2015-16
    phase: Audited Outcome
  - amount: 6425101000.0
    financial_year: 2016-17
    phase: Adjusted appropriation
  - amount: 6848214000.0
    financial_year: 2017-18
    phase: Main appropriation
  - amount: 7061226000.0
    financial_year: 2018-19
    phase: Medium Term Estimates
  - amount: 7378025000.0
    financial_year: 2019-20
    phase: Medium Term Estimates
  real:
  - amount: 6440466173
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 6654078300
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 6620224646
    financial_year: 2015-16
    phase: Audited Outcome
  - amount: 6739147059
    financial_year: 2016-17
    phase: Adjusted appropriation
  - amount: 6848214000
    financial_year: 2017-18
    phase: Main appropriation
  - amount: 6693637254
    financial_year: 2018-19
    phase: Medium Term Estimates
  - amount: 6642477644
    financial_year: 2019-20
    phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/national/departments/environmental-affairs
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/national/departments/environmental-affairs
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/national/departments/environmental-affairs
  id: 2017-18
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2018-19/national/departments/environmental-affairs
  id: 2018-19
  is_selected: false
government:
  name: South Africa
  slug: south-africa
government_functions:
- Economic affairs
intro: "## Vote purpose\n\n_Lead South Africa's environmental sector to achieve sustainable\
  \ development\ntowards a better quality of life for all._\n\n\n\n## Mandate\n\n\
  The Department of Environmental Affairs is mandated to realise the right of\ncitizens\
  \ to an environment that is not harmful to their health or wellbeing,\nand to have\
  \ the environment protected for the benefit of present and future\ngenerations.\
  \ To this end, the department provides leadership in environmental\nmanagement,\
  \ conservation and protection towards sustainability for the benefit\nof South Africans\
  \ and the global community.\n\nThis mandate is derived from the following legislation:\n\
  \n  * the National Environmental Management Act (1998), which provides for issue\
  \ specific legislation on biodiversity and heritage resources; oceans and coasts;\
  \ climate change and air quality management; and waste and chemicals management\n\
  \n  * the National Environmental Management Amendment Act (2004), which streamlines\
  \ the process of regulating and administering the environmental impact assessment\
  \ process\n\n  * the National Environmental Management: Protected Areas Amendment\
  \ Act (2009), which provides for the assignment of national parks, special parks\
  \ and heritage sites to South Africa in terms of the World Heritage Convention Act\
  \ (1999)\n\n  * the National Environmental Management: Biodiversity Act (2004),\
  \ which significantly reforms South Africa\u2019s laws regulating biodiversity\n\
  \n  * the National Environmental Management: Air Quality and Atmospheric Act (2004),\
  \ which reforms the law regulating air quality in order to protect the environment\
  \ by providing reasonable measures for preventing pollution and ecological degradation,\
  \ securing ecologically sustainable development, and provides for national norms\
  \ and standards regulating air quality monitoring\n\n  * the National Environmental\
  \ Management: Waste Act (2008), which reforms the law regulating waste management\
  \ in order to protect health and the environment by providing reasonable measures\
  \ for the prevention of pollution\n\n  * the National Environmental Management:\
  \ Integrated Coastal Management Act (2008), which promotes the conservation of the\
  \ coastal environment and ensures sustainable development practices and the use\
  \ of natural resources.\n\n"
is_vote_primary: true
name: Environmental Affairs
programmes:
- name: Administration
  total_budget: 863045000.0
- name: Legal, Authorisations and Compliance
  total_budget: 179780000.0
- name: Oceans and Coasts
  total_budget: 468455000.0
- name: Climate Change and Air Quality
  total_budget: 294872000.0
- name: Biodiversity and Conservation
  total_budget: 696518000.0
- name: Environmental Programmes
  total_budget: 3895209000.0
- name: Chemicals and Waste Management
  total_budget: 450335000.0
selected_financial_year: 2017-18
selected_tab: departments
slug: environmental-affairs
sphere:
  name: National
  slug: national
title: Environmental Affairs budget 2017-18  - vulekamali
treasury_datasets:
  ENE for Vote 27 - Environmental Affairs:
    description: The Estimates of National Expenditure (ENE) sets out the detailed
      spending plans of each government department for the coming year.
    formats:
    - format: XLSX
      url: https://data.vulekamali.gov.za/dataset/nat-dept-environmental-affairs-2017-18/resource/1892de86-458f-4c82-9aeb-20193f9ce7e8/download/ene17-vote27_chaptertables.xlsx
    - format: PDF
      url: https://data.vulekamali.gov.za/dataset/nat-dept-environmental-affairs-2017-18/resource/1c5ac8e0-fe98-4838-ab6e-44b823641a4f/download/vote-27-environmental-affairs.pdf
vote_number: 27
vote_primary:
  name: Environmental Affairs
  slug: environmental-affairs
  url_path: /2017-18/national/departments/environmental-affairs
