#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
department_adjusted_budget: null
department_budget:
  document:
    description: ''
    format: PDF
    name: Vote 13 - Environment And Nature Conservation
    url: https://data.vulekamali.gov.za/dataset/d6477113-b3e3-48fc-b58e-83f7b6cfa1d2/resource/0c1c0f5f-a831-4dc6-9cf0-a24ce325b4b1/download/nc-vote-13-environment-and-nature-conservation.pdf
  name: 'Northern Cape Department: Environment And Nature Conservation 2018-19'
  tables: null
description: 'Northern Cape department: Environment And Nature Conservation budget
  data for the 2018-19 financial year from National Treasury in partnership with IMALI
  YETHU.'
economic_classification_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2018-19
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2018-19-shifted-econ-classes/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2018%257Cgovernment.government%253A%2522Northern%2BCape%2522%257Cdepartment.department%253A%2522Environment%2BAnd%2BNature%2BConservation%2522%26drilldown%3Dbudget_phase.budget_phase%257Cdepartment.department%257Ceconomic_classification_2.economic_classification_2%257Ceconomic_classification_3.economic_classification_3%257Ceconomic_classification_4.economic_classification_4%257Cfinancial_year.financial_year%257Cgovernment.government%257Cprogramme_number.programme%257Cprogramme_number.programme_number%26pagesize%3D10000
  programmes:
  - items:
    - items:
      - name: Compensation Of Employees
        total_budget: 45508917.63
        type: economic_classification_2
      - name: Goods And Services
        total_budget: 24902238.3
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Machinery And Equipment
        total_budget: 1668452.0990000002
        type: economic_classification_2
      name: Payments For Capital Assets
      type: economic_classification_1
    - items:
      - name: Public Corporations And Private Enterprises
        total_budget: 224296.0
        type: economic_classification_2
      name: Transfers And Subsidies
      type: economic_classification_1
    name: Administration
    type: programme
  - items:
    - items:
      - name: Compensation Of Employees
        total_budget: 30512000.0
        type: economic_classification_2
      - name: Goods And Services
        total_budget: 4501000.0
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Machinery And Equipment
        total_budget: 174000.0
        type: economic_classification_2
      name: Payments For Capital Assets
      type: economic_classification_1
    name: Biodiversity Management
    type: programme
  - items:
    - items:
      - name: Compensation Of Employees
        total_budget: 8662000.0
        type: economic_classification_2
      - name: Goods And Services
        total_budget: 1646000.0
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Machinery And Equipment
        total_budget: 178000.0
        type: economic_classification_2
      name: Payments For Capital Assets
      type: economic_classification_1
    name: Compliance And Enforcement
    type: programme
  - items:
    - items:
      - name: Compensation Of Employees
        total_budget: 12597771.492
        type: economic_classification_2
      - name: Goods And Services
        total_budget: 1256863.1303
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Machinery And Equipment
        total_budget: 135267.08500000002
        type: economic_classification_2
      name: Payments For Capital Assets
      type: economic_classification_1
    name: Environmental Empowerment Services
    type: programme
  - items:
    - items:
      - name: Compensation Of Employees
        total_budget: 10750522.8349
        type: economic_classification_2
      - name: Goods And Services
        total_budget: 575958.8222
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Machinery And Equipment
        total_budget: 59813.8521
        type: economic_classification_2
      name: Payments For Capital Assets
      type: economic_classification_1
    name: Environmental Policy,Planning And Coordination
    type: programme
  - items:
    - items:
      - name: Compensation Of Employees
        total_budget: 10842846.679
        type: economic_classification_2
      - name: Goods And Services
        total_budget: 3668765.6001
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Machinery And Equipment
        total_budget: 123424.89589999999
        type: economic_classification_2
      name: Payments For Capital Assets
      type: economic_classification_1
    name: Environmental Quality Management
    type: programme
expenditure_over_time:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2018-19
  expenditure:
    base_financial_year: 2017-18
    nominal:
    - amount: 127586000.0
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 133652000.0
      financial_year: 2015-16
      phase: Audited Outcome
    - amount: 140676000.0
      financial_year: 2016-17
      phase: Audited Outcome
    - amount: 152624580.0
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: 157988138.4205
      financial_year: 2018-19
      phase: Main appropriation
    - amount: 166457000.0
      financial_year: 2019-20
      phase: Medium Term Estimates
    - amount: 176064000.0
      financial_year: 2020-21
      phase: Medium Term Estimates
    real:
    - amount: 149596195
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 149009461
      financial_year: 2015-16
      phase: Audited Outcome
    - amount: 147551960
      financial_year: 2016-17
      phase: Audited Outcome
    - amount: 152624580
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: 149763693
      financial_year: 2018-19
      phase: Main appropriation
    - amount: 149862178
      financial_year: 2019-20
      phase: Medium Term Estimates
    - amount: 150189737
      financial_year: 2020-21
      phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2018-19
  is_selected: true
government:
  name: Northern Cape
  slug: northern-cape
government_functions: []
intro: ''
is_vote_primary: true
name: Environment And Nature Conservation
programme_by_economic_classification:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2018-19
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2018-19-shifted-econ-classes/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2018%257Cgovernment.government%253A%2522Northern%2BCape%2522%257Cdepartment.department%253A%2522Environment%2BAnd%2BNature%2BConservation%2522%26drilldown%3Dbudget_phase.budget_phase%257Cdepartment.department%257Ceconomic_classification_2.economic_classification_2%257Ceconomic_classification_3.economic_classification_3%257Ceconomic_classification_4.economic_classification_4%257Cfinancial_year.financial_year%257Cgovernment.government%257Cprogramme_number.programme%257Cprogramme_number.programme_number%26pagesize%3D10000
  econ_classes:
  - items:
    - name: Administration
      total_budget: 45508917.63
      type: programme
    - name: Biodiversity Management
      total_budget: 30512000.0
      type: programme
    - name: Environmental Empowerment Services
      total_budget: 12597771.492
      type: programme
    - name: Environmental Quality Management
      total_budget: 10842846.679
      type: programme
    - name: Environmental Policy,Planning And Coordination
      total_budget: 10750522.8349
      type: programme
    - name: Compliance And Enforcement
      total_budget: 8662000.0
      type: programme
    name: Current Payments - Compensation Of Employees
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 24902238.3
      type: programme
    - name: Biodiversity Management
      total_budget: 4501000.0
      type: programme
    - name: Environmental Quality Management
      total_budget: 3668765.6001
      type: programme
    - name: Compliance And Enforcement
      total_budget: 1646000.0
      type: programme
    - name: Environmental Empowerment Services
      total_budget: 1256863.1303
      type: programme
    - name: Environmental Policy,Planning And Coordination
      total_budget: 575958.8222
      type: programme
    name: Current Payments - Goods And Services
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 1668452.0990000002
      type: programme
    - name: Compliance And Enforcement
      total_budget: 178000.0
      type: programme
    - name: Biodiversity Management
      total_budget: 174000.0
      type: programme
    - name: Environmental Empowerment Services
      total_budget: 135267.08500000002
      type: programme
    - name: Environmental Quality Management
      total_budget: 123424.89589999999
      type: programme
    - name: Environmental Policy,Planning And Coordination
      total_budget: 59813.8521
      type: programme
    name: Payments For Capital Assets - Machinery And Equipment
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 224296.0
      type: programme
    name: Transfers And Subsidies - Public Corporations And Private Enterprises
    type: economic_classification_1_and_2
programmes:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2018-19
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aestimates-of-provincial-expenditure-south-africa-2018-19-shifted-econ-classes/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2018%257Cgovernment.government%253A%2522Northern%2BCape%2522%257Cdepartment.department%253A%2522Environment%2BAnd%2BNature%2BConservation%2522%26drilldown%3Dbudget_phase.budget_phase%257Cdepartment.department%257Ceconomic_classification_2.economic_classification_2%257Ceconomic_classification_3.economic_classification_3%257Ceconomic_classification_4.economic_classification_4%257Cfinancial_year.financial_year%257Cgovernment.government%257Cprogramme_number.programme%257Cprogramme_number.programme_number%26pagesize%3D10000
  programme_budgets:
  - name: Administration
    total_budget: 72303904.029
  - name: Environmental Policy,Planning And Coordination
    total_budget: 11386295.5092
  - name: Compliance And Enforcement
    total_budget: 10486000.0
  - name: Environmental Quality Management
    total_budget: 14635037.175
  - name: Biodiversity Management
    total_budget: 35187000.0
  - name: Environmental Empowerment Services
    total_budget: 13989901.7073
  - name: Direct Charges
    total_budget: 0.0
selected_financial_year: 2018-19
selected_tab: departments
slug: environment-and-nature-conservation
sphere:
  name: Provincial
  slug: provincial
subprogramme_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/epre-sub-programme-expenditure-2018-19
  department_data_csv: https://datamanager.vulekamali.gov.za/csv/?api_url=https%3A//openspending.org/api/3/cubes/b9d2af843f3a7ca223eea07fb608e62a%3Aepre-sub-programme-drilldown-2018-19-v2/aggregate/%3Fcut%3Dfinancial_year.financial_year%253A2018%257Cgovernment.government%253A%2522Northern%2BCape%2522%257Cdepartment.department%253A%2522Environment%2BAnd%2BNature%2BConservation%2522%26drilldown%3Dbudget_phase.budget_phase%257Cdepartment.department%257Cfinancial_year.financial_year%257Cgovernment.government%257Cprogramme.programme%257Csubprogramme.subprogramme%26pagesize%3D10000
  programmes:
  - items:
    - name: Corporate Services
      total_budget: 44203000.0
      type: subprogramme
    - name: Financial Management
      total_budget: 13963522.929299999
      type: subprogramme
    - name: Office of the MEC
      total_budget: 9761000.0
      type: subprogramme
    - name: Senior Management
      total_budget: 4376381.1
      type: subprogramme
    name: Administration
    type: programme
  - items:
    - name: Conservation agency and Services
      total_budget: 21903000.0
      type: subprogramme
    - name: Biodiversity Protected Area Planning and Management
      total_budget: 10714000.0
      type: subprogramme
    - name: Coastal Management
      total_budget: 2570000.0
      type: subprogramme
    name: BIODIVERSITY MANAGEMENT
    type: programme
  - items:
    - name: Biodiversity Management Authorisation,Compliance
      total_budget: 5796000.0
      type: subprogramme
    - name: Environmental Quality Management Authorisation
      total_budget: 4690000.0
      type: subprogramme
    name: COMPLIANCE AND ENFORCEMENT
    type: programme
  - items:
    - name: Environmental Capacity Developmental and Support
      total_budget: 9019901.709199999
      type: subprogramme
    - name: Environmental Communication and Awareness Raising
      total_budget: 4970000.0
      type: subprogramme
    name: ENVIRONMENTAL EMPOWERMENT SERVICES
    type: programme
  - items:
    - name: Research and Development Support
      total_budget: 6557250.953
      type: subprogramme
    - name: Intergovernmental Coord,Spartial and Development
      total_budget: 4000110.3433
      type: subprogramme
    - name: Environment Information Management
      total_budget: 816000.0
      type: subprogramme
    - name: Legislative Development
      total_budget: 12934.2087
      type: subprogramme
    name: ENVIRONMENTAL POLICY,PLANNING AND COORDINATION
    type: programme
  - items:
    - name: Impact Management
      total_budget: 6535783.1629
      type: subprogramme
    - name: Pollution and Waste Management
      total_budget: 4772254.012
      type: subprogramme
    - name: Air Quality Management
      total_budget: 3327000.0
      type: subprogramme
    name: Environmental Quality Management
    type: programme
title: Environment And Nature Conservation budget 2018-19  - vulekamali
vote_number: 13
vote_primary:
  name: Environment And Nature Conservation
  slug: environment-and-nature-conservation
  url_path: /2018-19/provincial/northern-cape/departments/environment-and-nature-conservation
