#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
description: 'Northern Cape department: Environment And Nature Conservation budget
  data for the 2018-19 financial year from National Treasury in partnership with IMALI
  YETHU.'
economic_classification_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2018-19
  programmes:
  - items:
    - items:
      - name: Compensation Of Employees
        total_budget: 45508917.63
        type: economic_classification_2
      - name: Goods And Services
        total_budget: 24902238.3
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Machinery And Equipment
        total_budget: 1668452.0990000002
        type: economic_classification_2
      name: Payments For Capital Assets
      type: economic_classification_1
    - items:
      - name: Public Corporations And Private Enterprises
        total_budget: 224296.0
        type: economic_classification_2
      name: Transfers And Subsidies
      type: economic_classification_1
    name: Administration
    type: programme
  - items:
    - items:
      - name: Compensation Of Employees
        total_budget: 30512000.0
        type: economic_classification_2
      - name: Goods And Services
        total_budget: 4501000.0
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Machinery And Equipment
        total_budget: 174000.0
        type: economic_classification_2
      name: Payments For Capital Assets
      type: economic_classification_1
    name: Biodiversity Management
    type: programme
  - items:
    - items:
      - name: Compensation Of Employees
        total_budget: 8662000.0
        type: economic_classification_2
      - name: Goods And Services
        total_budget: 1646000.0
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Machinery And Equipment
        total_budget: 178000.0
        type: economic_classification_2
      name: Payments For Capital Assets
      type: economic_classification_1
    name: Compliance And Enforcement
    type: programme
  - items:
    - items:
      - name: Compensation Of Employees
        total_budget: 12597771.492
        type: economic_classification_2
      - name: Goods And Services
        total_budget: 1256863.1303
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Machinery And Equipment
        total_budget: 135267.08500000002
        type: economic_classification_2
      name: Payments For Capital Assets
      type: economic_classification_1
    name: Environmental Empowerment Services
    type: programme
  - items:
    - items:
      - name: Compensation Of Employees
        total_budget: 10750522.8349
        type: economic_classification_2
      - name: Goods And Services
        total_budget: 575958.8222
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Machinery And Equipment
        total_budget: 59813.8521
        type: economic_classification_2
      name: Payments For Capital Assets
      type: economic_classification_1
    name: Environmental Policy,Planning And Coordination
    type: programme
  - items:
    - items:
      - name: Compensation Of Employees
        total_budget: 10842846.679
        type: economic_classification_2
      - name: Goods And Services
        total_budget: 3668765.6001
        type: economic_classification_2
      name: Current Payments
      type: economic_classification_1
    - items:
      - name: Machinery And Equipment
        total_budget: 123424.89589999999
        type: economic_classification_2
      name: Payments For Capital Assets
      type: economic_classification_1
    name: Environmental Quality Management
    type: programme
expenditure_over_time:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2018-19
  expenditure:
    base_financial_year: 2017-18
    nominal:
    - amount: 127586000.0
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 133652000.0
      financial_year: 2015-16
      phase: Audited Outcome
    - amount: 140676000.0
      financial_year: 2016-17
      phase: Audited Outcome
    - amount: 152624580.0
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: 157988138.4205
      financial_year: 2018-19
      phase: Main appropriation
    - amount: 166457000.0
      financial_year: 2019-20
      phase: Medium Term Estimates
    - amount: 176064000.0
      financial_year: 2020-21
      phase: Medium Term Estimates
    real:
    - amount: 149596195
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 149009461
      financial_year: 2015-16
      phase: Audited Outcome
    - amount: 147551960
      financial_year: 2016-17
      phase: Audited Outcome
    - amount: 152624580
      financial_year: 2017-18
      phase: Adjusted appropriation
    - amount: 149763693
      financial_year: 2018-19
      phase: Main appropriation
    - amount: 149862178
      financial_year: 2019-20
      phase: Medium Term Estimates
    - amount: 150189737
      financial_year: 2020-21
      phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2018-19
  is_selected: true
government:
  name: Northern Cape
  slug: northern-cape
government_functions: []
intro: ''
is_vote_primary: true
name: Environment And Nature Conservation
programme_by_economic_classification:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2018-19
  econ_classes:
  - items:
    - name: Administration
      total_budget: 45508917.63
      type: programme
    - name: Biodiversity Management
      total_budget: 30512000.0
      type: programme
    - name: Environmental Empowerment Services
      total_budget: 12597771.492
      type: programme
    - name: Environmental Quality Management
      total_budget: 10842846.679
      type: programme
    - name: Environmental Policy,Planning And Coordination
      total_budget: 10750522.8349
      type: programme
    - name: Compliance And Enforcement
      total_budget: 8662000.0
      type: programme
    name: Current Payments - Compensation Of Employees
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 24902238.3
      type: programme
    - name: Biodiversity Management
      total_budget: 4501000.0
      type: programme
    - name: Environmental Quality Management
      total_budget: 3668765.6001
      type: programme
    - name: Compliance And Enforcement
      total_budget: 1646000.0
      type: programme
    - name: Environmental Empowerment Services
      total_budget: 1256863.1303
      type: programme
    - name: Environmental Policy,Planning And Coordination
      total_budget: 575958.8222
      type: programme
    name: Current Payments - Goods And Services
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 1668452.0990000002
      type: programme
    - name: Compliance And Enforcement
      total_budget: 178000.0
      type: programme
    - name: Biodiversity Management
      total_budget: 174000.0
      type: programme
    - name: Environmental Empowerment Services
      total_budget: 135267.08500000002
      type: programme
    - name: Environmental Quality Management
      total_budget: 123424.89589999999
      type: programme
    - name: Environmental Policy,Planning And Coordination
      total_budget: 59813.8521
      type: programme
    name: Payments For Capital Assets - Machinery And Equipment
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 224296.0
      type: programme
    name: Transfers And Subsidies - Public Corporations And Private Enterprises
    type: economic_classification_1_and_2
programmes:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2018-19
  programme_budgets:
  - name: Administration
    total_budget: 72303904.029
  - name: Environmental Policy,Planning And Coordination
    total_budget: 11386295.5092
  - name: Compliance And Enforcement
    total_budget: 10486000.0
  - name: Environmental Quality Management
    total_budget: 14635037.175
  - name: Biodiversity Management
    total_budget: 35187000.0
  - name: Environmental Empowerment Services
    total_budget: 13989901.7073
  - name: Direct Charges
    total_budget: 0.0
selected_financial_year: 2018-19
selected_tab: departments
slug: environment-and-nature-conservation
sphere:
  name: Provincial
  slug: provincial
title: Environment And Nature Conservation budget 2018-19  - vulekamali
treasury_datasets:
  EPRE for Vote 13 - Environment And Nature Conservation:
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: PDF
      url: https://data.vulekamali.gov.za/dataset/d6477113-b3e3-48fc-b58e-83f7b6cfa1d2/resource/0c1c0f5f-a831-4dc6-9cf0-a24ce325b4b1/download/nc-vote-13-environment-and-nature-conservation.pdf
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/d6477113-b3e3-48fc-b58e-83f7b6cfa1d2/resource/8f47c937-2100-4c09-968d-86317b54050d/download/nc-environ.-and-nature-conservation.xlsm
vote_number: 13
vote_primary:
  name: Environment And Nature Conservation
  slug: environment-and-nature-conservation
  url_path: /2018-19/provincial/northern-cape/departments/environment-and-nature-conservation
