#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/budget-analysis-for-advancing-socioeconomic-rights
description: 'Northern Cape department: Environment And Nature Conservation budget
  data for the 2018-19 financial year from National Treasury in partnership with IMALI
  YETHU.'
expenditure_over_time:
  base_financial_year: 2017-18
  nominal:
  - amount: 127586000.0
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 133652000.0
    financial_year: 2015-16
    phase: Audited Outcome
  - amount: 140676000.0
    financial_year: 2016-17
    phase: Audited Outcome
  - amount: 152624580.0
    financial_year: 2017-18
    phase: Adjusted appropriation
  - amount: 157988138.4205
    financial_year: 2018-19
    phase: Main appropriation
  - amount: 166457000.0
    financial_year: 2019-20
    phase: Medium Term Estimates
  - amount: 176064000.0
    financial_year: 2020-21
    phase: Medium Term Estimates
  real:
  - amount: 149596195
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 149009461
    financial_year: 2015-16
    phase: Audited Outcome
  - amount: 147551960
    financial_year: 2016-17
    phase: Audited Outcome
  - amount: 152624580
    financial_year: 2017-18
    phase: Adjusted appropriation
  - amount: 149763693
    financial_year: 2018-19
    phase: Main appropriation
  - amount: 149862178
    financial_year: 2019-20
    phase: Medium Term Estimates
  - amount: 150189737
    financial_year: 2020-21
    phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/northern-cape/departments/environment-and-nature-conservation
  id: 2018-19
  is_selected: true
government:
  name: Northern Cape
  slug: northern-cape
government_functions: []
intro: ''
is_vote_primary: true
name: Environment And Nature Conservation
programmes:
- name: Administration
  total_budget: 72303904.029
- name: Environmental Policy,Planning And Coordination
  total_budget: 11386295.5092
- name: Compliance And Enforcement
  total_budget: 10486000.0
- name: Environmental Quality Management
  total_budget: 14635037.175
- name: Biodiversity Management
  total_budget: 35187000.0
- name: Environmental Empowerment Services
  total_budget: 13989901.7073
- name: Direct Charges
  total_budget: 0.0
selected_financial_year: 2018-19
selected_tab: departments
slug: environment-and-nature-conservation
sphere:
  name: Provincial
  slug: provincial
title: Environment And Nature Conservation budget 2018-19  - vulekamali
treasury_datasets:
  EPRE for Vote 13 - Environment And Nature Conservation:
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: PDF
      url: https://data.vulekamali.gov.za/dataset/d6477113-b3e3-48fc-b58e-83f7b6cfa1d2/resource/0c1c0f5f-a831-4dc6-9cf0-a24ce325b4b1/download/nc-vote-13-environment-and-nature-conservation.pdf
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/d6477113-b3e3-48fc-b58e-83f7b6cfa1d2/resource/8f47c937-2100-4c09-968d-86317b54050d/download/nc-environ.-and-nature-conservation.xlsm
vote_number: 13
vote_primary:
  name: Environment And Nature Conservation
  slug: environment-and-nature-conservation
  url_path: /2018-19/provincial/northern-cape/departments/environment-and-nature-conservation
