financial_years:
- closest_match:
    is_exact_match: true
    name: Environmental Affairs and Development Planning
    organisational_unit: department
    slug: environmental-affairs-and-development-planning
    url_path: /2015-16/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Environmental Affairs and Development Planning
    organisational_unit: department
    slug: environmental-affairs-and-development-planning
    url_path: /2016-17/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Environmental Affairs and Development Planning
    organisational_unit: department
    slug: environmental-affairs-and-development-planning
    url_path: /2017-18/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2017-18
  is_selected: true
government:
  name: Western Cape
  slug: western-cape
name: Environmental Affairs and Development Planning
narrative: {}
resources:
  'EPRE for Vote 09 : Environmental Affairs and Development Planning':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://treasurydata.openup.org.za/dataset/566130c1-0c22-49d2-aa3c-4a8cfb167115/resource/b770aecf-ee96-4252-9e17-638cbb700ace/download/wc-environ.-affairs-and-dev-planning.xlsm
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2017/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/WC/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/WC
        - Vote 09 - Environmental Affairs and Development Planning.pdf
slug: environmental-affairs-and-development-planning
vote_number: 9
