#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
description: 'Western Cape department: Environmental Affairs and Development Planning
  budget data for the 2017-18 financial year from National Treasury in partnership
  with IMALI YETHU.'
economic_classification_by_programme:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2017-18
  programmes:
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 52540000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 9584000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 3530000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Households
        total_budget: 30000
        type: economic_classification_2
      - name: Departmental agencies and accounts
        total_budget: 5000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Administration
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 7985000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 6552000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 25000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Departmental agencies and accounts
        total_budget: 287050000
        type: economic_classification_2
      - name: Non-profit institutions
        total_budget: 800000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Biodiversity Management
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 20995000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 3704000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 128000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    name: Compliance and Enforcement
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 47109000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 10564000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 211000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Provinces and municipalities
        total_budget: 21350000
        type: economic_classification_2
      - name: Non-profit institutions
        total_budget: 5100000
        type: economic_classification_2
      - name: Departmental agencies and accounts
        total_budget: 1000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Development Planning
    type: programme
  - items:
    - items:
      - name: Goods and services
        total_budget: 2111000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Provinces and municipalities
        total_budget: 500000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Environmental Empowerment Services
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 14403000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 5604000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 22000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Public corporations and private enterprises
        total_budget: 630000
        type: economic_classification_2
      - name: Non-profit institutions
        total_budget: 400000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Environmental Policy, Planning and Coordination
    type: programme
  - items:
    - items:
      - name: Compensation of employees
        total_budget: 62819000
        type: economic_classification_2
      - name: Goods and services
        total_budget: 25635000
        type: economic_classification_2
      name: Current payments
      type: economic_classification_1
    - items:
      - name: Machinery and equipment
        total_budget: 1181000
        type: economic_classification_2
      name: Payments for capital assets
      type: economic_classification_1
    - items:
      - name: Public corporations and private enterprises
        total_budget: 1000000
        type: economic_classification_2
      - name: Departmental agencies and accounts
        total_budget: 2000
        type: economic_classification_2
      name: Transfers and subsidies
      type: economic_classification_1
    name: Environmental Quality Management
    type: programme
expenditure_over_time:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2017-18
  expenditure:
    base_financial_year: 2017-18
    nominal:
    - amount: 412199000
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 457181000
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 502648000
      financial_year: 2015-16
      phase: Audited Outcome
    - amount: 543699000
      financial_year: 2016-17
      phase: Adjusted appropriation
    - amount: 591570000
      financial_year: 2017-18
      phase: Main appropriation
    - amount: 588153000
      financial_year: 2018-19
      phase: Medium Term Estimates
    - amount: 607656000
      financial_year: 2019-20
      phase: Medium Term Estimates
    real:
    - amount: 510499421
      financial_year: 2013-14
      phase: Audited Outcome
    - amount: 536050492
      financial_year: 2014-15
      phase: Audited Outcome
    - amount: 560405441
      financial_year: 2015-16
      phase: Audited Outcome
    - amount: 570273917
      financial_year: 2016-17
      phase: Adjusted appropriation
    - amount: 591570000
      financial_year: 2017-18
      phase: Main appropriation
    - amount: 557535310
      financial_year: 2018-19
      phase: Medium Term Estimates
    - amount: 547076134
      financial_year: 2019-20
      phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2017-18
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2018-19
  is_selected: false
government:
  name: Western Cape
  slug: western-cape
government_functions: []
intro: "## Vision\n\nA resilient, sustainable, quality and inclusive living environment.\r\
  \n\r\n\n\n## Mission\n\nTo promote a resilient, sustainable, quality and inclusive\
  \ living environment in support of human well-being.\r\n\r\n\n\n## Core functions\
  \ and responsibilities\n\nThe core functions of the Department of Environmental\
  \ Affairs and Development Planning are to promote\r\nsustainable economic development\
  \ and social equity by upholding the environmental integrity of the\r\nWestern Cape.\
  \ This will be achieved through:\r\n\r\n* Ensuring cohesive and integrated environmental\
  \ governance;\r\n\r\n* Strategically advancing environmental sustainability;\r\n\
  \r\n* Sustaining the environmental quality; and\r\n\r\n* Ensuring integrated environmental\
  \ and land management in the Western Cape."
is_vote_primary: true
name: Environmental Affairs and Development Planning
programme_by_economic_classification:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2017-18
  econ_classes:
  - items:
    - name: Environmental Quality Management
      total_budget: 62819000
      type: programme
    - name: Administration
      total_budget: 52540000
      type: programme
    - name: Development Planning
      total_budget: 47109000
      type: programme
    - name: Compliance and Enforcement
      total_budget: 20995000
      type: programme
    - name: Environmental Policy, Planning and Coordination
      total_budget: 14403000
      type: programme
    - name: Biodiversity Management
      total_budget: 7985000
      type: programme
    name: Current payments - Compensation of employees
    type: economic_classification_1_and_2
  - items:
    - name: Environmental Quality Management
      total_budget: 25635000
      type: programme
    - name: Development Planning
      total_budget: 10564000
      type: programme
    - name: Administration
      total_budget: 9584000
      type: programme
    - name: Biodiversity Management
      total_budget: 6552000
      type: programme
    - name: Environmental Policy, Planning and Coordination
      total_budget: 5604000
      type: programme
    - name: Compliance and Enforcement
      total_budget: 3704000
      type: programme
    - name: Environmental Empowerment Services
      total_budget: 2111000
      type: programme
    name: Current payments - Goods and services
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 3530000
      type: programme
    - name: Environmental Quality Management
      total_budget: 1181000
      type: programme
    - name: Development Planning
      total_budget: 211000
      type: programme
    - name: Compliance and Enforcement
      total_budget: 128000
      type: programme
    - name: Biodiversity Management
      total_budget: 25000
      type: programme
    - name: Environmental Policy, Planning and Coordination
      total_budget: 22000
      type: programme
    name: Payments for capital assets - Machinery and equipment
    type: economic_classification_1_and_2
  - items:
    - name: Biodiversity Management
      total_budget: 287050000
      type: programme
    - name: Administration
      total_budget: 5000
      type: programme
    - name: Environmental Quality Management
      total_budget: 2000
      type: programme
    - name: Development Planning
      total_budget: 1000
      type: programme
    name: Transfers and subsidies - Departmental agencies and accounts
    type: economic_classification_1_and_2
  - items:
    - name: Administration
      total_budget: 30000
      type: programme
    name: Transfers and subsidies - Households
    type: economic_classification_1_and_2
  - items:
    - name: Development Planning
      total_budget: 5100000
      type: programme
    - name: Biodiversity Management
      total_budget: 800000
      type: programme
    - name: Environmental Policy, Planning and Coordination
      total_budget: 400000
      type: programme
    name: Transfers and subsidies - Non-profit institutions
    type: economic_classification_1_and_2
  - items:
    - name: Development Planning
      total_budget: 21350000
      type: programme
    - name: Environmental Empowerment Services
      total_budget: 500000
      type: programme
    name: Transfers and subsidies - Provinces and municipalities
    type: economic_classification_1_and_2
  - items:
    - name: Environmental Quality Management
      total_budget: 1000000
      type: programme
    - name: Environmental Policy, Planning and Coordination
      total_budget: 630000
      type: programme
    name: Transfers and subsidies - Public corporations and private enterprises
    type: economic_classification_1_and_2
programmes:
  dataset_detail_page: /datasets/estimates-of-provincial-expenditure/estimates-of-provincial-expenditure-2017-18
  programme_budgets:
  - name: Administration
    total_budget: 65689000
  - name: Environmental Policy, Planning and Coordination
    total_budget: 21059000
  - name: Compliance and Enforcement
    total_budget: 24827000
  - name: Environmental Quality Management
    total_budget: 90637000
  - name: Biodiversity Management
    total_budget: 302412000
  - name: Environmental Empowerment Services
    total_budget: 2611000
  - name: Development Planning
    total_budget: 84335000
selected_financial_year: 2017-18
selected_tab: departments
slug: environmental-affairs-and-development-planning
sphere:
  name: Provincial
  slug: provincial
title: Environmental Affairs and Development Planning budget 2017-18  - vulekamali
treasury_datasets:
  'EPRE for Vote 09 : Environmental Affairs and Development Planning':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/566130c1-0c22-49d2-aa3c-4a8cfb167115/resource/b770aecf-ee96-4252-9e17-638cbb700ace/download/wc-environ.-affairs-and-dev-planning.xlsm
    - format: PDF
      url: https://data.vulekamali.gov.za/dataset/566130c1-0c22-49d2-aa3c-4a8cfb167115/resource/e5fc0223-936f-4d61-9af6-27a0c6168422/download/wc-vote-09-environmental-affairs-and-dev.-planning.pdf
vote_number: 9
vote_primary:
  name: Environmental Affairs and Development Planning
  slug: environmental-affairs-and-development-planning
  url_path: /2017-18/provincial/western-cape/departments/environmental-affairs-and-development-planning
