contributed_datasets: null
financial_years:
- closest_match:
    is_exact_match: true
    name: Environmental Affairs and Development Planning
    slug: environmental-affairs-and-development-planning
    url_path: /2015-16/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Environmental Affairs and Development Planning
    slug: environmental-affairs-and-development-planning
    url_path: /2016-17/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Environmental Affairs and Development Planning
    slug: environmental-affairs-and-development-planning
    url_path: /2017-18/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2017-18
  is_selected: true
- closest_match:
    is_exact_match: false
    name: Western Cape
    slug: western-cape
    url_path: /2018-19/provincial/western-cape
  id: 2018-19
  is_selected: false
government:
  name: Western Cape
  slug: western-cape
government_functions: []
intro: "## Vision\n\nA resilient, sustainable, quality and inclusive living environment.\r\
  \n\r\n\n\n## Mission\n\nTo promote a resilient, sustainable, quality and inclusive\
  \ living environment in support of human well-being.\r\n\r\n\n\n## Core functions\
  \ and responsibilities\n\nThe core functions of the Department of Environmental\
  \ Affairs and Development Planning are to promote\r\nsustainable economic development\
  \ and social equity by upholding the environmental integrity of the\r\nWestern Cape.\
  \ This will be achieved through:\r\n\r\n* Ensuring cohesive and integrated environmental\
  \ governance;\r\n\r\n* Strategically advancing environmental sustainability;\r\n\
  \r\n* Sustaining the environmental quality; and\r\n\r\n* Ensuring integrated environmental\
  \ and land management in the Western Cape."
is_vote_primary: true
name: Environmental Affairs and Development Planning
programmes:
- name: Administration
  total_budget: 65689000.0
- name: Environmental Policy, Planning and Coordination
  total_budget: 21059000.0
- name: Compliance and Enforcement
  total_budget: 24827000.0
- name: Environmental Quality Management
  total_budget: 90637000.0
- name: Biodiversity Management
  total_budget: 302412000.0
- name: Environmental Empowerment Services
  total_budget: 2611000.0
- name: Development Planning
  total_budget: 84335000.0
selected_financial_year: 2017-18
selected_tab: departments
slug: environmental-affairs-and-development-planning
sphere:
  name: Provincial
  slug: provincial
title: Environmental Affairs and Development Planning - vulekamali
treasury_datasets:
  'EPRE for Vote 09 : Environmental Affairs and Development Planning':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/566130c1-0c22-49d2-aa3c-4a8cfb167115/resource/b770aecf-ee96-4252-9e17-638cbb700ace/download/wc-environ.-affairs-and-dev-planning.xlsm
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2017/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/WC/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/WC%20-%20Vote%2009%20-%20Environmental%20Affairs%20and%20Dev.%20Planning.pdf
vote_number: 9
vote_primary:
  name: Environmental Affairs and Development Planning
  slug: environmental-affairs-and-development-planning
  url_path: /2017-18/provincial/western-cape/departments/environmental-affairs-and-development-planning
