financial_years:
- closest_match:
    is_exact_match: true
    name: Environmental Affairs and Development Planning
    organisational_unit: department
    url_path: /2015-16/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Environmental Affairs and Development Planning
    organisational_unit: department
    url_path: /2016-17/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    name: Environmental Affairs and Development Planning
    organisational_unit: department
    url_path: /2017-18/provincial/western-cape/departments/environmental-affairs-and-development-planning
  id: 2017-18
  is_selected: true
government:
  name: Western Cape
name: Environmental Affairs and Development Planning
vote_number: 9
