#########################################
#  GENERATED FILE. Don't edit by hand.  #
#########################################

contributed_datasets:
- contributor: International Budget Partnership
  name: How Does Civil Society Use Budget Information?
  url_path: /datasets/contributed/how-does-civil-society-use-budget-information
- contributor: International Budget Partnership
  name: How transparent and participatory are the budgets of Metropolitan Municipalities
    in South Africa?
  url_path: /datasets/contributed/how-transparent-and-participatory-are-the-budgets-of-metropolitan-municipalities-in-south-africa
- contributor: International Budget Partnership
  name: A Guide to Conducting Social Audits in South Africa
  url_path: /datasets/contributed/a-guide-to-conducting-social-audits-in-south-africa
- contributor: Studies in Poverty and Inequality Institute
  name: Budget Analysis for Advancing Socioeconomic Rights
  url_path: /datasets/contributed/budget-analysis-for-advancing-socioeconomic-rights
description: 'National department: Environmental Affairs budget data for the 2018-19
  financial year from National Treasury in partnership with IMALI YETHU.'
economic_classification_by_programme:
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 427858000.0
    - economic_classification_2_name: Goods and services
      total_budget: 342599000.0
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Buildings and other fixed structures
      total_budget: 147375000.0
    - economic_classification_2_name: Machinery and equipment
      total_budget: 7060000.0
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Foreign governments and international organisations
      total_budget: 16928000.0
  programme_name: Administration
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 81143000.0
    - economic_classification_2_name: Goods and services
      total_budget: 38512000.0
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 799000.0
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Departmental agencies and accounts
      total_budget: 650609000.0
    - economic_classification_2_name: Non-profit institutions
      total_budget: 2287000.0
  programme_name: Biodiversity and Conservation
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Goods and services
      total_budget: 127514000.0
    - economic_classification_2_name: Compensation of employees
      total_budget: 62191000.0
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 670000.0
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Departmental agencies and accounts
      total_budget: 359879000.0
  programme_name: Chemicals and Waste Management
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 71129000.0
    - economic_classification_2_name: Goods and services
      total_budget: 20467000.0
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 1299000.0
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Departmental agencies and accounts
      total_budget: 199975000.0
    - economic_classification_2_name: Non-profit institutions
      total_budget: 1638000.0
  programme_name: Climate Change and Air Quality
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 252009000.0
    - economic_classification_2_name: Goods and services
      total_budget: 189245000.0
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 3808000.0
  - economic_classification_1_name: Transfers and subsidies
    items:
    - economic_classification_2_name: Households
      total_budget: 2998640000.0
    - economic_classification_2_name: Departmental agencies and accounts
      total_budget: 332579000.0
    - economic_classification_2_name: Public corporations and private enterprises
      total_budget: 95000000.0
  programme_name: Environmental Programmes
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Compensation of employees
      total_budget: 124243000.0
    - economic_classification_2_name: Goods and services
      total_budget: 63393000.0
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 1688000.0
  programme_name: Legal, Authorisations, Compliance and Enforcement
- items:
  - economic_classification_1_name: Current payments
    items:
    - economic_classification_2_name: Goods and services
      total_budget: 345900000.0
    - economic_classification_2_name: Compensation of employees
      total_budget: 130447000.0
  - economic_classification_1_name: Payments for capital assets
    items:
    - economic_classification_2_name: Machinery and equipment
      total_budget: 15648000.0
  programme_name: Oceans and Coasts
expenditure_over_time:
  base_financial_year: 2017-18
  nominal:
  - amount: 5675059000.0
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 5937920000.0
    financial_year: 2015-16
    phase: Audited Outcome
  - amount: 6380971000.0
    financial_year: 2016-17
    phase: Audited Outcome
  - amount: 6848214000.0
    financial_year: 2017-18
    phase: Adjusted appropriation
  - amount: 7112532000.0
    financial_year: 2018-19
    phase: Main appropriation
  - amount: 7531838000.0
    financial_year: 2019-20
    phase: Medium Term Estimates
  - amount: 7969308000.0
    financial_year: 2020-21
    phase: Medium Term Estimates
  real:
  - amount: 6654078300
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 6620224646
    financial_year: 2015-16
    phase: Audited Outcome
  - amount: 6692860073
    financial_year: 2016-17
    phase: Audited Outcome
  - amount: 6848214000
    financial_year: 2017-18
    phase: Adjusted appropriation
  - amount: 6742272400
    financial_year: 2018-19
    phase: Main appropriation
  - amount: 6780956358
    financial_year: 2019-20
    phase: Medium Term Estimates
  - amount: 6798143147
    financial_year: 2020-21
    phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/national/departments/environmental-affairs
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/national/departments/environmental-affairs
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/national/departments/environmental-affairs
  id: 2017-18
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2018-19/national/departments/environmental-affairs
  id: 2018-19
  is_selected: true
government:
  name: South Africa
  slug: south-africa
government_functions: []
intro: "## Vote purpose\n\nLead South Africa's environmental sector to achieve sustainable\
  \ development towards a better quality of life for all. \n\n## Mandate\n\nThe Department\
  \ of Environmental Affairs is mandated to give effect to the right of citizens to\
  \ an environment that is not harmful to their health or wellbeing, and to have the\
  \ environment protected for the benefit of present and future generations. To this\
  \ end, the department provides leadership in environmental management, conservation\
  \ and protection towards sustainability for the benefit of South Africans and the\
  \ global community.\n\nThis mandate is derived from the following legislation:\n\
  \n * the National Environmental Management Act (1998), which provides for specific\
  \ legislation on biodiversity and heritage resources; oceans and coasts; climate\
  \ change and air quality management; and waste and chemicals management\n * the\
  \ National Environmental Management Amendment Act (2004), which streamlines the\
  \ process of regulating and administering the environmental impact assessment process\n\
  \ * the National Environmental Management: Protected Areas Amendment Act (2009),\
  \ which provides for the assignment of national parks, special parks and heritage\
  \ sites to South Africa in terms of the World Heritage Convention Act (1999)\n *\
  \ the National Environmental Management: Biodiversity Act (2004), which significantly\
  \ reforms South Africa\u2019s laws regulating biodiversity\n * the National Environmental\
  \ Management: Air Quality and Atmospheric Act (2004), which reforms the law regulating\
  \ air quality in order to protect the environment by providing reasonable measures\
  \ for preventing pollution and ecological degradation, and securing ecologically\
  \ sustainable development; and provides for national norms and standards regulating\
  \ the monitoring of air quality\n * the National Environmental Management: Waste\
  \ Act (2008), which reforms the law regulating waste management in order to protect\
  \ health and the environment by providing reasonable measures for the prevention\
  \ of pollution\n * the National Environmental Management: Integrated Coastal Management\
  \ Act (2008), which promotes the conservation of the coastal environment and ensures\
  \ sustainable development practices and the use of natural resources.\n\n"
is_vote_primary: true
name: Environmental Affairs
programmes:
- name: Administration
  total_budget: 941820000.0
- name: Legal, Authorisations, Compliance and Enforcement
  total_budget: 189324000.0
- name: Oceans and Coasts
  total_budget: 491995000.0
- name: Climate Change and Air Quality
  total_budget: 294508000.0
- name: Biodiversity and Conservation
  total_budget: 773350000.0
- name: Environmental Programmes
  total_budget: 3871281000.0
- name: Chemicals and Waste Management
  total_budget: 550254000.0
selected_financial_year: 2018-19
selected_tab: departments
slug: environmental-affairs
sphere:
  name: National
  slug: national
title: Environmental Affairs budget 2018-19  - vulekamali
treasury_datasets:
  ENE for Vote 27 - Environmental Affairs:
    description: The Estimates of National Expenditure (ENE) sets out the detailed
      spending plans of each government department for the coming year.
    formats:
    - format: PDF
      url: https://data.vulekamali.gov.za/dataset/nat-dept-environmental-affairs-2018-19/resource/2834953b-8379-4b41-a6b3-cbe5c9969ea9/download/vote-27-environmental-affairs.pdf
    - format: XLSX
      url: https://data.vulekamali.gov.za/dataset/nat-dept-environmental-affairs-2018-19/resource/ccff34e2-d947-4545-8ccd-f3e030615bb9/download/ene18-vote27_chaptertables.xlsx
vote_number: 27
vote_primary:
  name: Environmental Affairs
  slug: environmental-affairs
  url_path: /2018-19/national/departments/environmental-affairs
