contributed_datasets:
- contributor: Heinrich Boell Foundation
  name: 'Housing women who have experienced abuse: policy, funding & practice (Mpumalanga)'
  url_path: /datasets/housing-women-who-have-experienced-abuse-policy-funding-practice-mpumalanga
description: 'Limpopo department: Economic Development, Environment and Tourism budget
  data for the 2017-18 financial year from National Treasury in partnership with IMALI
  YETHU.'
expenditure_over_time:
  base_financial_year: 2017-18
  nominal:
  - amount: 1071242000
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 1112393000
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 1153443000
    financial_year: 2015-16
    phase: Audited Outcome
  - amount: 1350120000
    financial_year: 2016-17
    phase: Adjusted appropriation
  - amount: 1500308000
    financial_year: 2017-18
    phase: Main appropriation
  - amount: 1293355000
    financial_year: 2018-19
    phase: Medium Term Estimates
  - amount: 1368375000
    financial_year: 2019-20
    phase: Medium Term Estimates
  real:
  - amount: 1326709723
    financial_year: 2013-14
    phase: Audited Outcome
  - amount: 1304294831
    financial_year: 2014-15
    phase: Audited Outcome
  - amount: 1285980911
    financial_year: 2015-16
    phase: Audited Outcome
  - amount: 1416111159
    financial_year: 2016-17
    phase: Adjusted appropriation
  - amount: 1500308000
    financial_year: 2017-18
    phase: Main appropriation
  - amount: 1226026360
    financial_year: 2018-19
    phase: Medium Term Estimates
  - amount: 1231955753
    financial_year: 2019-20
    phase: Medium Term Estimates
financial_years:
- closest_match:
    is_exact_match: true
    url_path: /2015-16/provincial/limpopo/departments/economic-development-environment-and-tourism
  id: 2015-16
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2016-17/provincial/limpopo/departments/economic-development-environment-and-tourism
  id: 2016-17
  is_selected: false
- closest_match:
    is_exact_match: true
    url_path: /2017-18/provincial/limpopo/departments/economic-development-environment-and-tourism
  id: 2017-18
  is_selected: true
- closest_match:
    is_exact_match: true
    url_path: /2018-19/provincial/limpopo/departments/economic-development-environment-and-tourism
  id: 2018-19
  is_selected: false
government:
  name: Limpopo
  slug: limpopo
government_functions:
- Economic affairs
intro: "## Vision\r\n\r\nA competitive economy within a sustainable environment.\r\
  \n\r\n\r\n\r\n## Mission\r\n\r\nTo create and facilitate the development of a competitive\
  \ economy, sustainable environment and tourism growth.\r\n\r\n\r\n\r\n## Core functions\r\
  \n\r\nThe mandate of the Department is to facilitate the provincial economy, promote\
  \ and manage environmental and tourism activities. To carry out this mandate, the\
  \ department pursues the following:\r\n\r\n* Ensuring the promotion of economic\
  \ planning, conducting research and implementation and monitoring of economic development\
  \ programs;\r\n\r\n* Creating an enabling environment for SMMEs and Co-operatives\
  \ to succeed in order to improve the quality of life of the people of Limpopo Province;\r\
  \n\r\n* Stimulating economic growth through industry development, trade and investment\
  \ promotion;\r\n\r\n* Ensuring that businesses in all sectors are regulated and\
  \ an environment created whereby consumers are effectively protected;\r\n\r\n* Ensuring\
  \ sustainable environmental management, utilisation and regulation of natural resources;\r\
  \n\r\n* Ensuring protection and sustainable natural resource management and utilisation;\r\
  \n\r\n* Providing environmental empowerment support services; and\r\n\r\n* Ensure\
  \ regulation, promotion and development of tourism in the province."
is_vote_primary: true
name: Economic Development, Environment and Tourism
programmes:
- name: ADMINISTRATION
  total_budget: 363183000
- name: ECONOMIC DEVELOPMENT
  total_budget: 620068000
- name: ENVIRONMENTAL AFFAIRS
  total_budget: 374820000
- name: TOURISM
  total_budget: 142237000
selected_financial_year: 2017-18
selected_tab: departments
slug: economic-development-environment-and-tourism
sphere:
  name: Provincial
  slug: provincial
title: Economic Development, Environment and Tourism budget 2017-18  - vulekamali
treasury_datasets:
  'EPRE for Vote 06 : Economic Development, Environment and Tourism':
    description: The Estimates of Provincial Revenue and Expenditure (EPRE) sets out
      the detailed spending plans of each government department for the coming year.
    formats:
    - format: XLSM
      url: https://data.vulekamali.gov.za/dataset/1d9b7b92-2fc0-411c-9ca7-5a42b8bbd8b6/resource/b092484a-8c4f-4018-9935-781ba3288ef7/download/lim-eco.-dev.-env.-and-tourism.xlsm
    - format: PDF
      url: http://www.treasury.gov.za/documents/provincial%20budget/2017/4.%20Estimates%20of%20Prov%20Rev%20and%20Exp/LIM/2.%20Estimates%20of%20Prov%20Rev%20and%20Exp/LIM
        - Vote 06 - Economic Dev., Environ. & Tourism.pdf
vote_number: 6
vote_primary:
  name: Economic Development, Environment and Tourism
  slug: economic-development-environment-and-tourism
  url_path: /2017-18/provincial/limpopo/departments/economic-development-environment-and-tourism
